### PR TITLE
fix(server): use a new db worker for hot updates

### LINKED ISSUE #2187: Is it correct that the Trivy Server Mode Vulnerability DB update is normal?
Is it correct that the current Trivy Server Mode Vulnerability DB update is normal?

The UpdatedAt/NextUpdate date will not change after the time you ran.
I would appreciate it if you can check if it is being updated normally.

```
$ trivy -v
Version: 0.27.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-05-12 06:06:17.231057123 +0000 UTC
  NextUpdate: 2022-05-12 12:06:17.231056623 +0000 UTC
  DownloadedAt: 2022-05-26 23:35:53.026928539 +0000 UTC


$ ls -alth
-rw-r--r-- 1 test test  153  5 27 08:35 metadata.json
-rw------- 1 test test 298M  5 27 08:35 trivy.db
```

### LINKED ISSUE #2579: can't update the trivy database in ClientServer mode
from @erikgb 

## Description
I am trying to use trivy in ClientServer mode to support scanning of images built in GitLab pipelines AND to offload the actual scan jobs for trivy-operator. While this works well for some time after startup of the trivy server, it seems to crash when trying to hot-update the vuln DB:

## What happened instead?
```sh
2022-07-18T00:15:19.588Z	[34mINFO[0m	Updating DB...
2022-07-18T00:15:19.608Z	[31mERROR[0m	failed DB hot update:
    github.com/aquasecurity/trivy/pkg/rpc/server.dbWorker.update
        /home/runner/work/trivy/trivy/pkg/rpc/server/listen.go:135
  - failed to download vulnerability DB:
    github.com/aquasecurity/trivy/pkg/rpc/server.dbWorker.hotUpdate
        /home/runner/work/trivy/trivy/pkg/rpc/server/listen.go:148
  - database download error:
    github.com/aquasecurity/trivy/pkg/db.(*Client).Download
        /home/runner/work/trivy/trivy/pkg/db/db.go:157
  - failed to fetch the layer:
    github.com/aquasecurity/trivy/pkg/oci.Artifact.Download
        /home/runner/work/trivy/trivy/pkg/oci/artifact.go:120
  - GET https://artifactory/.<company-domain>/v2/ghcr-docker-remote/aquasecurity/trivy-db/blobs/sha256:69a281fd44de250530862f193d73a259641f700646b1ad6b04a268308c08a20c: unexpected status code 404 Not Found: {"errors":[{"code":"BLOB_UNKNOWN","message":"blob unknown to registry","detail":{"blobSum":"sha256:69a281fd44de250530862f193d73a259641f700646b1ad6b04a268308c
```

## Additional details (base image name, container registry info...):
Note: We run in a semi air-gapped environment, and have to go through Artifactory for pulling all images. Which in this case means that I have configured trivy to use our mirror-proxy for downloading the DB. Using Helm to deploy trivy server, I have set value trivy.dbRepository=artifactory.<company-domain>/ghcr-docker-remote/aquasecurity/trivy-db . Any clues?

### PR DESCRIPTION
**Pull request by afdesk**
## Description
the first updating uses a new client instance, but `hotUpdate` uses the same client instance for all attempts.
we should use a new client for each update, because the client doesn't populate a new artifact.

## Related issues
- Close #2187
- Close #2579 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
I think we should add `Refresh` or something like that in `db.Client`. It forces to update `artifact`. We may want to change `populateOCIArtifact()` to `populateOCIArtifact(false bool)`.

```
func (c *Client) populateOCIArtifact(force bool) error {
	if c.artifact == nil || force {
		repo := fmt.Sprintf("%s:%d", c.dbRepository, db.SchemaVersion)
		art, err := oci.NewArtifact(repo, dbMediaType, c.quiet, c.insecureSkipTLSVerify)
		if err != nil {
			return xerrors.Errorf("OCI artifact error: %w", err)
		}
		c.artifact = art
	}
	return nil
}
```

File: pkg/db/db.go [hunk 1]
```diff
@@ -182,8 +182,8 @@ func (c *Client) updateDownloadedAt(dst string) error {
 	return nil
 }
 
-func (c *Client) populateOCIArtifact() error {
-	if c.artifact == nil {
+func (c *Client) populateOCIArtifact(force bool) error {
+	if c.artifact == nil || force {
```
Comment (knqyf263) [inline pkg/db/db.go:186]: I found `force` is always true... Can we simply populate it anytime by removing the if-statement?

Comment (afdesk) [reply pkg/db/db.go:186]: > I found `force` is always true... Can we simply populate it anytime by removing the if-statement?

yes, I wanted to write the same comment.

Comment (knqyf263) [reply pkg/db/db.go]: We should test it carefully, image scanning, client/server mode, Kubernetes scanning, etc. I don't remember, but there was a reason to avoid multiple initializations. It may be no longer necessary after some refactoring though.
