### PR TITLE
fix(sbom): use correct field for licenses in CycloneDX reports

### LINKED ISSUE #9042: bug(cyclonedx): incorrect field for licenses
## Description
CycloneDX supports 3 possible fields for licenses:
1. multiple licenses by ID - https://cyclonedx.org/docs/1.6/json/#tab-pane_components_items_licenses_oneOf_i0_items_license_oneOf_i0
2. multiple licenses by Name - https://cyclonedx.org/docs/1.6/json/#tab-pane_components_items_licenses_oneOf_i0_items_license_oneOf_i1
3. SPDX license expression - https://cyclonedx.org/docs/1.6/json/#tab-pane_components_items_licenses_oneOf_i1

We added handaling for SPDX licenses - #8077.
But we don't use similar logic for CycloneDX reports.
We use 2 way (licenses by Name) for all licenses:
https://github.com/aquasecurity/trivy/blob/454b8940986645de8fccc9e7b57db0deb600adaa/pkg/sbom/cyclonedx/marshal.go#L290-L292

But there are case when this is incorrect:
1. when license is SPDX license ID, but we use `name` instead of `id`
2. when license is SPDX expression (see #9033).

### Solution
We need to parse each got license before insert in in CycloneDX report:
1. for single license:
   1.2. check that this is SPDX license. Use `ID` field for SPDX license and `name` for another license.
2. for multiple licenses
   2.1. Use `SPDX expression` for valid SPDX expression
   2.2.for other cases split licenses and use `name`/`id` field for each license 

### Discussed in https://github.com/aquasecurity/trivy/discussions/9033

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
We need to use one of three correct field for component license (see #9042 for more details)

### Solution
Normalize and check each package license:
1. Single license:
   1.1. valid SPDX ID use licenseChoise.License.ID
   1.2. text license - use licenseChoise.License.Name
   1.3. invalid SPDX ID - use licenseChoise.License.Name
2. SPDX expression:
   1.4. all parts of expression are valid SPDX IDs/SPDX exceptions - use licenseChoise.Expression
   1.5. for other cases use licenseChoise.License.Name

### Examples of changes:
CycloneDX report for `centos:8`:
Before
```
...
          "license": {
            "name": "GPLv2+"
          }
...
          "license": {
            "name": "Public Domain"
          }
...
      "licenses": [
        {
          "license": {
            "name": "GPLv2+ and LGPLv2+"
          }
        }
...
          "license": {
            "name": "BSD with advertising"
          }
```
After:
```
...
          "license": {
            "id": "GPL-2.0-or-later"
          }
...
          "license": {
            "name": "Public-Domain"
          }
...
      "licenses": [
        {
          "expression": "GPL-2.0-or-later AND LGPL-2.0-or-later"
        }
...
          "license": {
            "name": "BSD-3-Clause WITH advertising"
          }
```
## Related issues
- Close #9042

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
I remember we did something similar for SPDX. If we define a method, can we avoid repeating code in SPDX and CycloneDX?

```diff
diff --git a/pkg/licensing/expression/types.go b/pkg/licensing/expression/types.go
index 7399f7462..c237464e1 100644
--- a/pkg/licensing/expression/types.go
+++ b/pkg/licensing/expression/types.go
@@ -14,6 +14,7 @@ var (
 
 type Expression interface {
 	String() string
+	IsSPDXLicense() bool
 }
 
 type Token struct {
@@ -42,6 +43,10 @@ func (s SimpleExpr) String() string {
 	return s.License
 }
 
+func (s SimpleExpr) IsSPDXLicense() bool {
+	return ValidateSPDXLicense(s.String())
+}
+
 type CompoundExpr struct {
 	left        Expression
 	conjunction Token
@@ -49,7 +54,11 @@ type CompoundExpr struct {
 }
 
 func NewCompoundExpr(left Expression, conjunction Token, right Expression) CompoundExpr {
-	return CompoundExpr{left: left, conjunction: conjunction, right: right}
+	return CompoundExpr{
+		left:        left,
+		conjunction: conjunction,
+		right:       right,
+	}
 }
 
 func (c CompoundExpr) Conjunction() Token {
@@ -81,3 +90,11 @@ func (c CompoundExpr) String() string {
 	}
 	return fmt.Sprintf("%s %s %s", left, c.conjunction.literal, right)
 }
+
+func (c CompoundExpr) IsSPDXLicense() bool {
+	if c.conjunction.token == WITH {
+		// e.g. A WITH B
+		return c.left.IsSPDXLicense() && ValidateSPDXException(c.right.String())
+	}
+	return c.left.IsSPDXLicense() && c.right.IsSPDXLicense()
+}
```

**Comment by DmitriyLewen** [comment]
I used your logic.
But I'm worried that the new logic is more confusing.

https://github.com/aquasecurity/trivy/pull/9057/commits/40ea83677a81a87a50f4c95bcec88ef5d95bdedc:
I used IsSPDXExpression function (but it function should check SPDX exception to correct work).
https://github.com/aquasecurity/trivy/pull/9057/commits/d621fc4f954007e2dd665ce590c957ad37c66866:
I optimized logic for SPDX:
- remove exception check for IsSPDXLicense
- don't check nested licenses for valid SPDX expression.

PS `expression.Normalize` function splits expressions, so exception can be simpeExpr.

**Comment by DmitriyLewen** [comment]
We can't skip validation for `replaceOtherLicenses`, because it doesn't work if last license expression is non-SPDX license.
https://github.com/aquasecurity/trivy/actions/runs/15873912882/job/44756852978?pr=9057

So it means that we will overcheck SPDX expressions.
e.g. `A or (B and C)` license
now we check once each license expression:
1. `A or (B and C)`
2. `A`
3. `B and C`
4. `B`
5. `C`

But after changes we will check:
1. `A or (B and C)`  + `A`, `B`, `C`, `B and C` 
2. `A`
3. `(B and C)` + `B` + `C`
4. `B`
5. `C`

**Comment by knqyf263** [comment]
To be honest, I still don’t quite understand why [this commit](https://github.com/aquasecurity/trivy/pull/9057/commits/d621fc4f954007e2dd665ce590c957ad37c66866) is necessary. I think the issue with unnecessary recursion could be resolved by simply returning a `SimpleExpr`.

```diff
diff --git a/pkg/sbom/spdx/marshal.go b/pkg/sbom/spdx/marshal.go
index e170beea2..e2aa9860e 100644
--- a/pkg/sbom/spdx/marshal.go
+++ b/pkg/sbom/spdx/marshal.go
@@ -451,7 +451,7 @@ func (m *Marshaler) normalizeLicenses(licenses []string) (string, []*spdx.OtherL
                        if e.IsSPDXExpression() {
                                // Use SimpleExpr for a valid SPDX license with an exception,
                                // to avoid parsing the license and exception separately.
-                               return e
+                               return expression.SimpleExpr{License: e.String()}
                        }
 
                        licenseName = e.String()
diff --git a/pkg/sbom/spdx/marshal_private_test.go b/pkg/sbom/spdx/marshal_private_test.go
index 60d7945ef..26c540d65 100644
--- a/pkg/sbom/spdx/marshal_private_test.go
+++ b/pkg/sbom/spdx/marshal_private_test.go
@@ -70,10 +70,24 @@ func TestMarshaler_normalizeLicenses(t *testing.T) {
                {
                        name: "happy path with WITH operator",
                        input: []string{
-                               "AFL 2.0",
+                               "GPLv2",
+                               "AFL 3.0 with wrong-exceptions",
+                               "LGPL 2.0 and unknown-license and GNU LESSER",
                                "AFL 3.0 with Autoconf-exception-3.0",
                        },
-                       wantLicenseName: "AFL-2.0 AND AFL-3.0 WITH Autoconf-exception-3.0",
+                       wantLicenseName: "GPL-2.0-only AND LicenseRef-51373b28fab165e9 AND LGPL-2.0-only AND LicenseRef-a0bb0951a6dfbdbe AND LGPL-2.1-only AND AFL-3.0 WITH Autoconf-exception-3.0",
+                       wantOtherLicenses: []*spdx.OtherLicense{
+                               {
+                                       LicenseIdentifier: "LicenseRef-51373b28fab165e9",
+                                       LicenseName:       "AFL-3.0 WITH wrong-exceptions",
+                                       ExtractedText:     `This component is licensed under "AFL-3.0 WITH wrong-exceptions"`,
+                               },
+                               {
+                                       LicenseIdentifier: "LicenseRef-a0bb0951a6dfbdbe",
+                                       LicenseName:       "unknown-license",
+                                       ExtractedText:     `This component is licensed under "unknown-license"`,
+                               },
+                       },
                },
                {
                        name: "happy path with non-SPDX exception",
```

Both the existing tests and the one you added are passing. If there are any cases that are failing, I’d appreciate it if you could share a test or an example.

**Comment by knqyf263** [comment]
Additionally, I'm unsure why we need a complex logic, like `sync.Once`, in CycloneDX. Am I missing something?

```diff
git diff pkg/sbom/cyclonedx/marshal.go 
diff --git a/pkg/sbom/cyclonedx/marshal.go b/pkg/sbom/cyclonedx/marshal.go
index 9c1e00e71..08314b051 100644
--- a/pkg/sbom/cyclonedx/marshal.go
+++ b/pkg/sbom/cyclonedx/marshal.go
@@ -8,7 +8,6 @@ import (
        "sort"
        "strconv"
        "strings"
-       "sync"
 
        cdx "github.com/CycloneDX/cyclonedx-go"
        "github.com/package-url/packageurl-go"
@@ -312,35 +311,33 @@ func (m *Marshaler) normalizeLicense(license string) cdx.LicenseChoice {
        license = strings.ReplaceAll(license, "-with-", " WITH ")
        license = strings.ReplaceAll(license, "-WITH-", " WITH ")
 
-       var licenseChoice cdx.LicenseChoice
-       onceValidateSPDXLicense := sync.Once{}
-       validateSPDXLicense := func(expr expression.Expression) expression.Expression {
-               // We only need to check the main license (not its parts).
-               onceValidateSPDXLicense.Do(func() {
-                       _, compoundExpr := expr.(expression.CompoundExpr)
-                       switch {
-                       case !expr.IsSPDXExpression():
-                               // Use licenseChoice.license.name for invalid SPDX ID / SPDX expression
-                               licenseChoice.License = &cdx.License{Name: expr.String()}
-                       case compoundExpr:
-                               // Use licenseChoice.expression for valid SPDX expression (with any conjunction)
-                               // e.g. "GPL-2.0 WITH Classpath-exception-2.0" or "GPL-2.0 AND MIT"
-                               licenseChoice.Expression = expr.String()
-                       default:
-                               // Use licenseChoice.license.id for valid SPDX ID
-                               licenseChoice.License = &cdx.License{ID: expr.String()}
-                       }
-               })
-
-               return expr
-       }
-
-       _, err := expression.Normalize(license, licensing.NormalizeLicense, expression.NormalizeForSPDX, validateSPDXLicense)
+       normalizedLicenses, err := expression.Normalize(license, licensing.NormalizeLicense, expression.NormalizeForSPDX)
        if err != nil {
                // Not fail on the invalid license
                m.logger.Warn("Unable to marshal SPDX licenses", log.String("license", license))
                return cdx.LicenseChoice{}
        }
+
+       // Case 1: the license is not a valid SPDX ID or SPDX expression
+       if !normalizedLicenses.IsSPDXExpression() {
+               // Use LicenseChoice.License.Name for invalid SPDX ID / SPDX expression
+               return cdx.LicenseChoice{
+                       License: &cdx.License{Name: normalizedLicenses.String()},
+               }
+       }
+
+       // Case 2: the license is a valid SPDX ID or SPDX expression
+       var licenseChoice cdx.LicenseChoice
+       switch normalizedLicenses.(type) {
+       case expression.SimpleExpr:
+               // Use LicenseChoice.License.ID for valid SPDX ID
+               licenseChoice.License = &cdx.License{ID: normalizedLicenses.String()}
+       case expression.CompoundExpr:
+               // Use LicenseChoice.Expression for valid SPDX expression (with any conjunction)
+               // e.g. "GPL-2.0 WITH Classpath-exception-2.0" or "GPL-2.0 AND MIT"
+               licenseChoice.Expression = normalizedLicenses.String()
+       }
+
        return licenseChoice
 }
 ```

**Comment by DmitriyLewen** [comment]
>  I think the issue with unnecessary recursion could be resolved by simply returning a SimpleExpr.

I don't know why i didn't think about this...
Thanks for help!

> like sync.Once, in CycloneDX

I don't know why i tried to solve this issue in `Normalize` function 😄 
Thanks!

I updated PR - https://github.com/aquasecurity/trivy/pull/9057/commits/94e9d07b2ebe7b7a64afba111bc1a320c96966fb
It should works now

File: pkg/licensing/expression/types.go [hunk 1]
```diff
@@ -14,6 +14,7 @@ var (
 
 type Expression interface {
 	String() string
+	IsSPDXLicense() bool
```
Comment (knqyf263) [inline pkg/licensing/expression/types.go]: Isn't `IsSPDXExpression` better than `IsSPDXLicense`? Both a single license and a compound license are also expressions according to [the spec](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/).

```
idstring = 1*(ALPHA / DIGIT / "-" / "." )

license-id = <short form license identifier in Annex A.1>

license-exception-id = <short form license exception identifier in Annex A.2>

license-ref = ["DocumentRef-"(idstring)":"]"LicenseRef-"(idstring)

simple-expression = license-id / license-id"+" / license-ref

compound-expression = (simple-expression /

  simple-expression "WITH" license-exception-id /

  compound-expression "AND" compound-expression /

  compound-expression "OR" compound-expression /

  "(" compound-expression ")" )

license-expression = (simple-expression / compound-expression)
```

Comment (DmitriyLewen) [reply pkg/licensing/expression/types.go]: I renamed this function because "IsSPDXLicense" was not quite correct.
I don't know why i renamed this function today...
Thanks!

updated in https://github.com/aquasecurity/trivy/pull/9057/commits/363074afaabde0e69ffe6f5f4e514ce16283cd5b
