### PR TITLE
fix(secret): update built-in rule `tests` 

### LINKED ISSUE #3801: Secrets not detected in subfolders with 'trivy fs'
## Description
I originally wanted (and still want) to scan an image, like the reporter of #3778. During debugging with the image's corresponding filesystem using `trivy fs` I noticed, that this doesn't detect secrets in files when they aren't located at the top level.

Given the file is located in the topmost folder:

```
wsluser@my_machine:/mnt/d/code/testprojects/secret_scanner_test/trivy/example/fs $ ls -la ./
total 0
drwxr-xr-x 1 wsluser wsluser 512 Mar  9 12:24 .
drwxr-xr-x 1 wsluser wsluser 512 Mar  9 11:09 ..
-rwxr--r-- 1 wsluser wsluser 103 Mar  9 11:07 test.txt
wsluser@my_machine:/mnt/d/code/testprojects/secret_scanner_test/trivy/example/fs $ cat test.txt
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
wsluser@my_machine:/mnt/d/code/testprojects/secret_scanner_test/trivy/example/fs $ trivy fs --scanners secret ./ --debug
2023-03-09T12:35:34.661+0100    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-03-09T12:35:34.663+0100    DEBUG   cache dir:  /home/wsluser/.cache/trivy
2023-03-09T12:35:34.663+0100    INFO    Secret scanning is enabled
2023-03-09T12:35:34.664+0100    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-03-09T12:35:34.664+0100    INFO    Please see also https://aquasecurity.github.io/trivy/v0.38/docs/secret/scanning/#recommendation for faster secret detection
2023-03-09T12:35:34.664+0100    DEBUG   No secret config detected: trivy-secret.yaml
2023-03-09T12:35:34.665+0100    DEBUG   Walk the file tree rooted at '.' in parallel
2023-03-09T12:35:34.672+0100    DEBUG   OS is not detected.
2023-03-09T12:35:34.672+0100    DEBUG   Secret file: test.txt

test.txt (secrets)

Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 2)

CRITICAL: AWS (aws-access-key-id)
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Access Key ID
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 test.txt:2
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   AWS_SECRET_ACCESS_KEY=****************************************
   2 [ AWS_ACCESS_KEY_ID=********************
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


CRITICAL: AWS (aws-secret-access-key)
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Secret Access Key
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 test.txt:1
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 [ AWS_SECRET_ACCESS_KEY=****************************************
   2   AWS_ACCESS_KEY_ID=********************
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

## What did you expect to happen?
Scan a folder and trivy reports secrets regardless of where in the folder structure the corresponding file is located.

## What happened instead?
When the file containing the secrets is at the topmost folder, `trivy fs` reports it. When it is located in a subfolder, the secret is not found.

## Output of run with `-debug`:

Given the file is in a subfolder:

```
wsluser@my_machine:/mnt/d/code/testprojects/secret_scanner_test/trivy/example_subfolder/fs $ ls -la
total 0
drwxr-xr-x 1 wsluser wsluser 512 Mar  9 12:26 .
drwxr-xr-x 1 wsluser wsluser 512 Mar  9 12:24 ..
drwxr-xr-x 1 wsluser wsluser 512 Mar  9 12:24 somefolder
wsluser@my_machine:/mnt/d/code/testprojects/secret_scanner_test/trivy/example_subfolder/fs $ ls -la somefolder/
total 0
drwxr-xr-x 1 wsluser wsluser 512 Mar  9 12:24 .
drwxr-xr-x 1 wsluser wsluser 512 Mar  9 12:26 ..
-rwxr--r-- 1 wsluser wsluser 103 Mar  9 11:07 test.txt
wsluser@my_machine:/mnt/d/code/testprojects/secret_scanner_test/trivy/example_subfolder/fs $ cat somefolder/test.txt
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
wsluser@my_machine:/mnt/d/code/testprojects/secret_scanner_test/trivy/example_subfolder/fs $ trivy fs --scanners secret ./ --debug
2023-03-09T12:37:51.567+0100    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-03-09T12:37:51.572+0100    DEBUG   cache dir:  /home/wsluser/.cache/trivy
2023-03-09T12:37:51.572+0100    INFO    Secret scanning is enabled
2023-03-09T12:37:51.572+0100    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-03-09T12:37:51.572+0100    INFO    Please see also https://aquasecurity.github.io/trivy/v0.38/docs/secret/scanning/#recommendation for faster secret detection
2023-03-09T12:37:51.572+0100    DEBUG   No secret config detected: trivy-secret.yaml
2023-03-09T12:37:51.573+0100    DEBUG   Walk the file tree rooted at '.' in parallel
2023-03-09T12:37:51.579+0100    DEBUG   OS is not detected.
```

## Output of `trivy -v`:

```
Version: 0.38.2
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-03-09 06:07:23.519086123 +0000 UTC
  NextUpdate: 2023-03-09 12:07:23.519085823 +0000 UTC
  DownloadedAt: 2023-03-09 09:25:17.02567 +0000 UTC
Policy Bundle:
  Digest: sha256:19a017cdc798631ad42f6f4dce823d77b2989128f0e1a7f9bc83ae3c59024edd
  DownloadedAt: 2023-03-08 11:58:35.3740422 +0000 UTC
```

## Additional details (base image name, container registry info...):
I linked #3778 because I'm not sure if the problem might be related, as `trivy image` for secret scanning for now also doesn't find secrets in files.

### PR DESCRIPTION
**Pull request by afdesk**
## Description

* fix built-in rule `tests` for skipping test files in the root folder
* add debug logs

## Related issues
- Close #3801 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/secret/scanner.go [hunk 1]
```diff
@@ -341,6 +341,7 @@ type Match struct {
 func (s *Scanner) Scan(args ScanArgs) types.Secret {
 	// Global allowed paths
 	if s.AllowPath(args.FilePath) {
+		log.Logger.Debugf("found global allowed paths %q", args.FilePath)
```
Comment (knqyf263) [inline pkg/fanal/secret/scanner.go:344]: We should clarify it is relevant to secret scanning.

```suggestion
		log.Logger.Debugf("Skipped secret scanning on %q matching allowed paths", args.FilePath)
```

File: pkg/fanal/secret/scanner.go [hunk 2]
```diff
@@ -355,11 +356,13 @@ func (s *Scanner) Scan(args ScanArgs) types.Secret {
 	for _, rule := range s.Rules {
 		// Check if the file path should be scanned by this rule
 		if !rule.MatchPath(args.FilePath) {
+			log.Logger.Debugf("%q skipped as non-compliant %q", args.FilePath, rule.ID)
```
Comment (knqyf263) [inline pkg/fanal/secret/scanner.go:359]: ditto

File: pkg/fanal/secret/scanner.go [hunk 3]
```diff
@@ -355,11 +356,13 @@ func (s *Scanner) Scan(args ScanArgs) types.Secret {
...
 			continue
 		}
 
 		// Check if the file path should be allowed
 		if rule.AllowPath(args.FilePath) {
+			log.Logger.Debugf("%q skipped as allowed", args.FilePath)
```
Comment (knqyf263) [inline pkg/fanal/secret/scanner.go:365]: same

File: pkg/fanal/secret/scanner.go [hunk 4]
```diff
@@ -409,6 +412,7 @@ func (s *Scanner) Scan(args ScanArgs) types.Secret {
 		return findings[i].Match < findings[j].Match
 	})
 
+	log.Logger.Debugf("%q contains secrets", args.FilePath)
```
Comment (knqyf263) [inline pkg/fanal/secret/scanner.go:415]: Do we need it? The detected secrets are shown in the result.

Comment (afdesk) [reply pkg/fanal/secret/scanner.go:415]: yes, sure. It's a redundant message

File: pkg/fanal/secret/scanner.go (hunk 1 above)
Comment (afdesk) [reply pkg/fanal/secret/scanner.go]: yes, sure

File: pkg/fanal/secret/scanner.go (hunk 2 above)
Comment (afdesk) [reply pkg/fanal/secret/scanner.go]: done

File: pkg/fanal/secret/scanner.go (hunk 3 above)
Comment (afdesk) [reply pkg/fanal/secret/scanner.go]: done

File: pkg/fanal/secret/builtin-allow-rules.go [hunk 5]
```diff
@@ -4,7 +4,7 @@ var builtinAllowRules = []AllowRule{
 	{
 		ID:          "tests",
 		Description: "Avoid test files and paths",
-		Path:        MustCompile(`(\/test|-test|_test|\.test)`),
+		Path:        MustCompile(`(^test|\/test|-test|_test|\.test)`),
```
Comment (afdesk) [inline pkg/fanal/secret/builtin-allow-rules.go:7]: @knqyf263 
there is a moment with this change.
the tests are failing, because Trivy is skipping `testdata` folder now.

as a workaround we can change `testdata` to `tstdata`, is it ok?

Comment (afdesk) [reply pkg/fanal/secret/builtin-allow-rules.go:7]: oh, this update can break a lot of places...

Comment (knqyf263) [reply pkg/fanal/secret/builtin-allow-rules.go:7]: >as a workaround we can change testdata to tstdata, is it ok?

No, `testdata` is defined in Go as ignored dirs.

>The go tool will ignore a directory named "testdata", making it available to hold ancillary data needed by the tests.

https://pkg.go.dev/cmd/go/internal/test

Comment (afdesk) [reply pkg/fanal/secret/builtin-allow-rules.go:7]: ok, i understood it. 
will try to skip this build-in rule

**Review by knqyf263 — APPROVED** [review]
