### PR TITLE
fix(sbom): use nuget purl type for dotnet-core

### LINKED ISSUE #2842: PURL format for nuget missing type
## Description

nuget PURLs in CycloneDX SBOMs do not follow the format defined by [purl-spec ](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#nuget)

## What did you expect to happen?

purls contain type of 'nuget' e.g.  - pkg:nuget/Azure.Core@1.25.0

## What happened instead?

No reference to nuget e.g. - "purl": "pkg:dotnet-core/Azure.Core@1.25.0"

## Output of run with `-debug`:

```
docker run -v D:/TrivyTest:/tmp/source  aquasec/trivy fs /tmp/source --format cyclonedx --debug
2022-09-08T07:59:23.019Z        DEBUG   ["cyclonedx" "spdx" "spdx-json" "github"] automatically enables '--list-all-pkgs'.
2022-09-08T07:59:23.019Z        DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-09-08T07:59:23.020Z        INFO    "--format cyclonedx" disables security checks. Specify "--security-checks vuln" explicitly if you want to include vulnerabilities in the CycloneDX report.
2022-09-08T07:59:23.037Z        DEBUG   cache dir:  /root/.cache/trivy
2022-09-08T07:59:23.156Z        DEBUG   OS is not detected.
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:62dd6634-fa97-4af2-9ea9-a36bc30f7b34",
  "version": 1,
  "metadata": {
    "timestamp": "2022-09-08T07:59:23+00:00",
    "tools": [
      {
        "vendor": "aquasecurity",
        "name": "trivy",
        "version": "0.31.3"
      }
    ],
    "component": {
      "bom-ref": "3a07a467-bf3d-4cd9-b10a-66b7ea4d3757",
      "type": "application",
      "name": "/tmp/source",
      "properties": [
        {
          "name": "aquasecurity:trivy:SchemaVersion",
          "value": "2"
        }
      ]
    }
  },
  "components": [
    {
      "bom-ref": "pkg:dotnet-core/Azure.Core@1.25.0",
      "type": "library",
      "name": "Azure.Core",
      "version": "1.25.0",
      "purl": "pkg:dotnet-core/Azure.Core@1.25.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Azure.Storage.Blobs@12.13.1",
      "type": "library",
      "name": "Azure.Storage.Blobs",
      "version": "12.13.1",
      "purl": "pkg:dotnet-core/Azure.Storage.Blobs@12.13.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Azure.Storage.Common@12.12.0",
      "type": "library",
      "name": "Azure.Storage.Common",
      "version": "12.12.0",
      "purl": "pkg:dotnet-core/Azure.Storage.Common@12.12.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Castle.Core@5.1.0",
      "type": "library",
      "name": "Castle.Core",
      "version": "5.1.0",
      "purl": "pkg:dotnet-core/Castle.Core@5.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/CsvHelper@28.0.1",
      "type": "library",
      "name": "CsvHelper",
      "version": "28.0.1",
      "purl": "pkg:dotnet-core/CsvHelper@28.0.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/DocumentFormat.OpenXml@2.18.0",
      "type": "library",
      "name": "DocumentFormat.OpenXml",
      "version": "2.18.0",
      "purl": "pkg:dotnet-core/DocumentFormat.OpenXml@2.18.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Google.Apis@1.57.0",
      "type": "library",
      "name": "Google.Apis",
      "version": "1.57.0",
      "purl": "pkg:dotnet-core/Google.Apis@1.57.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Google.Apis.Core@1.57.0",
      "type": "library",
      "name": "Google.Apis.Core",
      "version": "1.57.0",
      "purl": "pkg:dotnet-core/Google.Apis.Core@1.57.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Azure.Cosmos@3.30.1",
      "type": "library",
      "name": "Microsoft.Azure.Cosmos",
      "version": "3.30.1",
      "purl": "pkg:dotnet-core/Microsoft.Azure.Cosmos@3.30.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Bcl.AsyncInterfaces@1.1.1",
      "type": "library",
      "name": "Microsoft.Bcl.AsyncInterfaces",
      "version": "1.1.1",
      "purl": "pkg:dotnet-core/Microsoft.Bcl.AsyncInterfaces@1.1.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Bcl.HashCode@1.1.0",
      "type": "library",
      "name": "Microsoft.Bcl.HashCode",
      "version": "1.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Bcl.HashCode@1.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.Configuration@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.Configuration",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.Configuration@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.Configuration.Abstractions@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.Configuration.Abstractions",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.Configuration.Abstractions@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.Configuration.Binder@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.Configuration.Binder",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.Configuration.Binder@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.DependencyInjection@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.DependencyInjection",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.DependencyInjection@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.DependencyInjection.Abstractions@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.DependencyInjection.Abstractions",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.DependencyInjection.Abstractions@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.Logging@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.Logging",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.Logging@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.Logging.Abstractions@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.Logging.Abstractions",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.Logging.Abstractions@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.Logging.Configuration@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.Logging.Configuration",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.Logging.Configuration@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.Options@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.Options",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.Options@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.Options.ConfigurationExtensions@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.Options.ConfigurationExtensions",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.Options.ConfigurationExtensions@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Extensions.Primitives@3.1.0",
      "type": "library",
      "name": "Microsoft.Extensions.Primitives",
      "version": "3.1.0",
      "purl": "pkg:dotnet-core/Microsoft.Extensions.Primitives@3.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.OpenApi@1.2.3",
      "type": "library",
      "name": "Microsoft.OpenApi",
      "version": "1.2.3",
      "purl": "pkg:dotnet-core/Microsoft.OpenApi@1.2.3",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Microsoft.Win32.SystemEvents@6.0.0",
      "type": "library",
      "name": "Microsoft.Win32.SystemEvents",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/Microsoft.Win32.SystemEvents@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Moq@4.18.2",
      "type": "library",
      "name": "Moq",
      "version": "4.18.2",
      "purl": "pkg:dotnet-core/Moq@4.18.2",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Newtonsoft.Json@13.0.1",
      "type": "library",
      "name": "Newtonsoft.Json",
      "version": "13.0.1",
      "purl": "pkg:dotnet-core/Newtonsoft.Json@13.0.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/OpenTelemetry@1.3.1",
      "type": "library",
      "name": "OpenTelemetry",
      "version": "1.3.1",
      "purl": "pkg:dotnet-core/OpenTelemetry@1.3.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/OpenTelemetry.Api@1.3.1",
      "type": "library",
      "name": "OpenTelemetry.Api",
      "version": "1.3.1",
      "purl": "pkg:dotnet-core/OpenTelemetry.Api@1.3.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/SendGrid@9.28.1",
      "type": "library",
      "name": "SendGrid",
      "version": "9.28.1",
      "purl": "pkg:dotnet-core/SendGrid@9.28.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Serilog@2.10.0",
      "type": "library",
      "name": "Serilog",
      "version": "2.10.0",
      "purl": "pkg:dotnet-core/Serilog@2.10.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Serilog.Sinks.Console@4.1.0",
      "type": "library",
      "name": "Serilog.Sinks.Console",
      "version": "4.1.0",
      "purl": "pkg:dotnet-core/Serilog.Sinks.Console@4.1.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/Swashbuckle.AspNetCore.Swagger@6.4.0",
      "type": "library",
      "name": "Swashbuckle.AspNetCore.Swagger",
      "version": "6.4.0",
      "purl": "pkg:dotnet-core/Swashbuckle.AspNetCore.Swagger@6.4.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Buffers@4.5.1",
      "type": "library",
      "name": "System.Buffers",
      "version": "4.5.1",
      "purl": "pkg:dotnet-core/System.Buffers@4.5.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Collections.Immutable@1.7.0",
      "type": "library",
      "name": "System.Collections.Immutable",
      "version": "1.7.0",
      "purl": "pkg:dotnet-core/System.Collections.Immutable@1.7.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Configuration.ConfigurationManager@6.0.0",
      "type": "library",
      "name": "System.Configuration.ConfigurationManager",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.Configuration.ConfigurationManager@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Diagnostics.DiagnosticSource@6.0.0",
      "type": "library",
      "name": "System.Diagnostics.DiagnosticSource",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.Diagnostics.DiagnosticSource@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Diagnostics.EventLog@6.0.0",
      "type": "library",
      "name": "System.Diagnostics.EventLog",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.Diagnostics.EventLog@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Drawing.Common@6.0.0",
      "type": "library",
      "name": "System.Drawing.Common",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.Drawing.Common@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.IO.Hashing@6.0.0",
      "type": "library",
      "name": "System.IO.Hashing",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.IO.Hashing@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.IO.Packaging@4.7.0",
      "type": "library",
      "name": "System.IO.Packaging",
      "version": "4.7.0",
      "purl": "pkg:dotnet-core/System.IO.Packaging@4.7.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Memory@4.5.4",
      "type": "library",
      "name": "System.Memory",
      "version": "4.5.4",
      "purl": "pkg:dotnet-core/System.Memory@4.5.4",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Memory.Data@1.0.2",
      "type": "library",
      "name": "System.Memory.Data",
      "version": "1.0.2",
      "purl": "pkg:dotnet-core/System.Memory.Data@1.0.2",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Numerics.Vectors@4.5.0",
      "type": "library",
      "name": "System.Numerics.Vectors",
      "version": "4.5.0",
      "purl": "pkg:dotnet-core/System.Numerics.Vectors@4.5.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Reflection.Emit.Lightweight@4.7.0",
      "type": "library",
      "name": "System.Reflection.Emit.Lightweight",
      "version": "4.7.0",
      "purl": "pkg:dotnet-core/System.Reflection.Emit.Lightweight@4.7.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Runtime.CompilerServices.Unsafe@6.0.0",
      "type": "library",
      "name": "System.Runtime.CompilerServices.Unsafe",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.Runtime.CompilerServices.Unsafe@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Security.AccessControl@6.0.0",
      "type": "library",
      "name": "System.Security.AccessControl",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.Security.AccessControl@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Security.Cryptography.ProtectedData@6.0.0",
      "type": "library",
      "name": "System.Security.Cryptography.ProtectedData",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.Security.Cryptography.ProtectedData@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Security.Permissions@6.0.0",
      "type": "library",
      "name": "System.Security.Permissions",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.Security.Permissions@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Text.Encodings.Web@4.7.2",
      "type": "library",
      "name": "System.Text.Encodings.Web",
      "version": "4.7.2",
      "purl": "pkg:dotnet-core/System.Text.Encodings.Web@4.7.2",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Text.Json@4.7.2",
      "type": "library",
      "name": "System.Text.Json",
      "version": "4.7.2",
      "purl": "pkg:dotnet-core/System.Text.Json@4.7.2",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Threading.Tasks.Extensions@4.5.4",
      "type": "library",
      "name": "System.Threading.Tasks.Extensions",
      "version": "4.5.4",
      "purl": "pkg:dotnet-core/System.Threading.Tasks.Extensions@4.5.4",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.ValueTuple@4.5.0",
      "type": "library",
      "name": "System.ValueTuple",
      "version": "4.5.0",
      "purl": "pkg:dotnet-core/System.ValueTuple@4.5.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/System.Windows.Extensions@6.0.0",
      "type": "library",
      "name": "System.Windows.Extensions",
      "version": "6.0.0",
      "purl": "pkg:dotnet-core/System.Windows.Extensions@6.0.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/bootstrap@5.2.0",
      "type": "library",
      "name": "bootstrap",
      "version": "5.2.0",
      "purl": "pkg:dotnet-core/bootstrap@5.2.0",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "pkg:dotnet-core/starkbank-ecdsa@1.3.3",
      "type": "library",
      "name": "starkbank-ecdsa",
      "version": "1.3.3",
      "purl": "pkg:dotnet-core/starkbank-ecdsa@1.3.3",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "56c19f3f-6b1c-4c4c-a008-71c038875ce5",
      "type": "application",
      "name": "TrivyTest/bin/Debug/net6.0/TrivyTest.deps.json",
      "properties": [
        {
          "name": "aquasecurity:trivy:Type",
          "value": "dotnet-core"
        },
        {
          "name": "aquasecurity:trivy:Class",
          "value": "lang-pkgs"
        }
      ]
    }
  ],
  "dependencies": [
    {
      "ref": "56c19f3f-6b1c-4c4c-a008-71c038875ce5",
      "dependsOn": [
        "pkg:dotnet-core/Azure.Core@1.25.0",
        "pkg:dotnet-core/Azure.Storage.Blobs@12.13.1",
        "pkg:dotnet-core/Azure.Storage.Common@12.12.0",
        "pkg:dotnet-core/Castle.Core@5.1.0",
        "pkg:dotnet-core/CsvHelper@28.0.1",
        "pkg:dotnet-core/DocumentFormat.OpenXml@2.18.0",
        "pkg:dotnet-core/Google.Apis@1.57.0",
        "pkg:dotnet-core/Google.Apis.Core@1.57.0",
        "pkg:dotnet-core/Microsoft.Azure.Cosmos@3.30.1",
        "pkg:dotnet-core/Microsoft.Bcl.AsyncInterfaces@1.1.1",
        "pkg:dotnet-core/Microsoft.Bcl.HashCode@1.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.Configuration@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.Configuration.Abstractions@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.Configuration.Binder@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.DependencyInjection@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.DependencyInjection.Abstractions@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.Logging@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.Logging.Abstractions@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.Logging.Configuration@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.Options@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.Options.ConfigurationExtensions@3.1.0",
        "pkg:dotnet-core/Microsoft.Extensions.Primitives@3.1.0",
        "pkg:dotnet-core/Microsoft.OpenApi@1.2.3",
        "pkg:dotnet-core/Microsoft.Win32.SystemEvents@6.0.0",
        "pkg:dotnet-core/Moq@4.18.2",
        "pkg:dotnet-core/Newtonsoft.Json@13.0.1",
        "pkg:dotnet-core/OpenTelemetry@1.3.1",
        "pkg:dotnet-core/OpenTelemetry.Api@1.3.1",
        "pkg:dotnet-core/SendGrid@9.28.1",
        "pkg:dotnet-core/Serilog@2.10.0",
        "pkg:dotnet-core/Serilog.Sinks.Console@4.1.0",
        "pkg:dotnet-core/Swashbuckle.AspNetCore.Swagger@6.4.0",
        "pkg:dotnet-core/System.Buffers@4.5.1",
        "pkg:dotnet-core/System.Collections.Immutable@1.7.0",
        "pkg:dotnet-core/System.Configuration.ConfigurationManager@6.0.0",
        "pkg:dotnet-core/System.Diagnostics.DiagnosticSource@6.0.0",
        "pkg:dotnet-core/System.Diagnostics.EventLog@6.0.0",
        "pkg:dotnet-core/System.Drawing.Common@6.0.0",
        "pkg:dotnet-core/System.IO.Hashing@6.0.0",
        "pkg:dotnet-core/System.IO.Packaging@4.7.0",
        "pkg:dotnet-core/System.Memory@4.5.4",
        "pkg:dotnet-core/System.Memory.Data@1.0.2",
        "pkg:dotnet-core/System.Numerics.Vectors@4.5.0",
        "pkg:dotnet-core/System.Reflection.Emit.Lightweight@4.7.0",
        "pkg:dotnet-core/System.Runtime.CompilerServices.Unsafe@6.0.0",
        "pkg:dotnet-core/System.Security.AccessControl@6.0.0",
        "pkg:dotnet-core/System.Security.Cryptography.ProtectedData@6.0.0",
        "pkg:dotnet-core/System.Security.Permissions@6.0.0",
        "pkg:dotnet-core/System.Text.Encodings.Web@4.7.2",
        "pkg:dotnet-core/System.Text.Json@4.7.2",
        "pkg:dotnet-core/System.Threading.Tasks.Extensions@4.5.4",
        "pkg:dotnet-core/System.ValueTuple@4.5.0",
        "pkg:dotnet-core/System.Windows.Extensions@6.0.0",
        "pkg:dotnet-core/bootstrap@5.2.0",
        "pkg:dotnet-core/starkbank-ecdsa@1.3.3"
      ]
    },
    {
      "ref": "3a07a467-bf3d-4cd9-b10a-66b7ea4d3757",
      "dependsOn": [
        "56c19f3f-6b1c-4c4c-a008-71c038875ce5"
      ]
    }
  ],
  "vulnerabilities": []
}
```

## Output of `trivy -v`:

Version: 0.31.2

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
use [nuget](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#nuget) purl type for `dotnet-core`

Before:
```zsh
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:fa54af43-7447-4a82-af53-b9f2e4130097",
  "version": 1,
  "metadata": {
    "timestamp": "2022-10-03T06:51:30+00:00",
    "tools": [
      {
        "vendor": "aquasecurity",
        "name": "trivy",
        "version": "0.32.1"
      }
    ],
    "component": {
      "bom-ref": "b41bce6c-bb5e-4429-ad43-7db3522c0219",
      "type": "application",
      "name": "datacollector.deps.json",
      "properties": [
        {
          "name": "aquasecurity:trivy:SchemaVersion",
          "value": "2"
        }
      ]
    }
  },
  "components": [
    {
      "bom-ref": "pkg:dotnet-core/Newtonsoft.Json@9.0.1",
      "type": "library",
      "name": "Newtonsoft.Json",
      "version": "9.0.1",
      "purl": "pkg:dotnet-core/Newtonsoft.Json@9.0.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "7c2c5f96-f93a-4f14-be8b-328cc416fc1e",
      "type": "application",
      "name": "datacollector.deps.json",
      "properties": [
        {
          "name": "aquasecurity:trivy:Type",
          "value": "dotnet-core"
        },
        {
          "name": "aquasecurity:trivy:Class",
          "value": "lang-pkgs"
        }
      ]
    }
  ],
  "dependencies": [
    {
      "ref": "7c2c5f96-f93a-4f14-be8b-328cc416fc1e",
      "dependsOn": [
        "pkg:dotnet-core/Newtonsoft.Json@9.0.1"
      ]
    },
    {
      "ref": "b41bce6c-bb5e-4429-ad43-7db3522c0219",
      "dependsOn": [
        "7c2c5f96-f93a-4f14-be8b-328cc416fc1e"
      ]
    }
  ],
  "vulnerabilities": []
}

```

After:
```zsh
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:962826f6-cd5b-409f-95b0-ab7469aeb24b",
  "version": 1,
  "metadata": {
    "timestamp": "2022-10-03T07:12:14+00:00",
    "tools": [
      {
        "vendor": "aquasecurity",
        "name": "trivy",
        "version": "0.32.0-1-g3233dbd0"
      }
    ],
    "component": {
      "bom-ref": "54aafb2e-9042-4a28-b07c-09148179dfb1",
      "type": "application",
      "name": "datacollector.deps.json",
      "properties": [
        {
          "name": "aquasecurity:trivy:SchemaVersion",
          "value": "2"
        }
      ]
    }
  },
  "components": [
    {
      "bom-ref": "pkg:nuget/Newtonsoft.Json@9.0.1",
      "type": "library",
      "name": "Newtonsoft.Json",
      "version": "9.0.1",
      "purl": "pkg:nuget/Newtonsoft.Json@9.0.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "dotnet-core"
        }
      ]
    },
    {
      "bom-ref": "5327f4f7-0954-4559-9a1e-13dd9da0a939",
      "type": "application",
      "name": "datacollector.deps.json",
      "properties": [
        {
          "name": "aquasecurity:trivy:Type",
          "value": "dotnet-core"
        },
        {
          "name": "aquasecurity:trivy:Class",
          "value": "lang-pkgs"
        }
      ]
    }
  ],
  "dependencies": [
    {
      "ref": "5327f4f7-0954-4559-9a1e-13dd9da0a939",
      "dependsOn": [
        "pkg:nuget/Newtonsoft.Json@9.0.1"
      ]
    },
    {
      "ref": "54aafb2e-9042-4a28-b07c-09148179dfb1",
      "dependsOn": [
        "5327f4f7-0954-4559-9a1e-13dd9da0a939"
      ]
    }
  ],
  "vulnerabilities": []
}
 
```

## Related issues
- Close #2842

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/purl/purl.go [hunk 1]
```diff
@@ -290,6 +290,8 @@ func purlType(t string) string {
 		return packageurl.TypeMaven
 	case string(analyzer.TypeBundler), string(analyzer.TypeGemSpec):
 		return packageurl.TypeGem
+	case string(analyzer.TypeNuget), string(ftypes.DotNetCore):
```
Comment (knqyf263) [inline pkg/purl/purl.go:293]: It should be `TypeDotNetDeps`, no?

```suggestion
	case string(analyzer.TypeNuget), string(analyzer. TypeDotNetDeps):
```

Comment (knqyf263) [reply pkg/purl/purl.go:293]: Also, I think we need to add `TypeNuget` here.
https://github.com/aquasecurity/trivy/blob/4c32b47548441dd31beba8a3e91871fd94a0ec09/pkg/purl/purl.go#L80-L98

Comment (DmitriyLewen) [reply pkg/purl/purl.go]: Done

**Review by knqyf263 — APPROVED** [review]
