### PR TITLE
fix(python): add `poetry` v2 support

### LINKED ISSUE #8322: bug(python): add support for poetry 2.0.0
## Description
Poetry changed the logic for placing dependencies in `pyproject.toml` file since version 2.0.0 - https://python-poetry.org/docs/dependency-specification/

So we need to add support for `project.dependencies` field in new `pyproject.toml` files to:
- fix panic when `tool` does not exist (see #8321)
- properly specify direct/dev/etc dependencies.

### Discussed in https://github.com/aquasecurity/trivy/discussions/8321

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Changes:
- fix panic when `pyproject.toml` file doesn't contain `tool` field.
- parse `project.dependencies` array to get main deps.
- don't skip packages with `category: "dev"` (`parser` package)
- use `package.group` field to detect Dev deps (for poetry v2)

## Related issues
- Close #8322

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/dependency/parser/python/poetry/parse.go [hunk 1]
```diff
@@ -50,15 +52,16 @@ func (p *Parser) Parse(r xio.ReadSeekerAt) ([]ftypes.Package, []ftypes.Dependenc
...
 		pkgID := packageID(pkg.Name, pkg.Version)
 		pkgs = append(pkgs, ftypes.Package{
 			ID:      pkgID,
 			Name:    pkg.Name,
 			Version: pkg.Version,
+			// TODO upgrade logic for working with groups
+			// Mark only:
+			// - `category = "dev"`
+			// - groups without `main`. e.g. `groups = ["dev"]`
+			Dev: pkg.Category == "dev" || (len(pkg.Groups) > 0 && !slices.Contains(pkg.Groups, "main")),
```
Comment (nikpivkin) [inline pkg/dependency/parser/python/poetry/parse.go:64]: Checking the number of groups is not necessary, is it?
```suggestion
			Dev: pkg.Category == "dev" || !slices.Contains(pkg.Groups, "main"),
```

File: pkg/dependency/parser/python/pyproject/pyproject.go [hunk 2]
```diff
@@ -32,15 +38,41 @@ type Dependencies struct {
...
+	case []any: // For Poetry v2
+		d.Set = set.New[string]()
+		for i := range deps {
+			dep, ok := deps[i].(string)
+			if !ok {
+				return xerrors.Errorf("dependencies must be string, but got: %T", deps[i])
+			}
+			// There are some formats:
+			// e.g. `Flask == 1.1.4`, `Flask==1.1.4`, `Flask (>= 1.0.0)`, `Flask(>= 1.0.0)`, etc.
+			dep = strings.NewReplacer(">", " ", "<", " ", "=", " ", "(", " ").Replace(dep)
```
Comment (nikpivkin) [inline pkg/dependency/parser/python/pyproject/pyproject.go:69]: It may be necessary to add processing for one more case. The package can be installed with optional dependencies. For example:
```bash
poetry add django -E bcrypt,argon2
```

Then ``pyptoject.toml`` will contain the following dependency:
```
dependencies = [
    “django[bcrypt,argon2] (>=5.1.5,<6.0.0)”,
]
```

So django is marked as dev, since `poetry.lock` specifies the dependency without extra packages:
```
[[package]]
name = “django”
```

File: pkg/dependency/parser/python/poetry/parse.go (hunk 1 above)
Comment (DmitriyLewen) [reply pkg/dependency/parser/python/poetry/parse.go:64]: I forgot to remove that after changing logic for groups. Thanks!

File: pkg/dependency/parser/python/pyproject/pyproject.go (hunk 2 above)
Comment (DmitriyLewen) [reply pkg/dependency/parser/python/pyproject/pyproject.go]: nice catch!

Added `[` in https://github.com/aquasecurity/trivy/pull/8323/commits/dbaf2c83b1e059a9ad4b47e9e8061111fb0cef00

File: pkg/dependency/parser/python/poetry/parse.go (hunk 1 above)
Comment (DmitriyLewen) [reply pkg/dependency/parser/python/poetry/parse.go:64]: It wasn't a mistake after all.
I remembered why I didn't remove that check:
it needs to check that `poetry.lock` uses groups instead of `category`.

Without that check, we'd mark all dependencies as `Dev` for `poetry.lock` with `category`:
https://github.com/aquasecurity/trivy/actions/runs/13107249603

**Review by nikpivkin — APPROVED** [review]

**Comment by DmitriyLewen** [comment]
@aqua-bot backport release/v0.59
