### PR TITLE
fix(vuln): skip vulns detection for CentOS Stream family without scan failure

### LINKED ISSUE #9898: bug(os): Trivy detects CentOS Stream as CentOS
## Description
Trivy checks CentOS version from two files:
- etc/centos-release file
- etc/os-release

Trivy doesn't detect OS from `centos-release` file.
But CentOS Stream uses `CentOS` ID in `os-release` file:
```
bash-5.1# cat /etc/centos-release 
CentOS Stream release 9
bash-5.1# cat etc/os-release 
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
...
```
That is why Trivy detects CentOS Stream as CentOS.

## Solutions
- check version: if version <= 8 - CentOS, of version >= 9 - CentOS Stream (8 is latest CentOS version - https://www.redhat.com/en/topics/linux/centos-linux-eol#why-is-it-going-away) 
- check `NAME` field from `/etc/os-release`. 
We will able to detect CentOS Stream and simply report that it’s an unsupported OS for vulnerability detection (the same way we do for Fedora).

- Alternative way - RedHat and CentOS team stop support CentOS OSes - https://www.redhat.com/en/topics/linux/centos-linux-eol#why-is-it-going-away. So we can don't worry that `centos-release` file will be removed/updated and scan only this file and don't detect CentOS from os-release file
	✅ Pros:
	    - Simple to implement
	❌ Cons:
	    - CentOS Stream will not be detected at all

### Discussed in https://github.com/aquasecurity/trivy/discussions/9894

### PR DESCRIPTION
**Pull request by amitverse**
## Description
Trivy doesn't support `CentOS Stream` OS. And when it scan such OS, it fails to detect vulnerabilities and throws a fatal error- `Fatal error   run error: image scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: unable to scan OS packages`

Ideally the scan shouldn't fail and it should skip the vulns detection.

## Fix
This PR addresses the fix for the above mentioned issue.
With this changes, the field `Name` will have higher precedence than `ID` for deciding `OS family`.
If the `OS family` belongs to `CentOS Stream`, it will skip vulns detection without failing scan and with a warning-
WARN	Unsupported os	family="CentOS Stream" 

## Related issues
- Close #9898 

## Validation
1.  image: quay.io/centos/centos:stream10
```bash
➜ ./trivy image quay.io/centos/centos:stream10 --scanners vuln
2025-12-29T13:18:02+06:00       INFO    [vuln] Vulnerability scanning is enabled
2025-12-29T13:18:37+06:00       INFO    [python] Licenses acquired from one or more METADATA files may be subject to additional terms. Use `--debug` flag to see all affected packages.
2025-12-29T13:18:38+06:00       INFO    Detected OS     family="centos-stream" version="10"
2025-12-29T13:18:38+06:00       WARN    Unsupported os  family="centos-stream"
2025-12-29T13:18:38+06:00       INFO    Number of language-specific files       num=0
2025-12-29T13:18:38+06:00       WARN    [report] Supported files for scanner(s) not found.      scanners=[vuln]

Report Summary

┌────────┬──────┬─────────────────┐
│ Target │ Type │ Vulnerabilities │
├────────┼──────┼─────────────────┤
│   -    │  -   │        -        │
└────────┴──────┴─────────────────┘
```
2.  image: quay.io/centos/centos:stream8
```bash
➜ ./trivy image quay.io/centos/centos:stream8 --scanners vuln
2025-12-29T13:16:28+06:00       INFO    [vuln] Vulnerability scanning is enabled
2025-12-29T13:16:50+06:00       INFO    [python] Licenses acquired from one or more METADATA files may be subject to additional terms. Use `--debug` flag to see all affected packages.
2025-12-29T13:16:50+06:00       INFO    Detected OS     family="centos-stream" version="8"
2025-12-29T13:16:50+06:00       WARN    Unsupported os  family="centos-stream"
2025-12-29T13:16:50+06:00       INFO    Number of language-specific files       num=0
2025-12-29T13:16:50+06:00       WARN    [report] Supported files for scanner(s) not found.      scanners=[vuln]

Report Summary

┌────────┬──────┬─────────────────┐
│ Target │ Type │ Vulnerabilities │
├────────┼──────┼─────────────────┤
│   -    │  -   │        -        │
└────────┴──────┴─────────────────┘
```

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/docs/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/docs/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/analyzer/os/release/release.go [hunk 1]
```diff
@@ -40,9 +40,18 @@ func (a osReleaseAnalyzer) Analyze(_ context.Context, input analyzer.AnalysisInp
 		key, value := strings.TrimSpace(ss[0]), strings.TrimSpace(ss[1])
 
 		switch key {
+		case "NAME":
+			osName := strings.Trim(value, `"'`)
+			osFamily := nameToOSFamily(osName)
```
Comment (DmitriyLewen) [inline pkg/fanal/analyzer/os/release/release.go]: I don’t think we need two sources for osFamily.
This can easily introduce confusion when maintaining the code and when adding support for new operating systems.

I suggest keeping id as the primary source, and using name only for normalization (post-processing).
This way it’s clear that:
	•	we always rely on id, and
	•	we fall back to name only in exceptional cases, when id doesn’t provide a reliable value.

I’ve put together a small example to illustrate my thinking:
```diff
diff --git a/pkg/fanal/analyzer/os/release/release.go b/pkg/fanal/analyzer/os/release/release.go
index 24aa1b744..1c99ea7ee 100644
--- a/pkg/fanal/analyzer/os/release/release.go
+++ b/pkg/fanal/analyzer/os/release/release.go
@@ -27,8 +27,7 @@ var requiredFiles = []string{
 type osReleaseAnalyzer struct{}
 
 func (a osReleaseAnalyzer) Analyze(_ context.Context, input analyzer.AnalysisInput) (*analyzer.AnalysisResult, error) {
-	var family types.OSType
-	var versionID string
+	var id, osName, versionID string
 	scanner := bufio.NewScanner(input.Content)
 	for scanner.Scan() {
 		line := scanner.Text()
@@ -40,35 +39,32 @@ func (a osReleaseAnalyzer) Analyze(_ context.Context, input analyzer.AnalysisInp
 		key, value := strings.TrimSpace(ss[0]), strings.TrimSpace(ss[1])
 
 		switch key {
-		case "NAME":
-			osName := strings.Trim(value, `"'`)
-			osFamily := nameToOSFamily(osName)
-			if osFamily != "" {
-				family = osFamily
-			}
 		case "ID":
-			id := strings.Trim(value, `"'`)
-			// Only set from ID if family not already set from NAME
-			if family == "" {
-				family = idToOSFamily(id)
-			}
+			id = strings.Trim(value, `"'`)
+		case "NAME":
+			osName = strings.Trim(value, `"'`)
 		case "VERSION_ID":
 			versionID = strings.Trim(value, `"'`)
 		default:
 			continue
 		}
+	}
 
-		if family != "" && versionID != "" {
-			return &analyzer.AnalysisResult{
-				OS: types.OS{
-					Family: family,
-					Name:   versionID,
-				},
-			}, nil
-		}
+	// Determine OS family: ID is the primary source
+	family := idToOSFamily(id)
+	if family == "" || versionID == "" {
+		return nil, nil
 	}
 
-	return nil, nil
+	// Refine OS family based on NAME field
+	family = refineOSFamily(family, osName)
+
+	return &analyzer.AnalysisResult{
+		OS: types.OS{
+			Family: family,
+			Name:   versionID,
+		},
+	}, nil
 }
 
 //nolint:gocyclo
@@ -122,14 +118,18 @@ func idToOSFamily(id string) types.OSType {
 	return ""
 }
 
-// nameToOSFamily detects OS family from the NAME field.
-// This handles cases where NAME explicitly indicates a specific OS variant.
-func nameToOSFamily(name string) types.OSType {
-	switch name {
-	case "CentOS Stream":
+// refineOSFamily refines the OS family based on the NAME field.
+// This handles exceptional cases where the ID field doesn't provide enough specificity,
+// and we need to refine the detection using the NAME field.
+func refineOSFamily(family types.OSType, name string) types.OSType {
+	// CentOS: Distinguish between regular CentOS and CentOS Stream
+	// ID is "centos" for both, but NAME differs
+	if family == types.CentOS && name == "CentOS Stream" {
 		return types.CentOSStream
 	}
-	return ""
+
+	// Return family unchanged for normal cases
+	return family
 }
 
 func (a osReleaseAnalyzer) Required(filePath string, _ os.FileInfo) bool {

```

**Comment by amitverse** [comment]
hii @DmitriyLewen, thanks for the review.
 i have resolved the review-comment. also, added the testcase for centos-stream. please review when you have a chance.

**Review by DmitriyLewen — APPROVED** [review]
Thanks for contribution!
