### PR TITLE
fix(purl): skip unsupported library type

### LINKED ISSUE #3994: SBOM scan: unsupported type github
## Description

I am scanning a CycloneDX SBOM that contains a component with a Github package URL.
Trivy exits with an error (`unsupported type github`).

## What did you expect to happen?
I was hoping that a vulnerability scan is possible, considering that[ GitHub advisory databases are a supported data source](https://aquasecurity.github.io/trivy/v0.39/docs/vulnerability/detection/data-source/).

## What happened instead?
```
2023-04-05T15:58:11.178+0200	FATAL	sbom scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: failed to scan application libraries: failed vulnerability detection of libraries: failed to initialize a driver: unsupported type github
```

## Output of run with `-debug`:

```
$ trivy  --debug sbom test_sbom.json 
2023-04-05T16:02:49.726+0200	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-04-05T16:02:49.729+0200	DEBUG	cache dir:  /home/user/.cache/trivy
2023-04-05T16:02:49.729+0200	DEBUG	DB update was skipped because the local DB is the latest
2023-04-05T16:02:49.729+0200	DEBUG	DB Schema: 2, UpdatedAt: 2023-04-05 12:08:03.416475873 +0000 UTC, NextUpdate: 2023-04-05 18:08:03.416475473 +0000 UTC, DownloadedAt: 2023-04-05 13:58:11.168521624 +0000 UTC
2023-04-05T16:02:49.729+0200	INFO	Vulnerability scanning is enabled
2023-04-05T16:02:49.730+0200	DEBUG	Vulnerability type:  [os library]
2023-04-05T16:02:49.730+0200	INFO	Detected SBOM format: cyclonedx-json
2023-04-05T16:02:49.730+0200	DEBUG	Unmarshaling CycloneDX JSON...
2023-04-05T16:02:49.731+0200	WARN	Third-party SBOM may lead to inaccurate vulnerability detection
2023-04-05T16:02:49.731+0200	WARN	Recommend using Trivy to generate SBOMs
2023-04-05T16:02:49.731+0200	WARN	Ignore the OS package as no OS information is found.
2023-04-05T16:02:49.733+0200	DEBUG	OS is not detected.
2023-04-05T16:02:49.733+0200	DEBUG	Detected OS: unknown
2023-04-05T16:02:49.733+0200	INFO	Number of language-specific files: 1
2023-04-05T16:02:49.733+0200	INFO	Detecting github vulnerabilities...
2023-04-05T16:02:49.733+0200	DEBUG	Detecting library vulnerabilities, type: github, path: 
2023-04-05T16:02:49.737+0200	FATAL	sbom scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:413
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:257
  - scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:588
  - scan failed:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:156
  - failed to detect vulnerabilities:
    github.com/aquasecurity/trivy/pkg/scanner/local.Scanner.Scan
        /home/runner/work/trivy/trivy/pkg/scanner/local/scan.go:120
  - failed to scan application libraries:
    github.com/aquasecurity/trivy/pkg/scanner/local.Scanner.scanVulnerabilities
        /home/runner/work/trivy/trivy/pkg/scanner/local/scan.go:231
  - failed vulnerability detection of libraries:
    github.com/aquasecurity/trivy/pkg/scanner/local.Scanner.scanLangPkgs
        /home/runner/work/trivy/trivy/pkg/scanner/local/scan.go:296
  - failed to initialize a driver:
    github.com/aquasecurity/trivy/pkg/detector/library.Detect
        /home/runner/work/trivy/trivy/pkg/detector/library/detect.go:19
  - unsupported type github:
    github.com/aquasecurity/trivy/pkg/detector/library.NewDriver
        /home/runner/work/trivy/trivy/pkg/detector/library/driver.go:66
```

## Output of `trivy -v`:

```
$ trivy  -v sbom test_sbom.json 
2023-04-05T16:06:36.211+0200	INFO	Vulnerability scanning is enabled
2023-04-05T16:06:36.211+0200	INFO	Detected SBOM format: cyclonedx-json
2023-04-05T16:06:36.211+0200	WARN	Third-party SBOM may lead to inaccurate vulnerability detection
2023-04-05T16:06:36.211+0200	WARN	Recommend using Trivy to generate SBOMs
2023-04-05T16:06:36.211+0200	WARN	Ignore the OS package as no OS information is found.
2023-04-05T16:06:36.213+0200	INFO	Number of language-specific files: 1
2023-04-05T16:06:36.213+0200	INFO	Detecting github vulnerabilities...
2023-04-05T16:06:36.214+0200	FATAL	sbom scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: failed to scan application libraries: failed vulnerability detection of libraries: failed to initialize a driver: unsupported type github
```

## Additional details (base image name, container registry info...):
Trivy version:
```
Version: 0.36.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-04-05 12:08:03.416475873 +0000 UTC
  NextUpdate: 2023-04-05 18:08:03.416475473 +0000 UTC
  DownloadedAt: 2023-04-05 13:58:11.168521624 +0000 UTC
```

Minimal SBOM input file triggering the error:
```
{"bomFormat":"CycloneDX","specVersion":"1.4","version":1,"metadata":{"timestamp":"2023-04-05T08:55:01.123Z","component":{"type":"application","name":"test","version":"1","bom-ref":"test-app"}},"components":[{"type":"library","name":"pcre2","version":"10.42","purl":"pkg:github/PCRE2Project/pcre2@10.42","bom-ref":"pcre2"}],"dependencies":[{"ref":"test-app","dependsOn":["pcre2"]}]}
```

### LINKED ISSUE #4566: Trivy 0.42.0 crashes with "unsupported type bitnami" message
### Discussed in https://github.com/aquasecurity/trivy/discussions/4562

<div type='discussions-op-text'>

<sup>Originally posted by **elchenberg** June  5, 2023</sup>
### Description

Trivy 0.42.0 crashes with "unsupported type bitnami" message when scanning the image docker.io/bitnami/rabbitmq:3.11.17-debian-11-r2.

### Desired Behavior

No crash.

### Actual Behavior

Crash.

### Reproduction Steps

```bash
$ trivy version | head -n1
Version: 0.42.0

$ trivy image docker.io/bitnami/rabbitmq:3.11.17-debian-11-r2
2023-06-05T12:16:17.383+0200	INFO	Vulnerability scanning is enabled
2023-06-05T12:16:17.383+0200	INFO	Secret scanning is enabled
2023-06-05T12:16:17.383+0200	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-06-05T12:16:17.383+0200	INFO	Please see also https://aquasecurity.github.io/trivy/v0.42/docs/secret/scanning/#recommendation for faster secret detection
2023-06-05T12:16:18.775+0200	INFO	Detected OS: debian
2023-06-05T12:16:18.775+0200	INFO	Detecting Debian vulnerabilities...
2023-06-05T12:16:18.800+0200	INFO	Number of language-specific files: 1
2023-06-05T12:16:18.800+0200	INFO	Detecting bitnami vulnerabilities...
2023-06-05T12:16:18.800+0200	FATAL	image scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: failed to scan application libraries: failed vulnerability detection of libraries: failed to initialize a driver: unsupported type bitnami
```
```


### Target

Container Image

### Scanner

None

### Output Format

None

### Mode

Standalone

### Debug Output

```bash
$ trivy image docker.io/bitnami/rabbitmq:3.11.17-debian-11-r2 --debug
2023-06-05T12:28:39.197+0200	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-06-05T12:28:39.208+0200	DEBUG	cache dir:  /home/$USERNAME/.cache/trivy
2023-06-05T12:28:39.208+0200	DEBUG	There is no valid metadata file: unable to open a file: open /home/helgeeichelberg/.cache/trivy/db/metadata.json: no such file or directory
2023-06-05T12:28:39.208+0200	INFO	Need to update DB
2023-06-05T12:28:39.208+0200	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-06-05T12:28:39.208+0200	INFO	Downloading DB...
2023-06-05T12:28:39.208+0200	DEBUG	no metadata file
37.36 MiB / 37.36 MiB [-------------------------------------------------------------------------------------] 100.00% 5.65 MiB p/s 6.8s
2023-06-05T12:28:46.907+0200	DEBUG	Updating database metadata...
2023-06-05T12:28:46.907+0200	DEBUG	DB Schema: 2, UpdatedAt: 2023-06-05 06:08:14.618801312 +0000 UTC, NextUpdate: 2023-06-05 12:08:14.618800712 +0000 UTC, DownloadedAt: 2023-06-05 10:28:46.907497592 +0000 UTC
2023-06-05T12:28:46.907+0200	INFO	Vulnerability scanning is enabled
2023-06-05T12:28:46.907+0200	DEBUG	Vulnerability type:  [os library]
2023-06-05T12:28:46.907+0200	INFO	Secret scanning is enabled
2023-06-05T12:28:46.907+0200	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-06-05T12:28:46.907+0200	INFO	Please see also https://aquasecurity.github.io/trivy/v0.42/docs/secret/scanning/#recommendation for faster secret detection
2023-06-05T12:28:48.036+0200	DEBUG	No secret config detected: trivy-secret.yaml
2023-06-05T12:28:48.333+0200	DEBUG	Image ID: sha256:11bd5852655ef13a59af279e1574e5a57f9d76b72eab270581f755a55d095fd5
2023-06-05T12:28:48.333+0200	DEBUG	Diff IDs: [sha256:c38d7c6f14f7ac58167166952d65facfa188098f77173c54febef4c4aae32e36]
2023-06-05T12:28:48.333+0200	DEBUG	Base Layers: []
2023-06-05T12:28:48.333+0200	DEBUG	Missing image ID in cache: sha256:11bd5852655ef13a59af279e1574e5a57f9d76b72eab270581f755a55d095fd5
2023-06-05T12:28:48.333+0200	DEBUG	Missing diff ID in cache: sha256:c38d7c6f14f7ac58167166952d65facfa188098f77173c54febef4c4aae32e36
2023-06-05T12:28:50.177+0200	DEBUG	Analysis error: SBOM decode error: failed to decode: failed to unmarshal spdx: failed to parse package: external references error: failed to parse purl from string: failed to parse purl(purl:bitnami/erlang@25.3.2): scheme is missing
2023-06-05T12:28:59.915+0200	DEBUG	Skipping directory: sys
2023-06-05T12:28:59.915+0200	DEBUG	Skipping directory: dev
2023-06-05T12:29:02.987+0200	DEBUG	Skipping directory: proc
2023-06-05T12:29:03.161+0200	DEBUG	No secrets found in container image config
2023-06-05T12:29:03.167+0200	INFO	Detected OS: debian
2023-06-05T12:29:03.167+0200	INFO	Detecting Debian vulnerabilities...
2023-06-05T12:29:03.167+0200	DEBUG	debian: os version: 11
2023-06-05T12:29:03.167+0200	DEBUG	debian: the number of packages: 111
2023-06-05T12:29:03.193+0200	INFO	Number of language-specific files: 1
2023-06-05T12:29:03.193+0200	INFO	Detecting bitnami vulnerabilities...
2023-06-05T12:29:03.193+0200	DEBUG	Detecting library vulnerabilities, type: bitnami, path: opt/bitnami/rabbitmq/bin/rabbitmq
2023-06-05T12:29:03.194+0200	FATAL	image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:426
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:268
  - scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:683
  - scan failed:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:154
  - failed to detect vulnerabilities:
    github.com/aquasecurity/trivy/pkg/scanner/local.Scanner.Scan
        /home/runner/work/trivy/trivy/pkg/scanner/local/scan.go:102
  - failed to scan application libraries:
    github.com/aquasecurity/trivy/pkg/scanner/local.Scanner.scanVulnerabilities
        /home/runner/work/trivy/trivy/pkg/scanner/local/scan.go:189
  - failed vulnerability detection of libraries:
    github.com/aquasecurity/trivy/pkg/scanner/langpkg.(*scanner).Scan
        /home/runner/work/trivy/trivy/pkg/scanner/langpkg/scan.go:80
  - failed to initialize a driver:
    github.com/aquasecurity/trivy/pkg/detector/library.Detect
        /home/runner/work/trivy/trivy/pkg/detector/library/detect.go:19
  - unsupported type bitnami:
    github.com/aquasecurity/trivy/pkg/detector/library.NewDriver
        /home/runner/work/trivy/trivy/pkg/detector/library/driver.go:72
```
```


### Operating System

Ubuntu 20

### Version

```bash
Version: 0.42.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-06-05 06:08:14.618801312 +0000 UTC
  NextUpdate: 2023-06-05 12:08:14.618800712 +0000 UTC
  DownloadedAt: 2023-06-05 08:48:12.274325097 +0000 UTC
Java DB:
  Version: 1
  UpdatedAt: 2023-06-05 00:55:01.046797024 +0000 UTC
  NextUpdate: 2023-06-08 00:55:01.046796423 +0000 UTC
  DownloadedAt: 2023-06-05 08:58:54.678190662 +0000 UTC
Policy Bundle:
  Digest: sha256:2f95caeff50df1f00efdf5cb619c3b5488bbbb9bb08ef0890f52352464d35c79
  DownloadedAt: 2023-04-03 06:43:06.135944368 +0000 UTC
```
```


### Checklist

- [X] Run `trivy --reset`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)</div>

### PR DESCRIPTION
**Pull request by nikpivkin**
## Description

I think we can skip dependency detection for an unsupported library type, rather than throwing an error and stopping scanning.

Before:
```bash
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:0.42.0 image docker.io/bitnami/rabbitmq:3.11.17-debian-11-r2 --debug
2023-06-07T06:22:02.716Z	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-06-07T06:22:02.718Z	DEBUG	cache dir:  /root/.cache/trivy
2023-06-07T06:22:02.719Z	DEBUG	DB update was skipped because the local DB is the latest
2023-06-07T06:22:02.719Z	DEBUG	DB Schema: 2, UpdatedAt: 2023-06-07 06:07:05.537434966 +0000 UTC, NextUpdate: 2023-06-07 12:07:05.537434566 +0000 UTC, DownloadedAt: 2023-06-07 06:22:00.465958296 +0000 UTC
2023-06-07T06:22:02.719Z	INFO	Vulnerability scanning is enabled
2023-06-07T06:22:02.719Z	DEBUG	Vulnerability type:  [os library]
2023-06-07T06:22:02.719Z	INFO	Secret scanning is enabled
2023-06-07T06:22:02.719Z	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-06-07T06:22:02.719Z	INFO	Please see also https://aquasecurity.github.io/trivy/v0.42/docs/secret/scanning/#recommendation for faster secret detection
2023-06-07T06:22:02.725Z	DEBUG	No secret config detected: trivy-secret.yaml
2023-06-07T06:22:02.726Z	DEBUG	Image ID: sha256:c380a14b64f7d96b1a66f20f372ed0f4005ac6fe9295a7d66ec6d0a849d58fb9
2023-06-07T06:22:02.726Z	DEBUG	Diff IDs: [sha256:bd543f134be8b19df8d7f3fe385989200bd3dfac2ea09f8781f3c4c234dc754c]
2023-06-07T06:22:02.726Z	DEBUG	Base Layers: []
2023-06-07T06:22:02.730Z	INFO	Detected OS: debian
2023-06-07T06:22:02.730Z	INFO	Detecting Debian vulnerabilities...
2023-06-07T06:22:02.731Z	DEBUG	debian: os version: 11
2023-06-07T06:22:02.731Z	DEBUG	debian: the number of packages: 111
2023-06-07T06:22:02.741Z	INFO	Number of language-specific files: 1
2023-06-07T06:22:02.741Z	INFO	Detecting bitnami vulnerabilities...
2023-06-07T06:22:02.741Z	DEBUG	Detecting library vulnerabilities, type: bitnami, path: opt/bitnami/rabbitmq/bin/rabbitmq
2023-06-07T06:22:02.741Z	FATAL	image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:426
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:268
  - scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.scan
        /home/runner/work/trivy/trivy/pkg/commands/artifact/run.go:683
  - scan failed:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        /home/runner/work/trivy/trivy/pkg/scanner/scan.go:154
  - failed to detect vulnerabilities:
    github.com/aquasecurity/trivy/pkg/scanner/local.Scanner.Scan
        /home/runner/work/trivy/trivy/pkg/scanner/local/scan.go:102
  - failed to scan application libraries:
    github.com/aquasecurity/trivy/pkg/scanner/local.Scanner.scanVulnerabilities
        /home/runner/work/trivy/trivy/pkg/scanner/local/scan.go:189
  - failed vulnerability detection of libraries:
    github.com/aquasecurity/trivy/pkg/scanner/langpkg.(*scanner).Scan
        /home/runner/work/trivy/trivy/pkg/scanner/langpkg/scan.go:80
  - failed to initialize a driver:
    github.com/aquasecurity/trivy/pkg/detector/library.Detect
        /home/runner/work/trivy/trivy/pkg/detector/library/detect.go:19
  - unsupported type bitnami:
    github.com/aquasecurity/trivy/pkg/detector/library.NewDriver
        /home/runner/work/trivy/trivy/pkg/detector/library/driver.go:72
```

After:
```bash
2023-06-07T12:23:37.512+0600	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-06-07T12:23:37.527+0600	DEBUG	cache dir:  /Users/tososomaru/Library/Caches/trivy
2023-06-07T12:23:37.527+0600	DEBUG	DB update was skipped because the local DB is the latest
2023-06-07T12:23:37.527+0600	DEBUG	DB Schema: 2, UpdatedAt: 2023-06-07 06:07:05.537434966 +0000 UTC, NextUpdate: 2023-06-07 12:07:05.537434566 +0000 UTC, DownloadedAt: 2023-06-07 06:22:00.465958296 +0000 UTC
2023-06-07T12:23:37.527+0600	INFO	Vulnerability scanning is enabled
2023-06-07T12:23:37.527+0600	DEBUG	Vulnerability type:  [os library]
2023-06-07T12:23:37.527+0600	INFO	Secret scanning is enabled
2023-06-07T12:23:37.527+0600	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-06-07T12:23:37.527+0600	INFO	Please see also https://aquasecurity.github.io/trivy/dev/docs/secret/scanning/#recommendation for faster secret detection
2023-06-07T12:23:37.559+0600	DEBUG	No secret config detected: trivy-secret.yaml
2023-06-07T12:23:37.559+0600	DEBUG	Image ID: sha256:c380a14b64f7d96b1a66f20f372ed0f4005ac6fe9295a7d66ec6d0a849d58fb9
2023-06-07T12:23:37.559+0600	DEBUG	Diff IDs: [sha256:bd543f134be8b19df8d7f3fe385989200bd3dfac2ea09f8781f3c4c234dc754c]
2023-06-07T12:23:37.559+0600	DEBUG	Base Layers: []
2023-06-07T12:23:37.566+0600	INFO	Detected OS: debian
2023-06-07T12:23:37.566+0600	INFO	Detecting Debian vulnerabilities...
2023-06-07T12:23:37.566+0600	DEBUG	debian: os version: 11
2023-06-07T12:23:37.566+0600	DEBUG	debian: the number of packages: 111
2023-06-07T12:23:37.587+0600	INFO	Number of language-specific files: 1
2023-06-07T12:23:37.587+0600	INFO	Detecting bitnami vulnerabilities...
2023-06-07T12:23:37.587+0600	DEBUG	Detecting library vulnerabilities, type: bitnami, path: opt/bitnami/rabbitmq/bin/rabbitmq
2023-06-07T12:23:37.587+0600	WARN	The bitnami library type is not supported. Skipping vulnerability detection

docker.io/bitnami/rabbitmq:3.11.17-debian-11-r2 (debian 11.7)
=============================================================
Total: 119 (UNKNOWN: 0, LOW: 85, MEDIUM: 6, HIGH: 23, CRITICAL: 5)
....
```

## Related issues
- Close #4566 
- Close #3994 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/detector/library/detect.go [hunk 1]
```diff
@@ -13,7 +13,7 @@ import (
 func Detect(libType string, pkgs []ftypes.Package) ([]types.DetectedVulnerability, error) {
 	driver, err := NewDriver(libType)
 	if err != nil {
-		if errors.Is(err, ErrSBOMSupportOnly) {
+		if errors.Is(err, ErrSBOMSupportOnly) || errors.Is(err, ErrUnsupportedType) {
 			return nil, nil
 		}
 		return nil, xerrors.Errorf("failed to initialize a driver: %w", err)
```
Comment (afdesk) [inline pkg/detector/library/detect.go:19]: this code is unreachable now, because `NewDriver` can return either `ErrSBOMSupportOnly` or `ErrUnsupportedType`. 
so we have to change this statement.

**Review by afdesk — CHANGES_REQUESTED** [review]

File: pkg/detector/library/detect.go (hunk 1 above)
Comment (nikpivkin) [reply pkg/detector/library/detect.go]: done

**Review by afdesk — APPROVED** [review]

File: pkg/detector/library/driver.go [hunk 2]
```diff
@@ -64,18 +62,19 @@ func NewDriver(libType string) (Driver, error) {
...
 		log.Logger.Warn("CocoaPods is supported for SBOM, not for vulnerability scanning")
-		return Driver{}, ErrSBOMSupportOnly
+		return Driver{}, false
 	case ftypes.CondaPkg:
 		log.Logger.Warn("Conda package is supported for SBOM, not for vulnerability scanning")
-		return Driver{}, ErrSBOMSupportOnly
+		return Driver{}, false
 	default:
-		return Driver{}, xerrors.Errorf("unsupported type %s", libType)
+		log.Logger.Warnf("The %s library type is not supported. Skipping vulnerability detection", libType)
```
Comment (knqyf263) [inline pkg/detector/library/driver.go:70]:
```suggestion
		log.Logger.Warnf("The %q library type is not supported for vulnerability scanning", libType)
```

Comment (nikpivkin) [reply pkg/detector/library/driver.go]: fixed

**Review by knqyf263 — APPROVED** [review]
