### PR TITLE
fix(python): nil pointer dereference with optional poetry groups without dependencies

### LINKED ISSUE #10358: Segfault when poetry dependency groups have optional=true without dependencies
## Description

Trivy panics with a nil pointer dereference when scanning a project that has Poetry dependency groups defined with `optional = true` but without a `dependencies` section.

For example:

```toml
[tool.poetry.group.docs]
optional = true
```

This is valid Poetry configuration (groups can be marked optional without declaring dependencies), but Trivy crashes because `directDeps()` in `poetry.go` calls `Items()` on a nil `Dependencies.Set`.

## Reproduction Steps

1. Create a new folder
2. `python3 -m venv venv && . venv/bin/activate`
3. `poetry init` with default settings
4. `poetry add pyaml && poetry add -G test pytest`
5. Add to `pyproject.toml`:
   ```toml
   [tool.poetry.group.docs]
   optional = true
   ```
6. `trivy fs .` → segfault

## Stack Trace

```
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/python/poetry.directDeps(...)
        github.com/aquasecurity/trivy/pkg/fanal/analyzer/language/python/poetry/poetry.go:126 +0x74
```

## References

- Reported in https://github.com/aquasecurity/trivy/discussions/10356

### PR DESCRIPTION
**Pull request by knqyf263**
## Description

When a Poetry dependency group is defined with only `optional = true` and no `dependencies` section (e.g., `[tool.poetry.group.docs]` with `optional = true`), `directDeps()` calls `Items()` on a nil `Dependencies.Set`, causing a nil pointer dereference panic.

This adds a nil check before accessing the set.

## Related issues
- Close #10358

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/analyzer/language/python/poetry/poetry.go [hunk 1]
```diff
@@ -123,7 +123,9 @@ func (a poetryAnalyzer) mergePyProject(fsys fs.FS, dir string, app *types.Applic
 func directDeps(project pyproject.PyProject) set.Set[string] {
 	deps := project.MainDeps()
 	for _, groupDeps := range project.Tool.Poetry.Groups {
-		deps.Append(groupDeps.Dependencies.Items()...)
+		if groupDeps.Dependencies.Set != nil {
```
Comment (DmitriyLewen) [inline pkg/fanal/analyzer/language/python/poetry/poetry.go:126]: There is a similar problem in the pyproject.go file
https://github.com/aquasecurity/trivy/blob/d0a3f63b84e6a8cd9067e85344097f9179c14b0d/pkg/dependency/parser/python/pyproject/pyproject.go#L48
Perhaps we want to fix this problem in this PR?

**Review by DmitriyLewen — APPROVED** [review]
LGTM

left one comment.

**Comment by msecmhi** [comment]
@knqyf263 FWIW, there seems to be some parser parser differential between poetry and trivy, as **non-empty optional groups** cause this segfault too if the dependencies are specified using:

```toml
[dependency-groups]
test = "some-python-package (>=7.0.0,<8.0.0)"
```

The issue disappears when using `[tool.poetry.group.test.dependencies]`, I assume trivy fails to understand the link between those different headers - this might indicate some blindspots / unscanned dependencies.
