### PR TITLE
fix: fail k8s resource scanning

### LINKED ISSUE #5528: k8s scanning fails in 0.47.0
### Discussed in https://github.com/aquasecurity/trivy/discussions/5521

<div type='discussions-op-text'>

<sup>Originally posted by **michael-mader** November  6, 2023</sup>
### Description

The following command fails with trivy 0.47.0:

`trivy -d k8s --context "my-context" -n default deployments/my-release`

It fails with this output:
```
2023-11-06T11:12:28.630+0100    FATAL   k8s scan error:
    github.com/aquasecurity/trivy/pkg/k8s/commands.(*runner).run
        /home/runner/work/trivy/trivy/pkg/k8s/commands/run.go:95
  - failed to find node name
```

it is working in 0.46.1 and below. It is failing when using the trivy binary on MacOS 14.1 and running the 0.47.0 docker image on linux.

### Desired Behavior

Runs till end and does only fail if there are vulnerabilities

### Actual Behavior

Fails:
```
2023-11-06T11:12:28.630+0100    FATAL   k8s scan error:
    github.com/aquasecurity/trivy/pkg/k8s/commands.(*runner).run
        /home/runner/work/trivy/trivy/pkg/k8s/commands/run.go:95
  - failed to find node name
```

### Reproduction Steps

```bash
Run `trivy -d k8s --context "my-context" -n default deployments/my-release` with correct values for your deployment to scan.
```

### Target

Kubernetes

### Scanner

Vulnerability

### Output Format

None

### Mode

Standalone

### Debug Output

```bash
/Users/user/Downloads/trivy_0.47.0_macOS-ARM64/trivy -d k8s --context "my-context" -n default --no-progress deployments/my-deployment
2023-11-06T11:16:36.451+0100    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-11-06T11:16:36.452+0100    DEBUG   Ignore statuses {"statuses": null}
2023-11-06T11:16:38.362+0100    DEBUG   cache dir:  /Users/user/Library/Caches/trivy
2023-11-06T11:16:38.363+0100    DEBUG   DB update was skipped because the local DB is the latest
2023-11-06T11:16:38.363+0100    DEBUG   DB Schema: 2, UpdatedAt: 2023-11-06 06:17:59.317996254 +0000 UTC, NextUpdate: 2023-11-06 12:17:59.317995754 +0000 UTC, DownloadedAt: 2023-11-06 10:10:16.850618 +0000 UTC
1 / 1 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 0 p/s
2023-11-06T11:16:41.552+0100    FATAL   k8s scan error:
    github.com/aquasecurity/trivy/pkg/k8s/commands.(*runner).run
        /home/runner/work/trivy/trivy/pkg/k8s/commands/run.go:95
  - failed to find node name

```
```


### Operating System

macOS 14.1

### Version

```bash
Version: 0.47.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-11-06 06:17:59.317996254 +0000 UTC
  NextUpdate: 2023-11-06 12:17:59.317995754 +0000 UTC
  DownloadedAt: 2023-11-06 10:10:16.850618 +0000 UTC
Java DB:
  Version: 1
  UpdatedAt: 2023-11-06 00:56:11.785628882 +0000 UTC
  NextUpdate: 2023-11-09 00:56:11.785628382 +0000 UTC
  DownloadedAt: 2023-11-06 10:10:50.304873 +0000 UTC
Policy Bundle:
  Digest: sha256:1df8ade71efc830877ca3b1130f83e0c6368e3a45b0d4c0f0418955501644054
  DownloadedAt: 2023-11-06 10:10:17.701092 +0000 UTC
```

### Checklist

- [X] Run `trivy image --reset`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)</div>

### PR DESCRIPTION
**Pull request by chen-keinan**
## Description
Fail to fetch node name on k8s resource scanning 

## Related issues
- Close #5528 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.

### CODE REVIEW

File: pkg/k8s/scanner/scanner.go [hunk 1]
```diff
@@ -226,7 +226,7 @@ func (s *Scanner) scanK8sVulns(ctx context.Context, artifactsData []*artifacts.A
 	var resources []report.Resource
 	var nodeName string
 	if nodeName = findNodeName(artifactsData); nodeName == "" {
-		return nil, fmt.Errorf("failed to find node name")
+		return resources, nil
```
Comment (knqyf263) [inline pkg/k8s/scanner/scanner.go:229]: Is it ok to return here? Can't we scan vulnerabilities at all when we don't find a node name?

Also, I found another place using `findNodeName`. Don't we need to fix it?
https://github.com/aquasecurity/trivy/blob/d9977c39ebf662815bd2426d80276a3b87013dd5/pkg/k8s/scanner/scanner.go#L355-L357

Comment (chen-keinan) [reply pkg/k8s/scanner/scanner.go:229]: 1. yes, if there is no node name meaning its `namespace` or `resource` scope. k8s core components scanning is available only on cluster scope
2. the 2nd on is related to `kbom` if no node name then trivy show throw an error

**Review by knqyf263 — APPROVED** [review]
