### PR TITLE
fix(vex): use a separate `visited` set for each DFS path

### LINKED ISSUE #9757: bug(vex): Trivy skips the rule if we check the same parent from different paths.
## Description
We fixed an issue where two (or more) dependencies could cyclically depend on each other, causing incorrect traversal and follow-up logic.
See #9465

```mermaid
flowchart LR
  A --> B
  B --> A
```

But there are cases where a leaf reach the same ancestor through multiple distinct paths: in such situations, we skip applying the parent-filtering rule for that already-visited ancestor (we’ve already evaluated it), so we do not filter the vulnerability.

```mermaid
flowchart LR
  A --> B
  B --> C
  C --> X

  A --> D
  D --> E
  E --> F
  F --> X

  D --> G
  G --> H
  H --> F
```

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description

  This PR fixes a critical bug in VEX (Vulnerability Exploitability eXchange) processing where the visited set was being shared across different dependency paths during depth-first search traversal. The issue caused incorrect
  vulnerability filtering when multiple parents had dependencies on the same component.

## Reasons

  The original implementation had a fundamental flaw where the visited map was shared across all recursive paths in the DFS traversal. This meant that if component A was visited through one parent path, it would be marked as visited for
  all other parent paths, potentially causing the algorithm to incorrectly conclude that a component couldn't reach the root when it actually could through a different path.

  This bug was particularly problematic in scenarios with diamond dependencies (multiple paths to the same component) and could lead to incorrect vulnerability filtering decisions in VEX processing.

## Related issues
- Close #9757

## Related PRs
- [x] #9465

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by DmitriyLewen** [comment]
As an alternative solution, we can merge #9007 and revert #9465.
#9007 will solve the problem with cyclic dependencies (since all of them will be linked to the root component),
and reverting of 9465 will remove the incorrect parent check (the visited function).

File: pkg/vex/vex_test.go [hunk 1]
```diff
@@ -585,6 +599,37 @@ repositories:
...
 			}),
 		},
+		{
+			name: "check one parent from multiple dependency paths",
+			args: args{
+				// - oci:debian?tag=12
+				//     - pkg:deb/debian/base-files@5.3
+				//        - pkg:deb/debian/bash@5.3
+				//     - pkg:deb/debian/base-files2@5.3
+				//        - pkg:deb/debian/bash@5.3
```
Comment (knqyf263) [inline pkg/vex/vex_test.go:609]: This test case looks like multiple parents (bash-files@5.3 and bash-files2@5.3) from a single dependency (bash@5.3). Am I missing something?

Comment (DmitriyLewen) [reply pkg/vex/vex_test.go:609]: Right.
But oci:debian?tag=12 is the parent for both bash-files@5.3 and bash-files2@5.3.

For this test case there are two dependency paths:
1.	pkg:deb/debian/bash@5.3 -> pkg:deb/debian/base-files@5.3 -> oci:debian?tag=12
2.	pkg:deb/debian/bash@5.3 -> pkg:deb/debian/base-files2@5.3 -> oci:debian?tag=12

After the first path, we mark oci:debian?tag=12 as visited.
When we process pkg:deb/debian/base-files2@5.3, we see that oci:debian?tag=12 is already visited and return true.

**Comment by knqyf263** [comment]
>https://github.com/aquasecurity/trivy/pull/9007 will solve the problem with cyclic dependencies (since all of them will be linked to the root component),

I reviewed the change and I’m leaning toward this idea. However, it's not good to often change the SBOM structure. What do you think?

**Comment by DmitriyLewen** [comment]
I also don’t like changing the logic back and forth (since #9007 is basically a revert of the changes as well).
That’s actually why I created this PR.

However, we still need to fix #9011 somehow.

We can consider the first fix option (https://github.com/aquasecurity/trivy/pull/9007/commits/9f4702cacb7cfc2b395c8ab97ccb7a85d0cfc220).
I mean the logic where we add relationships only for orphan packages.
But then we have a choice:
- simpler logic, but effectively a revert
- more complex logic
