### PR TITLE
fix(java): add hash of GAV+root pom file path for pkgID for packages from pom.xml files

### LINKED ISSUE #7824: bug(sbom): Duplicate SBOM packages for multi-module pom.xml files
## Description
`mvn` handles `modules` separate.
Trivy uses same logic:
https://github.com/aquasecurity/trivy/blob/57e24aa85382f749df7f673e241caaf3fcbb45cb/pkg/dependency/parser/java/pom/parse.go#L142-L143

But `SPDX` format doesn't allow duplicate SPDXIDs - https://spdx.github.io/spdx-spec/v2.3/package-information/#72-package-spdx-identifier-field

Same for `CycloneDX` - https://cyclonedx.org/docs/1.6/json/#components

## Solutions
1. We will add `workspace` relationship for maven modules (see #7802). After these changes Trivy will use `rootPkg -> workspace -> directDeps -> IndirectDeps` logic.
This logic is different from `mvn` logic. So may want to remove duplicates in [parser](https://github.com/aquasecurity/trivy/blob/57e24aa85382f749df7f673e241caaf3fcbb45cb/pkg/dependency/parser/java/pom/parse.go).
2. We will remove duplicates when converting [Report](https://github.com/aquasecurity/trivy/blob/7aea79dd93cfb61453766dbbb2e3fc0fbd317852/pkg/types/report.go#L14) into [BOM](https://github.com/aquasecurity/trivy/blob/4a2f492c6e685ff577fb96a7006cd0c43755baf4/pkg/sbom/core/bom.go#L57)
## Example
Test project:
```bash
➜  cat pom.xml 
    <groupId>com.example</groupId>
    <artifactId>root</artifactId>
    <version>1.0.0</version>

    <modules>
        <module>module1</module>
        <module>module2</module>
    </modules>

➜  cat module1/pom.xml 
    <groupId>com.example</groupId>
    <artifactId>module1</artifactId>
    <version>1.0.0</version>

    <dependencies>
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>example-api</artifactId>
            <version>1.1.1</version>
        </dependency>
    </dependencies>

➜  cat module2/pom.xml
    <groupId>com.example</groupId>
    <artifactId>module2</artifactId>
    <version>2.0.0</version>

    <dependencies>
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>example-api</artifactId>
            <version>1.1.1</version>
        </dependency>
    </dependencies>
```
`mvn` output:
```bash
➜  mvn dependency:tree
[INFO] ------------------------< com.example:module1 >-------------------------
[INFO] Building module1 1.0.0                                             [1/3]
[INFO]   from module1/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.example:example-api:jar:1.1.1 is missing, no dependency information available
[INFO] 
[INFO] --- dependency:3.7.0:tree (default-cli) @ module1 ---
[INFO] com.example:module1:jar:1.0.0
[INFO] \- org.example:example-api:jar:1.1.1:compile
[INFO] 
[INFO] ------------------------< com.example:module2 >-------------------------
[INFO] Building module2 2.0.0                                             [2/3]
[INFO]   from module2/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.7.0:tree (default-cli) @ module2 ---
[INFO] com.example:module2:jar:2.0.0
[INFO] \- org.example:example-api:jar:1.1.1:compile
[INFO] 
[INFO] --------------------------< com.example:root >--------------------------
[INFO] Building root 1.0.0                                                [3/3]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- dependency:3.7.0:tree (default-cli) @ root ---
[INFO] com.example:root:pom:1.0.0
[INFO] ------------------------------------------------------------------------

``` 

trivy outputs:
```bash
➜  trivy -q fs ./pom.xml -f json --list-all-pkgs | grep ID
...
          "ID": "org.example:example-api:1.1.1",
            "UID": "e574f6e703187373"
          "ID": "org.example:example-api:1.1.1",
            "UID": "e574f6e703187373"

➜  trivy -q fs ./pom.xml -f spdx-json | grep SPDXID -B 1
...
      "name": "org.example:example-api",
      "SPDXID": "SPDXRef-Package-a9813b377fc4bc80",
--
      "name": "org.example:example-api",
      "SPDXID": "SPDXRef-Package-a9813b377fc4bc80",
...
```
### Discussed in https://github.com/aquasecurity/trivy/discussions/7795

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description

  This PR refactors Maven POM dependency parsing to use a composite package ID format that combines GAV (GroupId:ArtifactId:Version) coordinates with a hash of the POM file path. The new format is groupId:artifactId:version::hash8, where hash8 is an 8-character hash derived from both the GAV and the file path.

  This change addresses issues with duplicate package identification in multi-module Maven projects where the same dependency can appear in different modules with potentially different transitive dependency trees.

## Changes

  - Modified package ID generation (pkg/dependency/parser/java/pom/parse.go:897-911): Added packageID() function that generates IDs in the format GAV::hash8 using hashstructure to hash both the GAV and file path
  - Added RootFilePath tracking (pkg/dependency/parser/java/pom/artifact.go:35-38): Added RootFilePath field to artifact struct to store the root or module POM file path for hash calculation
  - Updated parsing logic (pkg/dependency/parser/java/pom/parse.go:129-131,141,175-176,259,268): Threading RootFilePath through artifact creation and analysis to ensure proper package ID generation
  - Enhanced vulnerability sorting (pkg/types/vulnerability.go:45-56): Updated BySeverity.Less() to include PkgID comparison for disambiguating packages with identical names but different IDs
  - Updated test fixtures: Modified integration test golden files and added comprehensive test cases for multi-module scenarios
  - Added filter sorting (pkg/result/filter.go): Sort vulnerabilities by PkgID to ensure deterministic filtering behavior

## Benefits

  1. Unique identification: Prevents package ID collisions in multi-module Maven projects where the same dependency appears in different modules
  2. Accurate dependency tracking: Each module's dependencies are tracked independently with their own dependency trees
  3. Improved vulnerability reporting: Vulnerabilities can be correctly associated with specific module contexts
  4. Deterministic results: Consistent package ID generation across different runs and platforms (using filepath.ToSlash for cross-platform compatibility)
  5. Better filtering and sorting: Enhanced vulnerability filtering and sorting with PkgID-based disambiguation

## Reasons

  Problem: In multi-module Maven projects, the same dependency (same GAV coordinates) can appear in multiple modules. Previously, Trivy used only the GAV as the package ID, which caused:
  - Loss of module context for dependencies
  - Inability to track different transitive dependency trees for the same package in different modules
  - Potential issues with vulnerability deduplication and filtering

## Related issues
- Close #7824

## Related PRs
- [x] #7879

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/docs/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/docs/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by DmitriyLewen** [comment]
@knqyf263 I created PR with your idea (https://github.com/aquasecurity/trivy/pull/7879#issuecomment-3574120751)
take a look, when you have time, please

File: pkg/dependency/parser/java/pom/parse.go [hunk 1]
```diff
@@ -133,12 +137,17 @@ func (p *Parser) Parse(ctx context.Context, r xio.ReadSeekerAt) ([]ftypes.Packag
...
 	rootArt.Relationship = ftypes.RelationshipRoot
+	rootArt.RootFilePath = p.rootPath
 
 	return p.parseRoot(ctx, rootArt, set.New[string]())
 }
 
 // nolint: gocyclo
 func (p *Parser) parseRoot(ctx context.Context, root artifact, uniqModules set.Set[string]) ([]ftypes.Package, []ftypes.Dependency, error) {
+	if root.RootFilePath == "" {
+		return nil, nil, xerrors.New("root file path should be filled")
```
Comment (knqyf263) [inline pkg/dependency/parser/java/pom/parse.go]: nit

```suggestion
		return nil, nil, xerrors.New(""root file path is required for package ID generation"")
```

File: pkg/dependency/parser/java/pom/parse.go [hunk 2]
```diff
@@ -875,8 +893,19 @@ func parseMavenMetadata(r io.Reader) (*Metadata, error) {
...
+		"path": filepath.ToSlash(pomFilePath),
+	}
+	h, err := hashstructure.Hash(v, hashstructure.FormatV2, &hashstructure.HashOptions{
+		ZeroNil:         true,
+		IgnoreZeroValue: true,
+	})
+	if err != nil {
+		log.Warn("Failed to calculate the pom.xml hash", log.String("name", name), log.String("version", version), log.Err(err))
+	}
+	return strconv.FormatUint(h, 16)
```
Comment (knqyf263) [inline pkg/dependency/parser/java/pom/parse.go]: What do you think about including GAV in the ID for readability? Something like `com.example:log4shell:1.0-SNAPSHOT::a302c021` (GAV + 8-char hash suffix).

```suggestion
func packageID(name, version, pomFilePath string) string {
    gav := dependency.ID(ftypes.Pom, name, version)
    v := map[string]any{
        "gav":  gav,
        "path": filepath.ToSlash(pomFilePath),
    }
    h, err := hashstructure.Hash(v, hashstructure.FormatV2, &hashstructure.HashOptions{
        ZeroNil:         true,
        IgnoreZeroValue: true,
    })
    if err != nil {
        log.Warn("Failed to calculate hash", log.Err(err))
        return gav // fallback to GAV only
    }
    // Append 8-character hash suffix
    return fmt.Sprintf("%s::%s", gav, strconv.FormatUint(h, 16)[:8])
  }
```

File: pkg/report/table/vulnerability.go [hunk 3]
```diff
@@ -377,3 +378,17 @@ func rootJarFromPath(path string) string {
...
+
+// vulnID builds human-readable vulnerability package ID for POM target type (override hash to groupId:artifactId:version)
+// and returns package ID for other target types.
+func vulnID(t ftypes.TargetType, pkg ftypes.Package) string {
+	if t == ftypes.Pom {
+		pomIDInfoOnce()
+		return dependency.ID(t, pkg.Name, pkg.Version)
+	}
+	return pkg.ID
+}
```
Comment (knqyf263) [inline pkg/report/table/vulnerability.go]: `com.example:log4shell:1.0-SNAPSHOT::a302c021` doesn't need this function. Or, we can just cut `::`.

**Review by knqyf263 — APPROVED** [review]
I left one comment with my idea, but overall it looks good to me.

File: pkg/dependency/parser/java/pom/parse.go (hunk 2 above)
Comment (DmitriyLewen) [reply pkg/dependency/parser/java/pom/parse.go]: This is good idea!
Updated in https://github.com/aquasecurity/trivy/pull/9880/changes/1be928578f58539aaa5d8223f093ad2f07146834

File: pkg/report/table/vulnerability.go (hunk 3 above)
Comment (DmitriyLewen) [reply pkg/report/table/vulnerability.go]: Yeah. Let's use new IDs.
If users ask to remove the hash suffix, we will trim it in another PR.
