### PR TITLE
fix(sbom): duplicate dependson

### LINKED ISSUE #3260: Trivy is not generating compliant cyclonedx json
## Description

It would be nice if trivy is continuously tested to generate compliant cyclonedx in json format.

```
trivy image shiftleft/scan:latest -f cyclonedx --output trivy-bom.json
cyclonedx validate --input-file trivy-bom.json --input-format json --input-version v1_4                                         
Validating JSON BOM...
Validation failed: Found duplicates at the following index pairs: "(8, 34), (9, 35), (12, 43), (12, 91), (18, 53), (18, 100), (18, 128), (42, 90), (43, 91), (53, 100), (53, 128), (57, 125), (60, 102), (65, 103), (68, 104), (69, 105), (71, 121), (76, 108), (82, 111), (88, 112), (94, 116), (99, 120), (100, 128), (1080, 1081)"
#/properties/dependencies/items/$ref/properties/dependsOn/uniqueItems
BOM is not valid.
```

## What did you expect to happen?
cyclonedx cli based validation to succeed

## Output of run with `-debug`:

Not relevant

## Output of `trivy -v`:

```
trivy -v                                                                                                                      
Version: 0.33.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-12-01 12:08:24.329983324 +0000 UTC
  NextUpdate: 2022-12-01 18:08:24.329982924 +0000 UTC
  DownloadedAt: 2022-12-01 13:15:57.796196741 +0000 UTC
```

## Additional details (base image name, container registry info...):
shiftleft/scan:latest

Seems to be failing for most of the images tried.

### PR DESCRIPTION
**Pull request by masahiro331**
## Description

* Changed to avoid duplicate dependsOn.
* Changed to create Application Component with RustBinary and GoBinary.

## Related issues
- Close #3260 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/sbom/cyclonedx/marshal.go [hunk 1]
```diff
@@ -205,6 +205,7 @@ func (e *Marshaler) marshalComponents(r types.Report, bomRef string) (*[]cdx.Com
 			pkgID := packageID(result.Target, pkg.Name, utils.FormatVersion(pkg), pkg.FilePath)
 			if _, ok := bomRefMap[pkgID]; !ok {
 				bomRefMap[pkgID] = pkgComponent.BOMRef
+				componentDependencies = append(componentDependencies, cdx.Dependency{Ref: pkgComponent.BOMRef})
```
Comment (knqyf263) [inline pkg/sbom/cyclonedx/marshal.go:208]: Why could it be duplicated? `componentDependencies` is defined per `types.Result`. The duplicate should not exist in `Result.Packages`.

File: pkg/sbom/cyclonedx/marshal.go [hunk 2]
```diff
@@ -247,8 +246,8 @@ func (e *Marshaler) marshalComponents(r types.Report, bomRef string) (*[]cdx.Com
 			}
 		}
 
-		if result.Type == ftypes.NodePkg || result.Type == ftypes.PythonPkg || result.Type == ftypes.GoBinary ||
-			result.Type == ftypes.GemSpec || result.Type == ftypes.Jar || result.Type == ftypes.RustBinary {
+		if result.Type == ftypes.NodePkg || result.Type == ftypes.PythonPkg ||
```
Comment (knqyf263) [inline pkg/sbom/cyclonedx/marshal.go:249]: Looks like this is the root. We aggregate Go/Rust binaries by mistake.

**Review by knqyf263 — APPROVED** [review]

File: pkg/sbom/cyclonedx/marshal.go (hunk 2 above)
Comment (prabhu) [reply pkg/sbom/cyclonedx/marshal.go:249]: Are we no longer aggregating these components with this change, or would this only filter duplicates?

Comment (knqyf263) [reply pkg/sbom/cyclonedx/marshal.go:249]: We no longer aggregate dependencies in Go/Rust binaries. It should have been a mistake.

Comment (prabhu) [reply pkg/sbom/cyclonedx/marshal.go:249]: Oh no. I was relying on this feature in my project. Any ideas for enabling go/rust binary parsing while generating SBoM with the new release?

Comment (masahiro331) [reply pkg/sbom/cyclonedx/marshal.go:249]: No problem. 

This feature does not aggregate packages depending on binaries.

Before.
```
golang
 -  package A
 -  package B
 -  package C
``` 

After 
```
Binary A 
- package A
- package B

Binary B 
- package C
```

Comment (knqyf263) [reply pkg/sbom/cyclonedx/marshal.go:249]: We just don't aggregate those dependencies. You are still able to see those packages in SBOM.

Comment (prabhu) [reply pkg/sbom/cyclonedx/marshal.go:249]: Thank you, @masahiro331 and @knqyf263, for the detailed explanation!
