### PR TITLE
fix(report): handle `git@github.com` schema for misconfigs in `sarif` report

### LINKED ISSUE #7897: bug(sarif): we need to handle protocol for misconfig URI
### Discussed in https://github.com/aquasecurity/trivy/discussions/7893

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Overwrite `git@github.com` schema for misconfigs in `sarif` report.

## Related issues
- Close #7897

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by nikpivkin — APPROVED** [review]

File: pkg/report/sarif.go [hunk 1]
```diff
@@ -346,8 +346,18 @@ func ToPathUri(input string, resultClass types.ResultClass) string {
 	return clearURI(input)
 }
 
+// clearURI clears URI for misconfigs
 func clearURI(s string) string {
-	return strings.ReplaceAll(strings.ReplaceAll(s, "\\", "/"), "git::https:/", "")
+	s = strings.ReplaceAll(s, "\\", "/")
+	if strings.HasPrefix(s, "git::https:/") {
+		s = strings.ReplaceAll(s, "git::https:/", "")
```
Comment (nikpivkin) [inline pkg/report/sarif.go:353]: `.git` needs to be handled here too. The URI is as follows: `git::https://example.com/vpc.git?ref=v1.2.0`

Comment (DmitriyLewen) [reply pkg/report/sarif.go:353]: hm.. nice catch!
I didn't check previous logic.
Updated in https://github.com/aquasecurity/trivy/pull/7898/commits/3ebdecfdafc7d5baf56816c30338cbf23db59a82

**Review by nikpivkin — APPROVED** [review]
