### PR TITLE
fix: Fix --file-patterns flag

### LINKED ISSUE #774: scan from docker-compose stack all images / local html reports
Hi @simar7 ,

Hope you are all well !

Is it possible to scan periodically/or after triggering a github action, all images in from a docker-compose file ? and save the reports in a local folder for each of them ?

Thanks for any insights or inputs for that.

Cheers,
X

### LINKED ISSUE #2608: trivy can scan dockerfile more than matching pattern Dockerfile*
Current version of trivy only support dockerfile with name starting with "Dockerfile". 
Same as using  as target, it only looks for "Dockerfile*"
Since docker support using `-f <dockerfile>`, trivy should have a similar feature . This is very useful with multiple dockerfiles,
some suggestions:
1. to allow user specify their dockerfile's name. e.g `trivy fs --security-checks config --file dockerfile1, dockerfile2, ...`
2. create a new type for `--security-checks ` e.g `--security-checks dockerfile` and use along with `--skip-files` e.g `trivy fs --security-checks dockerfile --skip-files some.txt .`

see test log:
```
docker$ trivy --version
Version: 0.30.4
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-07-27 12:07:07.855242681 +0000 UTC
  NextUpdate: 2022-07-27 18:07:07.855242281 +0000 UTC
  DownloadedAt: 2022-07-27 13:25:19.565918 +0000 UTC

docker$ trivy fs --security-checks config dockerfile 
2022-07-27T18:46:38.004+0200	INFO	Misconfiguration scanning is enabled
2022-07-27T18:46:38.042+0200	INFO	Detected config files: 0

docker$ trivy fs --security-checks config .
2022-07-27T18:58:35.661+0200	INFO	Misconfiguration scanning is enabled
2022-07-27T18:58:35.699+0200	INFO	Detected config files: 0
```
after rename dockerfile to Dockerfile, it works
```
docker$ mv dockerfile Dockerfile
docker$ trivy fs --security-checks config Dockerfile 
2022-07-27T18:46:51.456+0200	INFO	Misconfiguration scanning is enabled
2022-07-27T18:46:51.557+0200	INFO	Detected config files: 1

Dockerfile (dockerfile)

Tests: 22 (SUCCESSES: 21, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

HIGH: Specify at least 1 USER command in Dockerfile with non-root user as argument
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Running containers with 'root' user can lead to a container escape situation. It is a best practice to run containers as non-root users, which can be done by adding a 'USER' statement to the Dockerfile.

See https://avd.aquasec.com/misconfig/ds002
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


docker$ trivy fs --security-checks config .
2022-07-27T18:46:55.523+0200	INFO	Misconfiguration scanning is enabled
2022-07-27T18:46:55.624+0200	INFO	Detected config files: 1

Dockerfile (dockerfile)

Tests: 22 (SUCCESSES: 21, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

HIGH: Specify at least 1 USER command in Dockerfile with non-root user as argument
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Running containers with 'root' user can lead to a container escape situation. It is a best practice to run containers as non-root users, which can be done by adding a 'USER' statement to the Dockerfile.

See https://avd.aquasec.com/misconfig/ds002
────────────────────────────────────────────────
```

### PR DESCRIPTION
**Pull request by liamg**
Resolves #2608

Signed-off-by: Liam Galvin <liam.galvin@aquasec.com>

## Description
Fixes use of the `--file-patterns` flag. Defsec detection is now overridden when a custom file pattern is provided for the file type.

## Related issues
- Close #2608

### CODE REVIEW

**Review by owenrumney — APPROVED** [review]

File: pkg/fanal/handler/misconf/misconf.go [hunk 1]
```diff
@@ -39,6 +39,7 @@ func init() {
 const version = 1
 
 type misconfPostHandler struct {
+	options  artifact.Option
```
Comment (DmitriyLewen) [inline pkg/fanal/handler/misconf/misconf.go:42]: What if we only store `options.MisconfScannerOption.FilePatterns` here?
I think we don't need to keep all "options".

Comment (liamg) [reply pkg/fanal/handler/misconf/misconf.go]: Yeah, that's true, done :+1:

**Review by DmitriyLewen — APPROVED** [review]
