### PR TITLE
fix: de-duplicate same `dpkg` packages with different filePaths from different layers

### LINKED ISSUE #8297: fix(dpkg): de-duplicate same packages with different filePaths from different layers
## Description
We remove duplicates for debian packages from one layers:
https://github.com/aquasecurity/trivy/blob/1f5f34895823fae81bf521fc939bee743a50e304/pkg/fanal/analyzer/pkg/dpkg/dpkg.go#L202-L207

But there are cases when same packages with different filePaths are placed in different layers.
We need to de-duplicate these packages.

See #8273 for more details.

### Discussed in https://github.com/aquasecurity/trivy/discussions/8273

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
See #8297

## Related issues
- Close #8297

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/applier/docker.go [hunk 1]
```diff
@@ -232,6 +234,13 @@ func ApplyLayers(layers []ftypes.BlobInfo) ftypes.ArtifactDetail {
 		}
 	}
 
+	// De-duplicate same debian packages from different dirs
+	// cf. https://github.com/aquasecurity/trivy/issues/8297
+	packages := lo.UniqBy(mergedLayer.Packages, func(pkg ftypes.Package) string {
+		return cmp.Or(pkg.ID, fmt.Sprintf("%s@%s", pkg.Name, utils.FormatVersion(pkg)))
+	})
+	mergedLayer.Packages = lo.Ternary(len(packages) > 0, packages, nil)
```
Comment (knqyf263) [inline pkg/fanal/applier/docker.go:242]: Since this conversion is needed in many places, we may want to define a utility function somewhere, like:

```go
func NilIfEmpty[T any](s []T) []T {
    if len(s) == 0 {
        return nil
    }
    return s
}
```

Comment (DmitriyLewen) [reply pkg/fanal/applier/docker.go]: hm.. we already have this function 😄 :
https://github.com/aquasecurity/trivy/blob/60491f8a7e4a706c8a78586c010932ff3756c691/pkg/x/slices/slices.go#L3-L8

Used this function in https://github.com/aquasecurity/trivy/pull/8298/commits/4f939b793a879fc398683bfb3503142b2479191b

Comment (knqyf263) [reply pkg/fanal/applier/docker.go]: Oh, we already have it 😄

**Review by knqyf263 — APPROVED** [review]
