### PR TITLE
fix: handle Go 1.26 GOEXPERIMENT version format change

### LINKED ISSUE #10350: bug(go): Go 1.26 GOEXPERIMENT version format change causes stdlib version parsing warning
## Description
Starting with Go 1.26, the Go toolchain changed the format used to embed GOEXPERIMENT flags in the binary's build info. Trivy fails to correctly parse the stdlib version from binaries built with Go 1.26 when GOEXPERIMENT flags are present,
  producing a warning:
```
  WARN Version matching error err="version error (v1.26.0-X:nodwarf5): malformed version: v1.26.0-X:nodwarf5"
```
##  Root Cause

  In pkg/dependency/parser/golang/binary/parse.go, the code strips the GOEXPERIMENT suffix using a space as the separator:
```go
  // Ex: "go1.22.3 X:boringcrypto"
  stdlibVersion, _, _ = strings.Cut(stdlibVersion, " ")
```
  Go 1.26 changed the separator from a space to a dash (https://github.com/golang/go/commit/9daaab305c4d1dede9e4f6efdc5e1268a69327e6):
```
  ┌────────────┬───────────────────────┐
  │ Go version │ info.GoVersion format │
  ├────────────┼───────────────────────┤
  │ ≤ 1.25     │ go1.25.3 X:nodwarf5   │
  ├────────────┼───────────────────────┤
  │ ≥ 1.26     │ go1.26.0-X:nodwarf5   │
  └────────────┴───────────────────────┘
```
  With the new format, strings.Cut(..., " ") finds no match and returns the string unchanged. After prepending v, the result is v1.26.0-X:nodwarf5, which is treated as a pre-release semver and fails downstream version validation.

  This issue was previously reported for Go stdlib variants in #6698.

## Expected Behavior

  Trivy correctly extracts v1.26.0 as the stdlib version from binaries built with Go 1.26 + GOEXPERIMENT.

## Actual Behavior

  Trivy extracts v1.26.0-X:nodwarf5, fails to match it against the vulnerability DB, and logs:
  WARN Version matching error err="version error (v1.26.0-X:nodwarf5): malformed version: v1.26.0-X:nodwarf5"

## Proposed Fix

  Strip both separators —  X: (Go ≤1.25) and -X: (Go ≥1.26) — following the same approach used in the Go toolchain itself in https://github.com/golang/go/commit/9daaab305c4d1dede9e4f6efdc5e1268a69327e6:
```go
  // Strip GOEXPERIMENT suffix: "go1.25.3 X:foo" (Go <=1.25) or "go1.26.0-X:foo" (Go >=1.26)
  stdlibVersion, _, _ = strings.Cut(stdlibVersion, " X:")
  stdlibVersion, _, _ = strings.Cut(stdlibVersion, "-X:")
```
## References

  - Go toolchain commit: https://github.com/golang/go/commit/9daaab305c4d1dede9e4f6efdc5e1268a69327e6
  - Related Trivy issue: #6698
  - Community report: https://github.com/aquasecurity/trivy/discussions/10335

### PR DESCRIPTION
**Pull request by VedantMadane**
## Description
Go 1.26 changed the format used to embed GOEXPERIMENT flags in the binary's build info from \ X:\ separator (Go <=1.25) to \-X:\ separator (Go >=1.26). Trivy was failing to correctly parse the stdlib version from binaries built with Go 1.26 when GOEXPERIMENT flags are present.

## Changes
- Strip both GOEXPERIMENT separator formats when parsing stdlib version: \ X:foo\ (Go <=1.25) and \-X:foo\ (Go >=1.26)
- Extract version parsing logic to \parseStdlibVersion\ for testability
- Add unit tests for both format variants

## Testing
- Added \TestParseStdlibVersion\ with test cases for plain version, Go <=1.25 format (\go1.25.3 X:nodwarf5\), and Go >=1.26 format (\go1.26.0-X:nodwarf5\)
- Existing \goexperiment\ integration test continues to pass

Fixes #10350

### CODE REVIEW

File: pkg/dependency/parser/golang/binary/parse_internal_test.go
Comment (DmitriyLewen) [inline pkg/dependency/parser/golang/binary/parse_internal_test.go:1]: I think you can use export_test.go file for this test (instead of creating new file (parse_internal_test.go.)
e.g.
```diff
diff --git a/pkg/dependency/parser/golang/binary/export_test.go b/pkg/dependency/parser/golang/binary/export_test.go
index 3f361bc1e..2c0bb7545 100644
--- a/pkg/dependency/parser/golang/binary/export_test.go
+++ b/pkg/dependency/parser/golang/binary/export_test.go
@@ -13,3 +13,6 @@ func (p *Parser) ChooseMainVersion(version, ldflagsVersion, elfVersion string) s
 func (p *Parser) ELFSymbolVersion(r io.ReaderAt, name string) string {
 	return p.elfSymbolVersion(r, name)
 }
+
+
+var ParseStdlibVersion = parseStdlibVersion
\ No newline at end of file
diff --git a/pkg/dependency/parser/golang/binary/parse_internal_test.go b/pkg/dependency/parser/golang/binary/parse_internal_test.go
index bece0aeff..3a0102b8c 100644
--- a/pkg/dependency/parser/golang/binary/parse_internal_test.go
+++ b/pkg/dependency/parser/golang/binary/parse_internal_test.go
@@ -1,8 +1,9 @@
-package binary
+package binary_test
 
 import (
 	"testing"
 
+	"github.com/aquasecurity/trivy/pkg/dependency/parser/golang/binary"
 	"github.com/stretchr/testify/assert"
 )
 
@@ -40,7 +41,7 @@ func TestParseStdlibVersion(t *testing.T) {
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
-			got := parseStdlibVersion(tt.goVersion)
+			got := binary.ParseStdlibVersion(tt.goVersion)
 			assert.Equal(t, tt.want, got)
 		})
 	}

```

**Review by jtownnew13-collab — APPROVED** [review]

**Comment by DmitriyLewen** [comment]
Hello @VedantMadane 

I see that you did a rebase, but I don't see the suggested changes.
Let me know if you need my help.

Regards, Dmitriy
