### PR TITLE
fix(sbom): improve logic for binding direct dependency to parent component

### LINKED ISSUE #8488: bug(sbom): in some cases, an application component doesn't contain a direct dependency
## Description 
There are 2 cases when Direct dependency has parents:
1. when parent is Root or Workspace (we [handle](https://github.com/aquasecurity/trivy/blob/7558df7c227c769235e5441fbdd3f9f7efb1ff84/pkg/sbom/io/encode.go#L413) this case).
2. when Indirect dependency was added as Direct.
    e.g. we installed `sentry-sdk` (`django` is Indirect dependency) => after that we installed `django` (`django` is Direct dependency now).
    See #8487 for more details.
    I also added testcase for this issue - https://github.com/DmitriyLewen/trivy/commit/2558b3a0d9ff65446518b9648d67cfe0a7d1ae7c

So [belongToParent](https://github.com/aquasecurity/trivy/blob/7558df7c227c769235e5441fbdd3f9f7efb1ff84/pkg/sbom/io/encode.go#L406) can't currently handle these cases without info about ~~supported `Root`/`Workspace` relationships.~~ parents relationships.
for both case Direct dependency has parents. But for case 1 we don't need to bind dependency to root component, but for case 2 we need to do that.

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
This PR improves `belongToParent` logic for Direct dependencies:
- If parents contains `Root` or `Workspace` - doesn't bind dependency to the parent component (current logic)
- for other cases (if there are parents) we need to bind dependency to parent component (see #8488 for more details)

Example:
```json
{
  "ID": "django@5.1.6",
  "Name": "django",
  "Identifier": {
    "PURL": "pkg:pypi/django@5.1.6",
    "UID": "69691e87e187021d"
  },
  "Version": "5.1.6",
  "Relationship": "direct",
  "DependsOn": [
    "asgiref@3.8.1",
    "sqlparse@0.5.3",
    "tzdata@2025.1"
  ],
  "Layer": {}
},
{
  "ID": "sentry-sdk@2.22.0",
  "Name": "sentry-sdk",
  "Identifier": {
    "PURL": "pkg:pypi/sentry-sdk@2.22.0",
    "UID": "7e53a15e8bec68ad"
  },
  "Version": "2.22.0",
  "Relationship": "direct",
  "DependsOn": [
    "certifi@2025.1.31",
    "django@5.1.6",
    "urllib3@2.3.0"
  ],
  "Layer": {}
},
```

before:
```json
{
  "ref": "59c637a8-4c7b-4c61-b68e-a8731ff3bb09", // Application component
  "dependsOn": [
    "pkg:pypi/sentry-sdk@2.22.0"
  ]
},
{
  "ref": "pkg:pypi/sentry-sdk@2.22.0",
  "dependsOn": [
    "pkg:pypi/certifi@2025.1.31",
    "pkg:pypi/django@5.1.6",
    "pkg:pypi/urllib3@2.3.0"
  ]
},
```
after:
```json
{
  "ref": "285569c7-9e19-44e1-8bf0-906f4ef8d2a2",  // Application component
  "dependsOn": [
    "pkg:pypi/django@5.1.6",
    "pkg:pypi/sentry-sdk@2.22.0"
  ]
},
{
  "ref": "pkg:pypi/sentry-sdk@2.22.0",
  "dependsOn": [
    "pkg:pypi/certifi@2025.1.31",
    "pkg:pypi/django@5.1.6",
    "pkg:pypi/urllib3@2.3.0"
  ]
},
```

## Related issues
- Close #8488

## Related PRs
- [x] #8104

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
Does it work?

```diff
diff --git a/pkg/sbom/io/encode.go b/pkg/sbom/io/encode.go
index cf2c54648..8c9ea69a8 100644
--- a/pkg/sbom/io/encode.go
+++ b/pkg/sbom/io/encode.go
@@ -200,6 +200,7 @@ func (e *Encoder) encodePackages(parent *core.Component, result types.Result) {
 	components := make(map[string]*core.Component, len(result.Packages))
 	// PkgID => Package Component
 	dependencies := make(map[string]*core.Component, len(result.Packages))
+	var hasRoot bool
 	for i, pkg := range result.Packages {
 		pkgID := lo.Ternary(pkg.ID == "", fmt.Sprintf("%s@%s", pkg.Name, pkg.Version), pkg.ID)
 		result.Packages[i].ID = pkgID
@@ -219,6 +220,12 @@ func (e *Encoder) encodePackages(parent *core.Component, result types.Result) {
 		if vv := vulns[pkg.Identifier.UID]; vv != nil {
 			e.bom.AddVulnerabilities(c, vv)
 		}
+
+		// Check if the project has a root dependency
+		// TODO: Ideally, all projects should have a root dependency.
+		if pkg.Relationship == ftypes.RelationshipRoot {
+			hasRoot = true
+		}
 	}
 
 	// Build a dependency graph between packages
@@ -226,7 +233,7 @@ func (e *Encoder) encodePackages(parent *core.Component, result types.Result) {
 		c := components[pkg.Identifier.UID]
 
 		// Add a relationship between the parent and the package if needed
-		if e.belongToParent(pkg, parents) {
+		if e.belongToParent(pkg, parents, hasRoot) {
 			e.bom.AddRelationship(parent, c, core.RelationshipContains)
 		}
 
@@ -403,16 +410,15 @@ func (*Encoder) vulnerability(vuln types.DetectedVulnerability) core.Vulnerabili
 }
 
 // belongToParent determines if a package should be directly included in the parent based on its relationship and dependencies.
-func (*Encoder) belongToParent(pkg ftypes.Package, parents map[string]ftypes.Packages) bool {
+func (*Encoder) belongToParent(pkg ftypes.Package, parents map[string]ftypes.Packages, hasRoot bool) bool {
 	// Case 1: Relationship: known , DependsOn: known
 	//         Packages with no parent are included in the parent
 	//         - Relationship:
 	//           - Root: true (it doesn't have a parent)
 	//           - Workspace: false (it always has a parent)
 	//           - Direct:
-	//             - Under Root or Workspace: false (it always has a parent)
-	//             - No parents: true (e.g., package-lock.json)
-	//             - There are parents, but they are not Root or Workspace: true (when indirect dependency was installed manually. cf. https://github.com/aquasecurity/trivy/issues/8488)
+	//             - No root dependency in the project: true (e.g., poetry.lock)
+	//             - Otherwise: false (Direct dependencies should belong to the root/workspace)
 	//           - Indirect: false (it always has a parent)
 	// Case 2: Relationship: unknown, DependsOn: unknown (e.g., conan lockfile v2)
 	//         All packages are included in the parent
@@ -421,16 +427,10 @@ func (*Encoder) belongToParent(pkg ftypes.Package, parents map[string]ftypes.Pac
 	// Case 4: Relationship: unknown, DependsOn: known (e.g., GoBinaries, OS packages)
 	//         - Packages with parents: false. These packages are included in the packages from `parents` (e.g. GoBinaries deps and root package).
 	//         - Packages without parents: true. These packages are included in the parent (e.g. OS packages without parents).
-	pkgParents := parents[pkg.ID]
-	if pkg.Relationship != ftypes.RelationshipDirect {
-		return len(pkgParents) == 0
+	if pkg.Relationship == ftypes.RelationshipDirect {
+		return !hasRoot
 	}
-
-	_, found := lo.Find(pkgParents, func(pkg ftypes.Package) bool {
-		return pkg.Relationship == ftypes.RelationshipRoot || pkg.Relationship == ftypes.RelationshipWorkspace
-	})
-
-	return !found
+	return len(parents[pkg.ID]) == 0
 }
 
 func filterProperties(props []core.Property) []core.Property {
```

**Comment by DmitriyLewen** [comment]
This seems better to me than my solution. Thanks!

**Review by knqyf263 — APPROVED** [review]

File: pkg/sbom/io/encode.go [hunk 1]
```diff
@@ -226,7 +233,7 @@ func (e *Encoder) encodePackages(parent *core.Component, result types.Result) {
 		c := components[pkg.Identifier.UID]
 
 		// Add a relationship between the parent and the package if needed
-		if e.belongToParent(pkg, parents) {
+		if e.belongToParent(pkg, parents, hasRoot) {
```
Comment (nikpivkin) [inline pkg/sbom/io/encode.go:236]: Does the root package always come first? If the first package is not the root package, then belongToParent will return false. Then the second package will be the root package and for all subsequent ones belongToParent will return true. Just wondering.

Comment (DmitriyLewen) [reply pkg/sbom/io/encode.go:236]: rootRelationship is always first - https://github.com/aquasecurity/trivy/blob/d622ca2b1fe40a0eb588478ba9e15d3bd8471a78/pkg/fanal/types/package.go#L243

Comment (knqyf263) [reply pkg/sbom/io/encode.go:236]: Oh, it is not my suggestion.
https://github.com/aquasecurity/trivy/pull/8489#pullrequestreview-2660248630

I suggested adding `hasRoot = true` in line 203-222.

Comment (knqyf263) [reply pkg/sbom/io/encode.go:236]: Hmm. I checked the change again. Dmitriy applied my proposal correctly.
https://github.com/aquasecurity/trivy/blob/a4009f62fdcc4ce0170feaea7ffc58a92d4a87cb/pkg/sbom/io/encode.go/#L208-L212

Comment (knqyf263) [reply pkg/sbom/io/encode.go:236]: I guess @nikpivkin just got confused as we iterate packages twice. `hasRoot` is set to true in the first loop.

Comment (knqyf263) [reply pkg/sbom/io/encode.go:236]: In the GitHub diff, it looks like there is only one loop.

CleanShot 2025-03-05 at 14 26 45

Comment (knqyf263) [reply pkg/sbom/io/encode.go:236]: because 217-232 lines are folded

Comment (knqyf263) [reply pkg/sbom/io/encode.go:236]: Actually, same here. I left the [comment](https://github.com/aquasecurity/trivy/pull/8489/files#r1981114010) since the github view confused me and I also thought Dmitriy mistakenly added `hasRoot = true` to the first loop 😄

Comment (knqyf263) [reply pkg/sbom/io/encode.go:236]: Dmitriy just did a great job 👍

Comment (DmitriyLewen) [reply pkg/sbom/io/encode.go:236]: The code on GitHub confused me too, so I started looking for confirmation in sorting, although I checked it when I embedded the code 😄
