### PR TITLE
fix(secret): Alibaba AccessKey ID

### LINKED ISSUE #3065: alibaba-access-key-id secret detection triggers on go(.work).sum with specific hash in it
## Checklist
- [x] I've read [the documentation regarding wrong detection](https://aquasecurity.github.io/trivy/latest/community/contribute/issue/#wrong-detection).
- [x] I've confirmed that a security advisory in data sources was correct.
    - Run Trivy with `-f json` that shows data sources and make sure that the security advisory is correct.

## Description
The secret scanning rule searching for an Alibaba Access Key ID can trigger on a go(.work).sum with specific hashes in them (in this case: v1.2.2 of go-logr/stdr).

This is due to the generic Regex rule used for detection:
https://github.com/aquasecurity/trivy/blob/3cd88abec5e1a028a0b0342f03ffa71acbb20c37/pkg/fanal/secret/builtin-rules.go#L273-L278

which triggers on the offending hash containing LTAI somewhere in the middle:
```
github.com/go-logr/stdr v1.2.2 h1:hSWxHoqTgW2S2qGc0LTAI563KZ5YKYRhT3MFKZMbjag=
```

## JSON Output of run with `-debug`:

```
trivy fs -f json --debug go.work.sum
2022-10-22T15:48:45.341+0200	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-10-22T15:48:45.352+0200	DEBUG	cache dir:  /home/nils/.cache/trivy
2022-10-22T15:48:45.353+0200	DEBUG	DB update was skipped because the local DB is the latest
2022-10-22T15:48:45.353+0200	DEBUG	DB Schema: 2, UpdatedAt: 2022-10-22 12:06:57.104657491 +0000 UTC, NextUpdate: 2022-10-22 18:06:57.104657191 +0000 UTC, DownloadedAt: 2022-10-22 13:30:11.468966261 +0000 UTC
2022-10-22T15:48:45.353+0200	INFO	Vulnerability scanning is enabled
2022-10-22T15:48:45.353+0200	DEBUG	Vulnerability type:  [os library]
2022-10-22T15:48:45.353+0200	INFO	Secret scanning is enabled
2022-10-22T15:48:45.353+0200	INFO	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-10-22T15:48:45.353+0200	INFO	Please see also https://aquasecurity.github.io/trivy/v0.32/docs/secret/scanning/#recommendation for faster secret detection
2022-10-22T15:48:45.353+0200	DEBUG	No secret config detected: trivy-secret.yaml
2022-10-22T15:48:45.382+0200	DEBUG	OS is not detected.
2022-10-22T15:48:45.382+0200	DEBUG	Detected OS: unknown
2022-10-22T15:48:45.382+0200	INFO	Number of language-specific files: 0
2022-10-22T15:48:45.382+0200	DEBUG	Secret file: go.work.sum
{
  "SchemaVersion": 2,
  "ArtifactName": "go.work.sum",
  "ArtifactType": "filesystem",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
    {
      "Target": "go.work.sum",
      "Class": "secret",
      "Secrets": [
        {
          "RuleID": "alibaba-access-key-id",
          "Category": "Alibaba",
          "Severity": "HIGH",
          "Title": "Alibaba AccessKey ID",
          "StartLine": 185,
          "EndLine": 185,
          "Code": {
            "Lines": [
              {
                "Number": 183,
                "Content": "github.com/go-logfmt/logfmt v0.5.0 h1:TrB8swr/68K7m9CcGut2g3UOihhbcbiMAYiuTXdEih4=",
                "IsCause": false,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "github.com/go-logfmt/logfmt v0.5.0 h1:TrB8swr/68K7m9CcGut2g3UOihhbcbiMAYiuTXdEih4=",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 184,
                "Content": "github.com/go-logr/logr v1.2.2/go.mod h1:jdQByPbusPIv2/zmleS9BjJVeZ6kBagPoEUsqbVz/1A=",
                "IsCause": false,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "github.com/go-logr/logr v1.2.2/go.mod h1:jdQByPbusPIv2/zmleS9BjJVeZ6kBagPoEUsqbVz/1A=",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 185,
                "Content": "github.com/go-logr/stdr v1.2.2 h1:hSWxHoqTgW2S2qGc0************************ag=",
                "IsCause": true,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "github.com/go-logr/stdr v1.2.2 h1:hSWxHoqTgW2S2qGc0************************ag=",
                "FirstCause": true,
                "LastCause": true
              },
              {
                "Number": 186,
                "Content": "github.com/go-logr/stdr v1.2.2/go.mod h1:mMo/vtBO5dYbehREoey6XUKy/eSumjCCveDpRre4VKE=",
                "IsCause": false,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "github.com/go-logr/stdr v1.2.2/go.mod h1:mMo/vtBO5dYbehREoey6XUKy/eSumjCCveDpRre4VKE=",
                "FirstCause": false,
                "LastCause": false
              }
            ]
          },
          "Match": "github.com/go-logr/stdr v1.2.2 h1:hSWxHoqTgW2S2qGc0************************ag=",
          "Layer": {}
        }
      ]
    }
  ]
}

```

## Output of `trivy -v`:
```
Version: 0.32.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-10-22 12:06:57.104657491 +0000 UTC
  NextUpdate: 2022-10-22 18:06:57.104657191 +0000 UTC
  DownloadedAt: 2022-10-22 13:30:11.468966261 +0000 UTC
```

## Additional details (base image name, container registry info...):
Offending line:
```
github.com/go-logr/stdr v1.2.2 h1:hSWxHoqTgW2S2qGc0LTAI563KZ5YKYRhT3MFKZMbjag=
github.com/go-logr/stdr v1.2.2/go.mod h1:mMo/vtBO5dYbehREoey6XUKy/eSumjCCveDpRre4VKE=
```

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Currently `Alibaba AccessKey ID` can be found in line with extra characters before or after secret template.
e.g.: `asdLTAI1234567890ABCDEFG123` or `LTAI1234567890ABCDEFG123asd`
Fix this.

## Related issues
- Close #3065

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/secret/builtin-rules.go [hunk 1]
```diff
@@ -270,12 +270,13 @@ var builtinRules = []Rule{
...
-		Category: CategoryAlibaba,
-		Title:    "Alibaba AccessKey ID",
-		Severity: "HIGH",
-		Regex:    MustCompile(`(LTAI)(?i)[a-z0-9]{20}`),
-		Keywords: []string{"LTAI"},
+		ID:              "alibaba-access-key-id",
+		Category:        CategoryAlibaba,
+		Title:           "Alibaba AccessKey ID",
+		Severity:        "HIGH",
+		Regex:           MustCompile(`([^0-9a-z]|^)(?P<secret>(LTAI)(?i)[a-z0-9]{20})([^0-9a-z]|$)`),
```
Comment (knqyf263) [inline pkg/fanal/secret/builtin-rules.go:277]: I see `^0-9a-z` is characters other than digits and alphabetic characters, but what does `|^` mean?

Comment (DmitriyLewen) [reply pkg/fanal/secret/builtin-rules.go:277]: `|^` is the start line.
if the file only contains a secret, Trivy will not find that secret.
for example: https://regex101.com/r/v9TsI0/1.

same for `|$`

Comment (knqyf263) [reply pkg/fanal/secret/builtin-rules.go:277]: Oh, I got it. Thanks.

**Review by knqyf263 — APPROVED** [review]
