### PR TITLE
fix(java): exclude dev dependencies in gradle lockfile

### LINKED ISSUE #8755: fix(gradle): exclude development dependencies
## Description
Dependencies only with included in `testCompileClasspath` and `testRuntimeClasspath` should be marked as development dependencies and only included when --include-dev-deps is specified. [The document](https://trivy.dev/latest/docs/coverage/language/java/) also needs to be fixed.

```
junit:junit:4.13.2=testCompileClasspath,testRuntimeClasspath
org.apache.commons:commons-lang3:3.12.0=compileClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
org.hamcrest:hamcrest-core:1.3=testCompileClasspath,testRuntimeClasspath
empty=annotationProcessor,testAnnotationProcessor
```

### PR DESCRIPTION
**Pull request by sneaky-potato**
## Description
We need to mark development dependencies while scanning gradle lockfiles so that they are not included in the final scans

## Related issues
- Close #8755 

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
Thanks for your contribution. Can you please add a test in https://github.com/aquasecurity/trivy/blob/60fa45623a2b4c4aab14493c846d1f31f590d3ef/pkg/dependency/parser/gradle/lockfile/parse_test.go?

File: pkg/dependency/parser/gradle/lockfile/parse.go [hunk 1]
```diff
@@ -35,10 +35,23 @@ func (Parser) Parse(r xio.ReadSeekerAt) ([]ftypes.Package, []ftypes.Dependency,
 
 		name := strings.Join(dep[:2], ":")
 		version := strings.Split(dep[2], "=")[0] // remove classPaths
+
```
Comment (knqyf263) [inline pkg/dependency/parser/gradle/lockfile/parse.go:38]: Can you please see if `strings.Cut` works in this case?

```suggestion
		version, classPathsString, _ := strings.Cut(dep[2], "=")
```

Comment (sneaky-potato) [reply pkg/dependency/parser/gradle/lockfile/parse.go]: Right, refactored in latest commit, thanks for this suggestion

**Comment by DmitriyLewen** [comment]
@sneaky-potato thanks for your work!

Do you have time to create one more PR with update for docs.
We write information about support of `--include-dev-deps` flag for languages (e.g. for [yarn](https://trivy.dev/latest/docs/coverage/language/nodejs/#package-relationships), [pnpm](https://trivy.dev/latest/docs/coverage/language/nodejs/#lock-file-v9-version)) 
If you don't have time - simple tell me, i will do that myself.

Regards, Dmitriy

**Comment by sneaky-potato** [comment]
Hi @DmitriyLewen, sure I can update the docs.
Do you mean to update the information about the `--include-dev-deps` flag when using the cli?
I can see the following description on using the `--help` flag
```console
$ ./trivy fs . --help | grep include-dev-deps
      --include-dev-deps            include development dependencies in the report (supported: npm, yarn)
```

**Comment by DmitriyLewen** [comment]
> Shall I put information about the --include-dev-deps flag under Gradle.lock section

Absolutely right.

**Comment by sneaky-potato** [comment]
Hi please find the PR for updating docs here: #8830
