### PR TITLE
fix(python): impove package name normalization 

### LINKED ISSUE #9279: bug(python): Trivy uses non-normalized pkg name in `*.dist-info` dir name
## Description 
Trivy uses non-normalized pkg name in `*.dist-info` dir name.
That is why Trivy can't detect licenses for packages with `-`.

e.g.:`typing-inspection` pkg => `typing_inspection-0.4.1.dist-info`.

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
This PR normalizes Python package names according to PEP-0503 specification instead of PEP-0426, and fixes dist-info directory name generation to properly handle package names with special characters.

## Reason

  The existing implementation followed PEP-0426 for package name normalization, but Python packaging has evolved to use PEP-0503 for normalized names. Additionally, the dist-info directory name generation was not properly handling
  package names containing -, _, or . characters, causing license information lookup failures for packages with these characters in their names.

## Improvements
- Updated normalization standard: Switched from PEP-0426 to PEP-0503 for package name normalization
- Improved regex-based replacement: Replaced multiple string replacements with a single regex that handles consecutive runs of -, _, or . characters more efficiently
- Fixed dist-info directory lookup: Added proper normalization and conversion for dist-info directory names (normalize then replace - with _)
 - Enhanced test coverage: Added test case for packages with consecutive special characters (foo--bar__baz)
- Better license detection: Fixed license information retrieval for packages like annotated-types that use underscores in their dist-info directory names

## Example with fix License detection
before (Trivy uses `typing-inspection-0.4.1.dist-info` dir)
```bash
➜ VIRTUAL_ENV=./.venv trivy -q fs ./requirements.txt -f json --list-all-pkgs | jq '.Results[].Packages[] | select (.Name=="typing-inspection") | .Licenses' 
null
```
after (Trivy uses `typing_inspection-0.4.1.dist-info` dir)
```bash
➜ VIRTUAL_ENV=./.venv ./trivy -q fs ./requirements.txt -f json --list-all-pkgs | jq '.Results[].Packages[] | select (.Name=="typing-inspection") | .Licenses'
[
  "MIT"
]
``` 

## Related issues
- Close #9279

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/analyzer/language/python/pip/pip.go [hunk 1]
```diff
@@ -109,19 +109,14 @@ func (a pipLibraryAnalyzer) Version() int {
...
 // pkgLicense parses `METADATA` pkg file to look for licenses
 func (a pipLibraryAnalyzer) pkgLicense(pkgName, pkgVer, spDir string) []string {
-	// METADATA path is `**/site-packages/<pkg_name>-<pkg_version>.dist-info/METADATA`
-	pkgDir := fmt.Sprintf("%s-%s.dist-info", pkgName, pkgVer)
-	metadataPath := filepath.Join(spDir, pkgDir, "METADATA")
-	metadataFile, err := os.Open(metadataPath)
-	if os.IsNotExist(err) {
-		a.logger.Debug("No package metadata found", log.String("site-packages", pkgDir),
-			log.String("name", pkgName), log.String("version", pkgVer))
+	metadataFile := a.metadataFile(pkgName, pkgVer, spDir)
```
Comment (knqyf263) [inline pkg/fanal/analyzer/language/python/pip/pip.go:112]: Is this file closed somewhere? 
`metadataFile.Close()`.

Comment (DmitriyLewen) [reply pkg/fanal/analyzer/language/python/pip/pip.go:112]: Nice catch!
added in https://github.com/aquasecurity/trivy/pull/9290/commits/4ce96c70c5587bbd9631a7d08edea4cb9e302753
