### PR TITLE
fix(cli): don't use allow values for `--compliance` flag

### LINKED ISSUE #8876: bug(cli): unable to use custom compliance files with `--compliance` flag
## Description
Docs says that users can use custom compliance reports - https://trivy.dev/latest/docs/compliance/compliance/#custom-compliance.
Trivy also has logic for that:
https://github.com/aquasecurity/trivy/blob/243e5a3af99e7f539d843a622ee85d3749267541/pkg/compliance/spec/compliance.go#L91-L96

But we use the `Value` field, so users can't use filepath for the `--compliance` flag:
```
2025-05-15T18:29:02+06:00	FATAL	Fatal error
  - flag error:
    github.com/aquasecurity/trivy/pkg/commands.NewImageCommand.func2
        /Users/dmitriy/work/aquasecurity/trivy/pkg/commands/app.go:325
  - unable to parse flags:
    github.com/aquasecurity/trivy/pkg/flag.(*Flags).ToOptions
        /Users/dmitriy/work/aquasecurity/trivy/pkg/flag/options.go:652
  - unable to parse flag:
    github.com/aquasecurity/trivy/pkg/flag.parseFlags
        /Users/dmitriy/work/aquasecurity/trivy/pkg/flag/options.go:670
  - invalid argument "@/Users/dmitriy/work/tmp/8875/compliance-custom.yaml" for "--compliance" flag: must be one of ["docker-cis-1.6.0"]:
    github.com/aquasecurity/trivy/pkg/flag.(*Flag[...]).Parse
        /Users/dmitriy/work/aquasecurity/trivy/pkg/flag/options.go:119
```

### Affected modes:
- `image` mode. Allow only `docker-cis-1.6.0` value.
   https://github.com/aquasecurity/trivy/blob/6562082e280a9df6199892927f2e3f7dc8f0c8ce/pkg/commands/app.go#L255
- `k8s` mode. Allow only `k8s-nsa-1.0`, `k8s-cis-1.23`, `eks-cis-1.4`, `rke2-cis-1.24`,  `k8s-pss-baseline-0.1`,  `k8s-pss-restricted-0.1`:
   https://github.com/aquasecurity/trivy/blob/6562082e280a9df6199892927f2e3f7dc8f0c8ce/pkg/commands/app.go#L999-L1006

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
We don't need to use allowed values for `--complience` flag, because in this case users can't use custom compliance.
See more info in #8876.

So this PR removes allowed values and added built-in compiance's in flag description:
```
➜  ./trivy image --help | grep "\-\-compliance"   
      --compliance string          compliance report to generate (built-in compliance's: docker-cis-1.6.0)
➜  ./trivy k8s --help | grep "\-\-compliance" -A 7
      --compliance string          compliance report to generate
                                   Built-in compliance's:
                                     - k8s-nsa-1.0
                                     - k8s-cis-1.23
                                     - eks-cis-1.4
                                     - rke2-cis-1.24
                                     - k8s-pss-baseline-0.1
                                     - k8s-pss-restricted-0.1

```

## Related issues
- Close #8876

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by afdesk — APPROVED** [review]
LGTM

File: pkg/types/report.go [hunk 1]
```diff
@@ -74,6 +74,15 @@ const (
 	FormatCosignVuln Format = "cosign-vuln"
 )
 
+var BuildInK8sCompiances = []string{
```
Comment (knqyf263) [inline pkg/types/report.go:77]: nit
```suggestion
var BuiltInK8sCompiances = []string{
```

**Review by knqyf263 — APPROVED** [review]
LGTM

File: pkg/types/report.go (hunk 1 above)
Comment (DmitriyLewen) [reply pkg/types/report.go]: Thanks! fixed in https://github.com/aquasecurity/trivy/pull/8881/commits/94175bd699dcaad7cc537ca97f6f59d92681fd2a
