### PR TITLE
fix(repo): `git clone` output to Stderr

### LINKED ISSUE #7547: fix(repo): git CLI output mangles stdout
## Description
When scanning a git repository with `trivy repo`, the progress of `git clone` is written to standard output, resulting in a parse error.

```bash
❯ trivy repository --format cyclonedx --scanners vuln file://. --debug | jq
2024-09-18T15:26:30-07:00	DEBUG	Cache dir	dir="/Users/patcal04/Library/Caches/trivy"
2024-09-18T15:26:30-07:00	DEBUG	Parsed severities	severities=[UNKNOWN LOW MEDIUM HIGH CRITICAL]
2024-09-18T15:26:30-07:00	DEBUG	Ignore statuses	statuses=[]
2024-09-18T15:26:30-07:00	DEBUG	DB update was skipped because the local DB is the latest
2024-09-18T15:26:30-07:00	DEBUG	DB info	schema=2 updated_at=2024-09-18T18:13:21.187484554Z next_update=2024-09-19T00:13:21.187484163Z downloaded_at=2024-09-18T20:24:17.597058Z
2024-09-18T15:26:30-07:00	INFO	Vulnerability scanning is enabled
2024-09-18T15:26:30-07:00	DEBUG	Vulnerability type	type=[library]
2024-09-18T15:26:30-07:00	DEBUG	Enabling misconfiguration scanners	scanners=[azure-arm cloudformation dockerfile helm kubernetes terraform terraformplan-json terraformplan-snapshot]
2024-09-18T15:26:30-07:00	DEBUG	Initializing scan cache...	type="memory"
jq: parse error: Invalid numeric literal at line 1, column 12
```

It should be `os.Stderr`.
https://github.com/aquasecurity/trivy/blob/dbd2dd60604fbcb5456a864a37d9c1b5a9e6f231/pkg/fanal/artifact/repo/git.go#L131

### Discussed in https://github.com/aquasecurity/trivy/discussions/7544

### PR DESCRIPTION
**Pull request by dangogh**
## Description

This ensures that `git clone` output is directed to `os.Stderr` instead of `os.Stdout`.  Test added to demonstrate that stdout is empty after clone.

## Related issues
- Close #7547 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [x] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by dangogh** [comment]
NOTE: currently unable to run `mage test:unit` due to an error: ```../../wasm/sdk.go:146:10: cannot use uintptr(size) (value of type uintptr) as int value in assignment```.    Probably something due to my macbook pro M3 installlation.  I'll bring up in discussions tomorrow if unable to resolve that.

File: pkg/fanal/artifact/repo/git_test.go [hunk 1]
```diff
@@ -36,6 +38,18 @@ func setupGitRepository(t *testing.T, repo, dir string) (*httptest.Server, *git.
 	return gs, r
 }
 
+// wrapNewArtifact captures stdout to test that `git clone` output is not mixed with formatted output
+func wrapNewArtifact(target string, c cache.ArtifactCache, fs *walker.FS, opts artifact.Option) (func(), []byte, error) {
+	orig := os.Stdout
+	r, w, _ := os.Pipe()
+	os.Stdout = w
```
Comment (knqyf263) [inline pkg/fanal/artifact/repo/git_test.go:45]: Overriding os.Stdout could cause a problem if this test is run in parallel.

**Review by knqyf263 — COMMENTED** [review]
It seems that there's no simple way to add a test at the moment. Please feel free to revert it so we can merge this fix soon.

File: pkg/fanal/artifact/repo/git_test.go (hunk 1 above)
Comment (dangogh) [reply pkg/fanal/artifact/repo/git_test.go]: agreed -- reverted the test

**Review by knqyf263 — APPROVED** [review]
Thanks

**Comment by dangogh** [comment]
Need some help here.  Integration tests failed with this: 
```
* remote error: GET https://ghcr.io/v2/aquasecurity/trivy-test-images/manifests/sha256:460fdaba6a3c934072bd8a6e74be574085a573d2cc920abaf470db0c43c7fffe: TOOMANYREQUESTS: retry-after: 281.482µs, allowed: 44000/minute
```
and it's not clear to me if I can simply restart the test.

**Comment by knqyf263** [comment]
Yes, it's [a known issue](https://github.com/aquasecurity/trivy/discussions/7538). We've raised an issue, but we haven't heard back yet.
https://github.com/orgs/community/discussions/139074
