### PR TITLE
fix(sbom): use `purl` for `bitnami` pkg names

### LINKED ISSUE #6981: fix(bitnami): use `purl` to detect `bitnami` pkg name
## Description
We use [package name field](https://github.com/aquasecurity/trivy/blob/c3192f061d7e84eaf38df8df7c879dc00b4ca137/pkg/sbom/core/bom.go#L96-L97) instead of purl to detect package name to avoid case-insensitive issues:
https://github.com/aquasecurity/trivy/blob/c3192f061d7e84eaf38df8df7c879dc00b4ca137/pkg/sbom/io/decode.go#L249-L266

But `bitnami` is more focused on `purl`.
So After discussion we decided to use `purl` for `bitnami` packages.
See https://github.com/aquasecurity/trivy/discussions/6954#discussioncomment-9826703

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
See #6981

## Related issues
- Close #6981

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/sbom/io/decode.go [hunk 1]
```diff
@@ -256,6 +256,13 @@ func (m *Decoder) pkgName(pkg *ftypes.Package, c *core.Component) string {
 		return pkg.Name
 	}
 
+	// Bitnami used different pkg.Name and the name from PURL.
```
Comment (knqyf263) [inline pkg/sbom/io/decode.go:259]: Since @fmulero mentioned it would be rotated in 6-9 months, how about adding a comment like this?

```suggestion
	// TODO(backward compatibility): Remove after 03/2025
	// Bitnami used different pkg.Name and the name from PURL.
```

Comment (DmitriyLewen) [reply pkg/sbom/io/decode.go:260]: Good idea! Added in https://github.com/aquasecurity/trivy/pull/6982/commits/7e76a4b78a3b56f782f485727c544af283f7663f

**Review by knqyf263 — APPROVED** [review]
