### PR TITLE
fix(nodejs): correctly parse `packages` array of `bun.lock` file

### LINKED ISSUE #8995: bug(bun): Trivy can't parse `bun.lock` unless package dependency is array element 3
## Description
We added support for `bun.lock` files - #8851 + #8897 
We thought that `dependency` struct is always 3 element of `package` array (see https://github.com/aquasecurity/trivy/pull/8851#discussion_r2091603377).

But it looks like `dependency` may be 2 element:
- https://bun.sh/blog/bun-lock-text-lockfile#:~:text=%22uWebSocket.js%22:%20%5B-,%22uWebSockets.js@github:uNetworking/uWebSockets.js%236609a88%22%2C%20%7B%7D%2C%20%22uNetworking%2DuWebSockets.js%2D6609a88%22%5D%2C,-%7D
- `"spdx-satisfies": ["spdx-satisfies@github:clearlydefined/spdx-satisfies.js#b9571c0", { "dependencies": { "spdx-compare": "^1.0.0", "spdx-expression-parse": "^3.0.0", "spdx-ranges": "^2.0.0" } }, "clearlydefined-spdx-satisfies.js-b9571c0"],` - (https://github.com/aquasecurity/trivy/discussions/8994#:~:text=%22spdx%2Dsatisfies%22:%20%5B%22spdx%2Dsatisfies@github:clearlydefined/spdx%2Dsatisfies.js%23b9571c0%22%2C%20%7B%20%22dependencies%22:%20%7B%20%22spdx%2Dcompare%22:%20%22%5E1.0.0%22%2C%20%22spdx%2Dexpression%2Dparse%22:%20%22%5E3.0.0%22%2C%20%22spdx%2Dranges%22:%20%22%5E2.0.0%22%20%7D%20%7D%2C%20%22clearlydefined%2Dspdx%2Dsatisfies.js%2Db9571c0%22%5D%2C)

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
`packages` array can use a different structure - https://bun.sh/reference/bun/BunLockFilePackageArray

So we need to parse `dependencies` from 2 or 3 elements of `package` array to avoid errors and missing dependencies

## Related issues
- Close #8995

## Related PRs
- [x] #8851

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/dependency/parser/nodejs/bun/parse.go [hunk 1]
```diff
@@ -58,12 +58,23 @@ func (p *ParsedPackage) UnmarshalJSON(data []byte) error {
...
+	// [pkg: string, info: BunLockFilePackageInfo, bunTag: string]
+	// [pkg: string, info: Pick<BunLockFileBasePackageInfo, "bin" | "binDir">]
+	// [pkg: string, registry: string, info: BunLockFilePackageInfo, integrity: string]
+	// cf.https://github.com/oven-sh/bun/blob/61e03a275885b9b48f7a28f6dfbbbe1156eedca6/packages/bun-types/bun.d.ts#L7745-L7755
+	metaRaw := raw[1]
+	if len(raw) > 3 {
+		metaRaw = raw[2]
 	}
-	return nil
+	return json.Unmarshal(metaRaw, &p.Meta)
```
Comment (connerlphillippi) [inline pkg/dependency/parser/nodejs/bun/parse.go:77]: note that bun.lock uses JSONC, which means it may have trailing commas and comments in the file. comments are unlikely, but commas are more likely as bun.lock does generate them.

Comment (DmitriyLewen) [reply pkg/dependency/parser/nodejs/bun/parse.go:77]: Hello @connerlphillippi 
Thanks!

We already found that and write unmarshaler for JSONC - https://github.com/aquasecurity/trivy/pull/8862
