### PR TITLE
fix(server): secrets inspectation for the config analyzer in client server mode

### LINKED ISSUE #6742: Trivy client server mode not scanning secrets exposed in image, Trivy standalone works
when scanning image for secret (in config) in standalone mode, I do get secret finding, for example:
```sh
trivy image gsingh737/nginxwithsecret:v1 --image-config-scanners secret --scanners secret

2024-05-22T08:50:16+03:00	INFO	Container image config scanners	scanners=[secret]
2024-05-22T08:50:16+03:00	INFO	Secret scanning is enabled
2024-05-22T08:50:16+03:00	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-05-22T08:50:16+03:00	INFO	Please see also https://aquasecurity.github.io/trivy/v0.51/docs/scanner/secret/#recommendation for faster secret detection

gsingh737/nginxwithsecret:v1 (secrets)

Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 2)

CRITICAL: AWS (aws-secret-access-key)
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Secret Access Key
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 gsingh737/nginxwithsecret:v1:132
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 130     "NJS_VERSION=0.8.2",
 131     "PKG_RELEASE=1~bookworm",
 132 [   "AWS_SECRET_ACCESS_KEY=****************************************"
 133     ],
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


CRITICAL: AWS (aws-secret-access-key)
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
AWS Secret Access Key
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 gsingh737/nginxwithsecret:v1:94
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  92     {
  93     "created": "2023-10-24T22:44:45Z",
  94 [   "created_by": "ENV AWS_SECRET_ACCESS_KEY=****************************************",
  95     "comment": "buildkit.dockerfile.v0",
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```
 
however whenrunning same in client/server mode no results appear, example:
```sh
trivy image gsingh737/nginxwithsecret:v1 --image-config-scanners secret --scanners secret --server http://0.0.0.0:8081

2024-05-22T09:17:53+03:00	INFO	Container image config scanners	scanners=[secret]
2024-05-22T09:17:53+03:00	INFO	Secret scanning is enabled
2024-05-22T09:17:53+03:00	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-05-22T09:17:53+03:00	INFO	Please see also https://aquasecurity.github.io/trivy/v0.51/docs/scanner/secret/#recommendation for faster secret detection
 ```

### PR DESCRIPTION
**Pull request by iamtraining**
fix secrets inspectation for the config analyzer in client server mode

## Description
secrets that were found when inspecting the config in client/server mode are not saved in the remote cache
 func (a Artifact) inspectConfig( ... )  
the secret field for PutArtifact is not sent to the server so these secrets are lost  
before  
`{ "SchemaVersion":1, "Architecture":"amd64", "Created":"2023-10-24T22:44:45Z", "DockerVersion":"", "OS":"linux" }`  
after this huge and massive fix  
`{"SchemaVersion":1,"Architecture":"amd64","Created":"2023-10-24T22:44:45Z","DockerVersion":"","OS":"linux","Secret":{"FilePath":"config.json","Findings":[{ ... }]}}`

## Related issues
- Close #6742 

## Checklist
- [ ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [ ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/rpc/convert.go [hunk 1]
```diff
@@ -1015,3 +1017,25 @@ func ConvertFromDeleteBlobsRequest(deleteBlobsRequest *cache.DeleteBlobsRequest)
 	}
 	return deleteBlobsRequest.GetBlobIds()
 }
+
+// ConvertFromRPCSecret converts common.Secret to fanal.Secret
+func ConvertFromRPCSecret(rpcSecret *common.Secret) *ftypes.Secret {
```
Comment (DmitriyLewen) [inline pkg/rpc/convert.go:1022]: same for ConvertFromRPCSecrets

**Review by DmitriyLewen — APPROVED** [review]
