### PR TITLE
fix(report): ensure json report got a final new line

### LINKED ISSUE #1787: The output file of 'trivy image -o output.json' lacks a final newline
When using `trivy image -o output.json -f json foo:latest`, the output file lacks a final newline.

This is not [POSIX-compliant](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206), and causes issues when processing the file.

Can you please add the final newline?

### PR DESCRIPTION
**Pull request by cpontvieux-systra**
## Related issues
- Close #1787

## Checklist
- [X] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md) to this repository.
- [X] I've followed the [conventions](https://github.com/aquasecurity/trivy/blob/main/CONTRIBUTING.md#title) in the PR title.
- [X] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/report/json.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ func (jw JSONWriter) Write(report types.Report) error {
 		return xerrors.Errorf("failed to marshal json: %w", err)
 	}
 
-	if _, err = fmt.Fprint(jw.Output, string(output)); err != nil {
+	if _, err = fmt.Fprint(jw.Output, string(output) + "\n"); err != nil {
```
Comment (knqyf263) [inline pkg/report/json.go:25]: How about Fprintln?
https://pkg.go.dev/fmt#Fprintln

Comment (cpontvieux-systra) [reply pkg/report/json.go]: Good idea

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks!
