### PR TITLE
fix(spdx): add workaround for no src packages

### LINKED ISSUE #3975: SPDX support for VM images
# Description
Generate SPDX reports of VM images like container images

```
$ trivy vm --format spdx ubuntu.vmdk
```

### PR DESCRIPTION
**Pull request by masahiro331**
## Description

The existing implementation already supported SPDX.
Fixed a bug in SourceInfo information in some packages as an implementation of SPDX.

And, support cyclonedx sbom for vm scan.

## Related issues
- Close #3975 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/sbom/spdx/marshal.go [hunk 1]
```diff
@@ -282,7 +282,7 @@ func (m *Marshaler) pkgToSpdxPackage(t, pkgDownloadLocation string, class types.
 	}
 
 	var pkgSrcInfo string
-	if class == types.ClassOSPkg {
+	if class == types.ClassOSPkg && pkg.SrcName != "" {
```
Comment (knqyf263) [inline pkg/sbom/spdx/marshal.go:285]: Would you elaborate on that?

Comment (masahiro331) [reply pkg/sbom/spdx/marshal.go:285]: Some package does not have srcName.
e.g. 

```
        {
          "ID": "gpg-pubkey@c87f5b1a-593863f8.",
          "Name": "gpg-pubkey",
          "Version": "c87f5b1a",
          "Release": "593863f8",
          "Arch": "None",
          "Licenses": [
            "pubkey"
          ],
          "Layer": {}
        },
```

In this case, spdx output empty SourceInfo.

```
##### Package: gpg-pubkey

PackageName: gpg-pubkey
SPDXID: SPDXRef-Package-6c5513710c857f3f
PackageVersion: c87f5b1a-593863f8
PackageDownloadLocation: NONE
FilesAnalyzed: false
PackageSourceInfo: built package from: 
PackageLicenseConcluded: pubkey
PackageLicenseDeclared: pubkey
ExternalRef: PACKAGE-MANAGER purl pkg:rpm/amazon/gpg-pubkey@c87f5b1a-593863f8?arch=None&distro=amazon-2%20%28Karoo%29
PackageAttributionText: PkgID: gpg-pubkey@c87f5b1a-593863f8.
```

**Review by knqyf263 — APPROVED** [review]
