### PR TITLE
fix(license): normalize licenses for PostAnalyzers

### LINKED ISSUE #9940: bug(license): Trivy doesn't normalize licenses for packages got from PostAnalyzers
## Description
We normalize licenses when converting detected `Packages` and `Dependencies` into `Applications`:
https://github.com/aquasecurity/trivy/blob/b885d3a3693a62bd2f506aeb238025242735ef1d/pkg/fanal/analyzer/language/analyze.go#L108-L110

However, for some post-analyzers we follow a different flow:
1. Run the Analyze or Parse function (which already converts results into Applications).
2. Enrich package licenses afterward.

As a result, licenses are not normalized in these cases.

### Discussed in https://github.com/aquasecurity/trivy/discussions/9938

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Normalize licenses in PostAnalyzers when Applications are produced first and licenses are enriched afterward.

## Example
before:
```bash
➜ trivy -q fs ./requirements.txt -f json | jq '.Results[].Packages[] | select (.Name=="ultralytics") | .Licenses'
[
  "GNU Affero General Public License v3 or later (AGPLv3+)"
]
```
after:
```bash
➜ ./trivy -q fs ./requirements.txt -f json | jq '.Results[].Packages[] | select (.Name=="ultralytics") | .Licenses'
[
  "AGPL-3.0-or-later"
]
```

## Related issues
- Close #9940

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/docs/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/docs/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/analyzer/language/analyze.go [hunk 1]
```diff
@@ -104,6 +104,7 @@ func toApplication(fileType types.LangType, filePath, libFilePath string, r xio.
 		pkgs[i].DependsOn = deps[pkg.ID]
 		pkgs[i].Digest = d
 		pkgs[i].Indirect = isIndirect(pkg.Relationship) // For backward compatibility
+		NormalizeLicenses(pkgs[i].Licenses)
```
Comment (knqyf263) [inline pkg/fanal/analyzer/language/analyze.go]: In analyze.go:107-111:

```
NormalizeLicenses(pkgs[i].Licenses)

for j, license := range pkg.Licenses {
    pkgs[i].Licenses[j] = licensing.Normalize(license)
}
```

The NormalizeLicenses() call on line 107 normalizes the licenses, then lines 109-111 iterate and normalize again. This seems redundant.

**Comment by DmitriyLewen** [comment]
I was thinking the same — it would be better to use this in a single place.
Thanks for pointing it out!

I moved the changes here:
https://github.com/aquasecurity/trivy/pull/9941/commits/5dd6894e974b7129b036444c49921af647cf2d4c

File: pkg/fanal/analyzer/language/analyze.go (hunk 1 above)
Comment (DmitriyLewen) [reply pkg/fanal/analyzer/language/analyze.go]: I remember removing this line.
It’s possible that I accidentally reverted this change.

File: pkg/fanal/analyzer/analyzer.go [hunk 2]
```diff
@@ -334,6 +336,31 @@ func belongToGroup(groupName Group, analyzerType Type, disabledAnalyzers []Type,
...
+		}
+	}
+	normalized = lo.Uniq(normalized)
+
+	if len(normalized) == 0 {
+		return nil
+	}
+
+	return normalized
+}
```
Comment (knqyf263) [inline pkg/fanal/analyzer/analyzer.go]: We can simplify this.

```diff
diff --git a/pkg/fanal/analyzer/analyzer.go b/pkg/fanal/analyzer/analyzer.go
index 92e34d401..8b6cfccc2 100644
--- a/pkg/fanal/analyzer/analyzer.go
+++ b/pkg/fanal/analyzer/analyzer.go
@@ -12,6 +12,7 @@ import (
 	"sync"
 
 	"github.com/samber/lo"
+	"github.com/samber/lo/it"
 	"golang.org/x/sync/errgroup"
 	"golang.org/x/sync/semaphore"
 	"golang.org/x/xerrors"
@@ -345,19 +346,12 @@ func normalizeApplicationsLicenses(applications []types.Application) {
 }
 
 func normalizeLicenses(licenses []string) []string {
-	var normalized []string
-	for _, l := range licenses {
-		l = licensing.Normalize(l)
-		if l != "" {
-			normalized = append(normalized, l)
-		}
-	}
-	normalized = lo.Uniq(normalized)
-
+	seq := it.UniqMap(slices.Values(licenses), licensing.Normalize)
+	seq = it.Compact(seq)
+	normalized := slices.Collect(seq)
 	if len(normalized) == 0 {
 		return nil
 	}
-
 	return normalized
 }
 ```

Comment (knqyf263) [reply pkg/fanal/analyzer/analyzer.go]: Also, what do you think about moving this function to the `licensing` package?

Comment (DmitriyLewen) [reply pkg/fanal/analyzer/analyzer.go]: > We can simplify this.

Thanks. Updated in b77146ff82e7b9933ec1268ba63dda5c1c551001

> Also, what do you think about moving this function to the licensing package?

Make sense 👍  Did refactoring in 29c9ba0b256d75958da3e77807194d105e668a42
