### PR TITLE
fix(cyclonedx): trim non-URL info for `advisory.url`

### LINKED ISSUE #6801: fix(cyclonedx): trim non-URL characters
## Description
Some advisories include invalid URLs, breaking CycloneDX.

e.g. `https://github.com/andk/cpanpm/commit/9c98370287f4e709924aee7c58ef21c85289a7f0 (2.35-TRIAL)`

The advisory contains the above string as a URL, so it should be their problem. However, we will trim the non-URL characters so that Trivy users are not disadvantaged by the problem.

### Discussed in https://github.com/aquasecurity/trivy/discussions/6224

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
trim non-URL info for [advisory.url](https://cyclonedx.org/docs/1.6/json/#vulnerabilities_items_advisories_items_url)
more info #6801

## Related issues
- Close #6801

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/sbom/cyclonedx/marshal.go [hunk 1]
```diff
@@ -345,6 +350,17 @@ func (*Marshaler) advisories(refs []string) *[]cdx.Advisory {
 	return &advs
 }
 
+// trimNonUrlInfo returns first valid URL.
+func trimNonUrlInfo(ref string) string {
+	ss := strings.Split(ref, " ")
```
Comment (knqyf263) [inline pkg/sbom/cyclonedx/marshal.go:355]: We just want to take the first block. `strings.Cut` seems enough.

```suggestion
	s, _, _ := strings.Cut(ref, " ")
```

Comment (DmitriyLewen) [reply pkg/sbom/cyclonedx/marshal.go:355]: What about case when `ref` starts with extra characters?
I haven't seen this case, but I think it's possible.
(e.g. `(2.35-TRIAL) https://github.com/andk/cpanpm/commit/9c98370287f4e709924aee7c58ef21c85289a7f0`)

Comment (knqyf263) [reply pkg/sbom/cyclonedx/marshal.go:355]: Yes, I thought about it and didn't think we could handle all edge cases. But it's still better to support more edge cases. Let's keep it as is.

**Review by knqyf263 — APPROVED** [review]
