### PR TITLE
fix(sbom): Use UUID as BomRef for packages with empty purl

### LINKED ISSUE #5449: bug(cyclonedx): wrong purl for local Go dependencies
### Discussed in https://github.com/aquasecurity/trivy/discussions/5434
We don't create PURL for local Go dependencies, but still create CycloneDX component:
```json
 "bom-ref": "pkg:/",
      "type": "library",
      "name": "./api",
      "purl": "pkg:/",
      "properties": [
...

  "dependencies": [
    {
      "ref": "03a5f5e8-87ca-4f07-9309-c5de465ce1a8",
      "dependsOn": [
        "pkg:/",
...
```

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
After #5190 we don't create purl for `Golang` dependencies with replace to local directory.
But we still create CycloneDX component, but `BomRef` and `purl` for these packages are incorrect.
See more in #5434 

We should skip wrong `purl` and use `UUID` for `BomRef` for these components.

## Related Issues
- Close #5449

## Related PRs
- [x] #5190

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by DmitriyLewen** [comment]
I thought about this case for a long time.
We don't create PURL for dependencies with local path as name:
https://github.com/aquasecurity/trivy/blob/26b4959541b8fb10adb5f454ad930c6e2b68a0a8/pkg/purl/purl.go#L368-L371

But perhaps we need to skip these dependencies when parsing Go files in `go-dep-parser`:
https://github.com/aquasecurity/go-dep-parser/blob/6f348921ea39b74251940077b07d337bb468f3c8/pkg/golang/binary/parse.go#L47-L66

@knqyf263 wdyt?

**Comment by DmitriyLewen** [comment]
As @knqyf263 correctly [said](https://github.com/aquasecurity/trivy/issues/5449#issuecomment-1783689618) - we need to save Go local packages using the UUID as the BomRef.

**Review by chen-keinan — APPROVED** [review]

File: pkg/sbom/cyclonedx/marshal.go [hunk 1]
```diff
@@ -234,8 +239,9 @@ func (e *Marshaler) rootComponent(r types.Report) (*core.Component, error) {
 		p, err := purl.NewPackageURL(purl.TypeOCI, r.Metadata, ftypes.Package{})
 		if err != nil {
 			return nil, xerrors.Errorf("failed to new package url for oci: %w", err)
-		} else if p.Type != "" {
-			root.PackageURL = &p
+		}
+		if p != nil {
```
Comment (knqyf263) [inline pkg/sbom/cyclonedx/marshal.go:243]: nit: Is there any reason to make it an independent if-statement rather than `else if`?

File: pkg/sbom/cyclonedx/marshal.go [hunk 2]
```diff
@@ -315,11 +321,17 @@ func pkgComponent(pkg Package) (*core.Component, error) {
...
+	version := pkg.Version
 	var group string
-	// use `group` field for GroupID and `name` for ArtifactID for jar files
-	if pkg.Type == ftypes.Jar {
-		name = pu.Name
-		group = pu.Namespace
+	// there are cases when we can't build purl
+	// e.g. local Go packages
+	if pu != nil {
+		version = pu.Version
```
Comment (knqyf263) [inline pkg/sbom/cyclonedx/marshal.go:329]: I'm probably missing something. Why do we need to override the version with the PURL version here?

File: pkg/sbom/cyclonedx/marshal.go (hunk 1 above)
Comment (DmitriyLewen) [reply pkg/sbom/cyclonedx/marshal.go:243]: I don't see point of using `else if`, because we return error when `err != nil`.
And independent `if` seems to me more readable.

File: pkg/sbom/cyclonedx/marshal.go (hunk 2 above)
Comment (DmitriyLewen) [reply pkg/sbom/cyclonedx/marshal.go:329]: We are currently using `PURL` version -https://github.com/aquasecurity/trivy/blob/e2fb3dd58f2800ffbeb106ace8e30032c2600e1e/pkg/sbom/cyclonedx/marshal.go#L372

I think it has to do with the version format.
We merge `version`, `release` and `epoch` for PURL - https://github.com/aquasecurity/trivy/blob/e2fb3dd58f2800ffbeb106ace8e30032c2600e1e/pkg/purl/purl.go#L211

Comment (knqyf263) [reply pkg/sbom/cyclonedx/marshal.go:329]: Oh, yes, that's correct. Thanks.

**Review by knqyf263 — APPROVED** [review]
