### PR TITLE
fix(report): hide empty table when all secrets/license/misconfigs are ignored

### LINKED ISSUE #7147: Report is not empty even if there are no findings: Part 2
### Discussed in https://github.com/aquasecurity/trivy/discussions/7134

<div type='discussions-op-text'>

<sup>Originally posted by **AntonKarasov** July  9, 2024</sup>
### Description

Hello,

I've already reported such a bug there - https://github.com/aquasecurity/trivy/issues/6351 but it is still reproducing for 0.52.0 and 0.53.0 versions.
I've noticed that trivy report/output is not empty even if there are no findings when some particular findings are in place in .trivyignore.yaml.
The previous version did not have such behavior as expected.
Our CI/CD relies on this report, if something exists within the report CI proceeds with different logic.

It reproduces for vuln and license scanners.

### Desired Behavior

Completely empty report:

./trivy --version
2024-03-19T15:10:56.700+0100	INFO	Loaded trivy.yaml
Version: 0.49.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2024-03-19 12:11:32.850008953 +0000 UTC
  NextUpdate: 2024-03-19 18:11:32.850008412 +0000 UTC
  DownloadedAt: 2024-03-19 13:37:47.401184 +0000 UTC
Policy Bundle:
  Digest: sha256:cdff1bc8c97e4f5cd04782b057c00f5ea8cd81147a506ac4be76bef13710f2d3
  DownloadedAt: 2024-03-14 12:20:41.064572 +0000 UTC

./trivy fs -q --scanners vuln .
2024-03-19T15:11:01.736+0100	INFO	Loaded trivy.yaml

### Actual Behavior

trivy --version
2024/07/09 17:20:39 INFO Loaded file_path=trivy.yaml
Version: 0.52.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2024-05-15 06:11:26.28841171 +0000 UTC
  NextUpdate: 2024-05-15 12:11:26.28841142 +0000 UTC
  DownloadedAt: 2024-05-15 11:26:24.448386 +0000 UTC
Check Bundle:
  Digest: sha256:6d0771effa53c6cf8130861fc3ac28f5515c35a028edb4bb1e67261b9218c80e
  DownloadedAt: 2024-05-17 14:18:27.189189 +0000 UTC
  
  
trivy fs --scanners license --severity UNKNOWN,HIGH,CRITICAL,MEDIUM .                                                                                                                                  
2024/07/09 17:20:30 INFO Loaded file_path=trivy.yaml
2024-07-09T17:20:30+02:00       INFO    License scanning is enabled
2024-07-09T17:20:31+02:00       INFO    Suppressing dependencies for development and testing. To display them, try the '--include-dev-deps' flag.

package-lock.json (license)

Total: 0 (UNKNOWN: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌─────────┬─────────┬────────────────┬──────────┐
│ Package │ License │ Classification │ Severity │
└─────────┴─────────┴────────────────┴──────────┘

### Reproduction Steps

```bash
1.Install latest(v0.53.0 or 0.52.0) trivy version 
2.Scan some package.json with findings
3.Add those findings to the .trivyignore.yaml
4.Scan it one more time
5.Observe non-empty report
6.Reapeat previous steps with the earlier trivy version(v0.49.0 for example)
7.Observe empty report
```

### Target

Filesystem

### Scanner

License

### Output Format

Table

### Mode

Standalone

### Debug Output

```bash
trivy fs --scanners license --debug --severity UNKNOWN,HIGH,CRITICAL,MEDIUM .                                                                                                                      
2024/07/09 17:25:49 INFO Loaded file_path=trivy.yaml
2024-07-09T17:25:49+02:00       DEBUG   Cache dir       dir="/Users/anton.karasov/Library/Caches/trivy"
2024-07-09T17:25:49+02:00       DEBUG   Parsed severities       severities=[UNKNOWN HIGH CRITICAL MEDIUM]
2024-07-09T17:25:49+02:00       DEBUG   Ignore statuses statuses=[0 1 2 4 5 6 7]
2024-07-09T17:25:49+02:00       INFO    License scanning is enabled
2024-07-09T17:25:49+02:00       DEBUG   Enabling misconfiguration scanners      scanners=[azure-arm cloudformation dockerfile helm kubernetes terraform terraformplan-json terraformplan-snapshot]
2024-07-09T17:25:49+02:00       DEBUG   Initializing scan cache...      type="memory"
2024-07-09T17:25:49+02:00       DEBUG   [nuget] The nuget packages directory couldn't be found. License search disabled
2024-07-09T17:25:49+02:00       DEBUG   Skipping path   path=".git"
2024-07-09T17:25:50+02:00       DEBUG   OS is not detected.
2024-07-09T17:25:50+02:00       INFO    Suppressing dependencies for development and testing. To display them, try the '--include-dev-deps' flag.
2024-07-09T17:25:50+02:00       DEBUG   Found an ignore yaml    path=".trivyignore.yaml"

package-lock.json (license)

Total: 0 (UNKNOWN: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌─────────┬─────────┬────────────────┬──────────┐
│ Package │ License │ Classification │ Severity │
└─────────┴─────────┴────────────────┴──────────┘
```

### Operating System

macOS Sonoma

### Version

```bash
trivy --version                                                                                                          
2024/07/09 17:27:17 INFO Loaded file_path=trivy.yaml
Version: 0.53.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2024-05-15 06:11:26.28841171 +0000 UTC
  NextUpdate: 2024-05-15 12:11:26.28841142 +0000 UTC
  DownloadedAt: 2024-05-15 11:26:24.448386 +0000 UTC
Check Bundle:
  Digest: sha256:6d0771effa53c6cf8130861fc3ac28f5515c35a028edb4bb1e67261b9218c80e
  DownloadedAt: 2024-05-17 14:18:27.189189 +0000 UTC
```

### Checklist

- [X] Run `trivy clean --all`
- [ ] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)</div>

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
We added hiding empty tables for suppressed vulnerabilities in #6352.
This PR hides tables for ignored `secrets`, `licenses` and `misconfigurations`

Before:
```bash
...
2024-07-16T13:36:54+06:00       DEBUG   Ignored id="MIT" target="package-lock.json"

Dockerfile (dockerfile)

Tests: 27 (SUCCESSES: 26, FAILURES: 0, EXCEPTIONS: 1)
Failures: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)


aws-secrets.txt (secrets)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)


package-lock.json (license)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌─────────┬─────────┬────────────────┬──────────┐
│ Package │ License │ Classification │ Severity │
└─────────┴─────────┴────────────────┴──────────┘

Process finished with the exit code 0

```

after:
```bash
2024-07-16T13:36:54+06:00       DEBUG   Ignored id="MIT" target="package-lock.json"

Process finished with the exit code 0
```

## Related issues
- Close #7147

## Related PRs
- [x] #6352

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/report/table/misconfig.go [hunk 1]
```diff
@@ -50,6 +50,11 @@ func NewMisconfigRenderer(result types.Result, severities []dbTypes.Severity, tr
 }
 
 func (r *misconfigRenderer) Render() string {
+	// Trivy doesn't currently support showing suppressed misconfigs
+	// So just skip this result
+	if len(r.result.Misconfigurations) == 0 {
+		return ""
+	}
```
Comment (DmitriyLewen) [inline pkg/report/table/misconfig.go:57]: @simar7 @nikpivkin 
Do we need to hide table if any misconfigs have been ignored?

Comment (nikpivkin) [reply pkg/report/table/misconfig.go:57]: The report displays misconfigurations as a list, not a table, with the header showing the number of ignored results.  I don't think this is worth hiding. @simar7 wdyt?

Comment (DmitriyLewen) [reply pkg/report/table/misconfig.go:57]: right. It looks like that:
```
Dockerfile (dockerfile)

Tests: 27 (SUCCESSES: 26, FAILURES: 0, EXCEPTIONS: 1)
Failures: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
but by default - if no `failures` are found - we hide it.

Comment (simar7) [reply pkg/report/table/misconfig.go:57]: @DmitriyLewen you mean this right?

```
$ trivy config .                                 
2024-07-16T22:12:14-06:00       INFO    Misconfiguration scanning is enabled
2024-07-16T22:12:15-06:00       INFO    Detected config files   num=0

$  empty-dir tree
.

0 directories, 0 files
```

If so, I think this behavior is fine as-is because it is inline with the other scanners:

```
 trivy fs .
2024-07-16T22:14:13-06:00       INFO    Vulnerability scanning is enabled
2024-07-16T22:14:13-06:00       INFO    Secret scanning is enabled
2024-07-16T22:14:13-06:00       INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-07-16T22:14:13-06:00       INFO    Please see also https://aquasecurity.github.io/trivy/v0.53/docs/scanner/secret#recommendation for faster secret detection
2024-07-16T22:14:13-06:00       INFO    Number of language-specific files       num=0

```

Comment (DmitriyLewen) [reply pkg/report/table/misconfig.go:57]: @simar7 take a look the following example:

Dockerfile without misconfigs:
```bash
➜  cat Dockerfile           
FROM alpine:3.12.1

COPY 123.txt 123.txt

USER patrick

HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost/ || exit 1 
➜  trivy config ./Dockerfile
2024-07-17T10:24:20+06:00	INFO	Misconfiguration scanning is enabled
2024-07-17T10:24:21+06:00	INFO	Detected config files	num=1
```
Dockerfile with misconfig:
```bash
➜  cat Dockerfile 
FROM alpine:3.12.1

ADD 123.txt 123.txt

USER patrick

HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost/ || exit 1
 
➜  trivy config ./Dockerfile
2024-07-17T10:25:09+06:00	INFO	Misconfiguration scanning is enabled
2024-07-17T10:25:10+06:00	INFO	Detected config files	num=1

Dockerfile (dockerfile)

Tests: 27 (SUCCESSES: 26, FAILURES: 1, EXCEPTIONS: 0)
Failures: 1 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
Dockerfile with ignored misconfig  
```bash
➜  cat Dockerfile 
FROM alpine:3.12.1

ADD 123.txt 123.txt

USER patrick

HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost/ || exit 1 

➜  cat .trivyignore.yaml 
misconfigurations:
  - id: AVD-DS-0005                                                           

➜ trivy config ./Dockerfile --ignorefile .trivyignore.yaml 
2024-07-17T10:26:56+06:00	INFO	Misconfiguration scanning is enabled
2024-07-17T10:26:56+06:00	INFO	Detected config files	num=1

Dockerfile (dockerfile)

Tests: 27 (SUCCESSES: 26, FAILURES: 0, EXCEPTIONS: 1)
Failures: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

## Trivy after these changes
➜  ./trivy config ./Dockerfile --ignorefile .trivyignore.yaml
2024-07-17T10:42:43+06:00	INFO	Misconfiguration scanning is enabled
2024-07-17T10:42:44+06:00	INFO	Detected config files	num=1

```

Comment (simar7) [reply pkg/report/table/misconfig.go:57]: Right I understand the change, I'm just saying that we shouldn't hide the fact that we've ignored stuff. I guess the difference lies in the fact that other scanners don't have the `EXCEPTIONS` field while misconfigurations scanner does. 

IMO, showing more info to the user is useful and create less opportunity for confusion. In misconfiguration scanning, we show the user how many config files we've scanned via the `Detected config files num=1` log output. This was done to differentiate the case when there's no misconfiguration vs there was no relevant file to find misconfigurations in.

I'm not sure of the original motivation for this PR but when things are ignored and not shown, it can be due to either us not finding an issue or the issue getting ignored (by an ignore policy).

Comment (DmitriyLewen) [reply pkg/report/table/misconfig.go:57]: > I'm not sure of the original motivation for this PR 

We hide empty tables to avoid very large output (as is the case with tables for language files without vulnerabilities).

>  I guess the difference lies in the fact that other scanners don't have the EXCEPTIONS field while misconfigurations scanner does.

right. That is why i asked you about this.

> we show the user how many config files we've scanned via the Detected config files num=1 log output.

We also show ignored files in `debug` log:
```bash
2024-07-17T11:19:03+06:00	DEBUG	Ignored	id="AVD-DS-0005" target="Dockerfile"
```

Just to make sure I understand you correctly - if all `failure` tests are ignored - we can hide the header with the number of tests (e.g. `Tests: 27 (SUCCESSES: 26, FAILURES: 0, EXCEPTIONS: 1)`), right?

Comment (simar7) [reply pkg/report/table/misconfig.go:57]: Hmm I see yeah I think based on what you said regarding showing debug log message and the fact it inlines the behavior with the other scanners, we should hide it.

But at the same time, maybe we should also drop support for `EXCEPTIONS` as a whole since no other scanner has a concept for it. Is it worth tracking ignored misconfigurations/vulnerabilities?

Comment (DmitriyLewen) [reply pkg/report/table/misconfig.go:57]: > maybe we should also drop support for EXCEPTIONS as a whole since no other scanner has a concept for it.

Unfortunately, I can't correctly assess how necessary this is. That's why I turned to you :smile:

> Is it worth tracking ignored misconfigurations/vulnerabilities?

Users can check ignored vulns using `--show-suppressed` flag - https://aquasecurity.github.io/trivy/v0.53/docs/configuration/filtering/#suppression

Comment (simar7) [reply pkg/report/table/misconfig.go:57]: I personally think it's reasonable to drop support for Exceptions since:

1. No other scanner uses it today. So the concept of Exceptions only exists in misconfiguration scanning. I believe the original concept originated from [conftest](https://www.conftest.dev/exceptions/) but we have diverged quite a bit from that now in Trivy.
2. The fact that it isn't very useful once we start to hide misconfigurations, if they are ignored. 

It will obviously be a breaking change that we will need to announce.

What do you think @knqyf263 @itaysk?

Comment (knqyf263) [reply pkg/report/table/misconfig.go:57]: It sounds reasonable. It's more aligned with other scanners.

Comment (DmitriyLewen) [reply pkg/report/table/misconfig.go:57]: We can then merge this PR and create a new issue to remove the Exceptions field.
@simar7 can you open new issue?

**Comment by DmitriyLewen** [comment]
@knqyf263 @simar7 review this PR, when you have time, please.

**Review by knqyf263 — APPROVED** [review]

File: pkg/report/table/misconfig.go (hunk 1 above)
Comment (simar7) [reply pkg/report/table/misconfig.go:57]: Created an issue to track https://github.com/aquasecurity/trivy/issues/7314
