### PR TITLE
fix(cli): replace '-' to '_' for env vars

### LINKED ISSUE #2559: ENV vars broken
## Description

Env vars are no longer working as expected.

## What did you expect to happen?

Setting cache-dir using env var TRIVY_CACHE_DIR

## What happened instead?

Setting cache-dir using env var TRIVY_CACHE_DIR has no effect

## Output of run with `-debug`:

```
docker run -it --rm -e TRIVY_CACHE_DIR="/.trivycache" ghcr.io/aquasecurity/trivy:0.30.0 --debug image alpine:3.16
2022-07-21T08:31:35.917Z	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-07-21T08:31:35.923Z	DEBUG	cache dir:  /.trivycache
```
```
docker run -it --rm -e TRIVY_CACHE_DIR="/.trivycache" ghcr.io/aquasecurity/trivy:0.30.1 --debug image alpine:3.16
2022-07-21T08:31:57.259Z	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2022-07-21T08:31:57.274Z	DEBUG	cache dir:  /root/.cache/trivy
```

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Trivy env variables currently include "-"  instead of "_". 
Added replacement for these envs.

## Related issues
- Close #2559

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/flag/options.go [hunk 1]
```diff
@@ -202,9 +202,9 @@ func (f *Flags) groups() []FlagGroup {
 	if f.SecretFlagGroup != nil {
 		groups = append(groups, f.SecretFlagGroup)
 	}
-	if f.LicenseFlagGroup != nil {
-		groups = append(groups, f.LicenseFlagGroup)
-	}
+	//if f.LicenseFlagGroup != nil {
+	//	groups = append(groups, f.LicenseFlagGroup)
+	//}
```
Comment (afdesk) [inline pkg/flag/options.go:207]: why is this block commented?

**Review by knqyf263 — APPROVED** [review]

File: pkg/flag/options.go (hunk 1 above)
Comment (DmitriyLewen) [reply pkg/flag/options.go]: Oh... thank you! I checked another issue.
I removed it.

**Review by afdesk — APPROVED** [review]
