### PR TITLE
fix(sbom): fix panic for `convert` mode when scanning json file derived from sbom file

### LINKED ISSUE #6780: segmentation violation when running trivy in convert mode
### Discussed in https://github.com/aquasecurity/trivy/discussions/6775

<div type='discussions-op-text'>

<sup>Originally posted by **scott-boost** May 25, 2024</sup>
### Description

When I try to convert a Trivy JSON to CycloneDX, I get the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x10941ea6c]
```

### Desired Behavior

a cyclonedx json file

### Actual Behavior

segmentation violation error

### Reproduction Steps

```bash
1. `trivy image --format cyclonedx ubuntu:latest --output /tmp/cdx_without_vulns.json`
2. `trivy sbom --format json --output /tmp/trivy_with_vulns.json /tmp/cdx_without_vulns.json`
3. `trivy convert --format cyclonedx  /tmp/trivy_with_vulns.json`
```

### Target

SBOM

### Scanner

Vulnerability

### Output Format

CycloneDX

### Mode

Standalone

### Debug Output

```bash
2024-05-24T14:06:54-04:00       DEBUG   ["cyclonedx" "spdx" "spdx-json" "github"] automatically enables '--list-all-pkgs'.
2024-05-24T14:06:54-04:00       DEBUG   Parsed severities       severities=[UNKNOWN LOW MEDIUM HIGH CRITICAL]
2024-05-24T14:06:54-04:00       INFO    "--format cyclonedx" disables security scanning. Specify "--scanners vuln" explicitly if you want to include vulnerabilities in the CycloneDX report.
2024-05-24T14:06:54-04:00       DEBUG   Writing report to output...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x106772a6c]

goroutine 1 [running]:
github.com/aquasecurity/trivy/pkg/sbom/core.(*BOM).Root(0x0)
        github.com/aquasecurity/trivy/pkg/sbom/core/bom.go:279 +0x1c
github.com/aquasecurity/trivy/pkg/sbom/io.(*Encoder).rootComponent(_, {0x2, {0x137f2660, 0xedde2cb7d, 0x10f5ce840}, {0x14001720ca0, 0x1b}, {0x14002cdc9a7, 0x9}, {0x0, ...}, ...})
        github.com/aquasecurity/trivy/pkg/sbom/io/encode.go:86 +0x140
github.com/aquasecurity/trivy/pkg/sbom/io.(*Encoder).Encode(_, {0x2, {0x137f2660, 0xedde2cb7d, 0x10f5ce840}, {0x14001720ca0, 0x1b}, {0x14002cdc9a7, 0x9}, {0x0, ...}, ...})
        github.com/aquasecurity/trivy/pkg/sbom/io/encode.go:31 +0x4c
github.com/aquasecurity/trivy/pkg/sbom/cyclonedx.(*Marshaler).MarshalReport(_, {_, _}, {0x2, {0x137f2660, 0xedde2cb7d, 0x10f5ce840}, {0x14001720ca0, 0x1b}, {0x14002cdc9a7, ...}, ...})
        github.com/aquasecurity/trivy/pkg/sbom/cyclonedx/marshal.go:52 +0x6c
github.com/aquasecurity/trivy/pkg/report/cyclonedx.Writer.Write({{_, _}, _, {{_, _}, _, _}}, {_, _}, {0x2, ...})
        github.com/aquasecurity/trivy/pkg/report/cyclonedx/cyclonedx.go:31 +0x78
github.com/aquasecurity/trivy/pkg/report.Write({_, _}, {0x2, {0x137f2660, 0xedde2cb7d, 0x10f5ce840}, {0x14001720ca0, 0x1b}, {0x14002cdc9a7, 0x9}, ...}, ...)
        github.com/aquasecurity/trivy/pkg/report/writer.go:99 +0x778
github.com/aquasecurity/trivy/pkg/commands/convert.Run({_, _}, {{{0x108856773, 0xa}, 0x0, 0x0, 0x1, 0x0, 0x45d964b800, {0x1400281a8a0, ...}, ...}, ...})
        github.com/aquasecurity/trivy/pkg/commands/convert/run.go:43 +0x498
github.com/aquasecurity/trivy/pkg/commands.NewConvertCommand.func2(0x140028eb208, {0x14002b6e840, 0x1, 0x4})
        github.com/aquasecurity/trivy/pkg/commands/app.go:525 +0x154
github.com/spf13/cobra.(*Command).execute(0x140028eb208, {0x14002b6e800, 0x4, 0x4})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000205208)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(0x1088c4026?)
        github.com/spf13/cobra@v1.8.0/command.go:1039 +0x1c
main.run()
        github.com/aquasecurity/trivy/cmd/trivy/main.go:41 +0x158
main.main()
        github.com/aquasecurity/trivy/cmd/trivy/main.go:19 +0x20
```

### Operating System

macOS Sonoma 14.4.1

### Version

```bash
Version: 0.51.4
```

### Checklist

- [X] Run `trivy image --reset`
- [X] Read [the troubleshooting](https://aquasecurity.github.io/trivy/latest/docs/references/troubleshooting/)</div>

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
See #6780

## Related issues
- Close #6780

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/sbom/io/encode_test.go [hunk 1]
```diff
@@ -562,6 +654,9 @@ func TestEncoder_Encode(t *testing.T) {
 		t.Run(tt.name, func(t *testing.T) {
 			uuid.SetFakeUUID(t, "3ff14136-e09f-4df9-80ea-%012d")
 
+			if tt.addBOMFunc != nil {
+				tt.report.BOM = tt.addBOMFunc()
```
Comment (knqyf263) [inline pkg/sbom/io/encode_test.go:658]: Why don't we add BOM [here](https://github.com/aquasecurity/trivy/pull/6808/files#diff-c5b3c454bb8e04604ef01e02f61e67f9f58631781e30671d252acb293a8d6897R542)?

Comment (DmitriyLewen) [reply pkg/sbom/io/encode_test.go]: In this case we will create `BOM` before running test case and `fakeUUID` not be used.

But i think we can just create another `SetFakeUUID` with different format to create the BOM.
Check https://github.com/aquasecurity/trivy/pull/6808/commits/068b89048a50e53075546e18fef94104d5c710aa please

**Review by knqyf263 — APPROVED** [review]
