### PR TITLE
fix(license): handle SPDX WITH exceptions as single license in category detection

### LINKED ISSUE #9379: bug(license): Trivy splits licenses that include the WITH separator when determining the category.
## Description
Trivy checks licenses that include `WITH` separator as multiple licenses when determining license category:

```bash
➜ cat trivy-full.yaml
license:
    notice:
        - Similar to Apache License but with the acknowledgment clause removed
        - "Similar to Apache License but with the acknowledgment clause removed"                                                                                                       ➜ trivy -q fs ./pom.xml --scanners license --table-mode detailed --config ./trivy-full.yaml     

pom.xml (license)

Total: 1 (UNKNOWN: 1, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌───────────────┬──────────────────────────────────────────────────────────────┬────────────────┬──────────┐
│    Package    │                           License                            │ Classification │ Severity │
├───────────────┼──────────────────────────────────────────────────────────────┼────────────────┼──────────┤
│ org.jdom:jdom │ Similar to Apache License but with the acknowledgment clause │ Non Standard   │ UNKNOWN  │
│               │ removed                                                      │                │          │
└───────────────┴──────────────────────────────────────────────────────────────┴────────────────┴──────────┘
➜ cat trivy-separated.yaml 
license:
    notice:
        - Similar to Apache License but
        - the acknowledgment clause removed                                                                                                                                                
➜ trivy -q fs ./pom.xml --scanners license --table-mode detailed --config ./trivy-separated.yaml

pom.xml (license)

Total: 1 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌───────────────┬──────────────────────────────────────────────────────────────┬────────────────┬──────────┐
│    Package    │                           License                            │ Classification │ Severity │
├───────────────┼──────────────────────────────────────────────────────────────┼────────────────┼──────────┤
│ org.jdom:jdom │ Similar to Apache License but with the acknowledgment clause │ Notice         │ LOW      │
│               │ removed                                                      │                │          │
└───────────────┴──────────────────────────────────────────────────────────────┴────────────────┴──────────┘
``` 
### Discussed in https://github.com/aquasecurity/trivy/discussions/9371

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
  This PR improves the licensing scanner to handle SPDX license expressions with the WITH operator and implements case-insensitive license matching for better compatibility.

  Key Changes:

  1. SPDX WITH Exception Handling: Added special handling for the WITH operator in compound expressions (e.g., "GPL-2.0-only WITH Classpath-exception-2.0"). These expressions are now treated as single licenses for category detection
  rather than being processed as compound expressions.
  2. Case-Insensitive License Matching: The CaseInsensitive set is used to avoid case-insensitive issues in licenses.

## Example
config file:
```yaml
license:
    notice:
        - Similar to Apache License but with the acknowledgment clause removed
```
before:
```bash
➜ trivy -q fs ./pom.xml --scanners license --table-mode detailed --config ./trivy-full.yaml     
pom.xml (license)

Total: 1 (UNKNOWN: 1, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌───────────────┬──────────────────────────────────────────────────────────────┬────────────────┬──────────┐
│    Package    │                           License                            │ Classification │ Severity │
├───────────────┼──────────────────────────────────────────────────────────────┼────────────────┼──────────┤
│ org.jdom:jdom │ Similar to Apache License but with the acknowledgment clause │ Non Standard   │ UNKNOWN  │
│               │ removed                                                      │                │          │
└───────────────┴──────────────────────────────────────────────────────────────┴────────────────┴──────────┘
```

after:
```bash
➜  ./trivy -q fs ./pom.xml --scanners license --table-mode detailed --config ./trivy-full.yaml

pom.xml (license)

Total: 1 (UNKNOWN: 0, LOW: 1, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

┌───────────────┬──────────────────────────────────────────────────────────────┬────────────────┬──────────┐
│    Package    │                           License                            │ Classification │ Severity │
├───────────────┼──────────────────────────────────────────────────────────────┼────────────────┼──────────┤
│ org.jdom:jdom │ Similar to Apache License but with the acknowledgment clause │ Notice         │ LOW      │
│               │ removed                                                      │                │          │
└───────────────┴──────────────────────────────────────────────────────────────┴────────────────┴──────────┘

```

## Related issues
- Close #9379

## Checklist
- [x] I've read the [guidelines for contributing](https://trivy.dev/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://trivy.dev/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by knqyf263** [comment]
I hope this PR helps.
https://github.com/aquasecurity/trivy/pull/9720

File: pkg/licensing/scanner.go [hunk 1]
```diff
@@ -13,17 +13,16 @@ import (
 	"github.com/aquasecurity/trivy/pkg/set"
 )
 
-type ScannerOption struct {
```
Comment (DmitriyLewen) [inline pkg/licensing/scanner.go:16]: Unused struct.

**Review by knqyf263 — APPROVED** [review]
