### PR TITLE
Skip downloading DB if a remote DB is not updated

### LINKED ISSUE #684: Skip downloading DB if a remote DB is not updated
When the cron job building trivy-db on GitHub Actions fails, trivy downloads an old DB and tries to download the latest db again at every start time.
https://github.com/aquasecurity/trivy/issues/675

Trivy should skip downloading DB if a remote DB is not updated.

### PR DESCRIPTION
**Pull request by mozillazg**
Closes #684 and depend on https://github.com/aquasecurity/trivy-db/pull/84 and https://github.com/aquasecurity/trivy/pull/718

```
2020-10-25T20:11:50.923+0800    DEBUG   DB update was skipped because DB was downloaded during the last hour
2020-10-25T20:11:50.923+0800    DEBUG   DB Schema: 1, Type: 1, UpdatedAt: 2020-10-25 00:43:05.269422607 +0000 UTC, NextUpdate: 2020-10-25 12:03:05.269422107 +0000 UTC, DownloadedAt: 2020-10-25 12:10:42.279962 +0000 UTC
```

### CODE REVIEW

File: pkg/db/db_test.go [hunk 1]
```diff
@@ -133,6 +133,30 @@ func TestClient_NeedsUpdate(t *testing.T) {
 			skip:          true,
 			expectedError: xerrors.New("--skip-update cannot be specified with the old DB"),
 		},
+		{
+			name:  "happly with old DownloadedAt",
```
Comment (knqyf263) [inline pkg/db/db_test.go:137]:
```suggestion
			name:  "happy with old DownloadedAt",
```

File: pkg/vulnerability/vulnerability_test.go [hunk 2]
```diff
@@ -212,65 +212,6 @@ func TestClient_FillInfo(t *testing.T) {
 				},
 			},
 		},
-		{
```
Comment (knqyf263) [inline pkg/vulnerability/vulnerability_test.go:215]: Could you tell me why you removed this test case?

File: pkg/db/db.go [hunk 3]
```diff
@@ -117,10 +118,15 @@ func (c Client) NeedsUpdate(cliVersion string, light, skip bool) (bool, error) {
...
-		return false, nil
+	if db.SchemaVersion == metadata.Version && metadata.Type == dbType {
+		if c.clock.Now().Before(metadata.NextUpdate) {
+			log.Logger.Debug("DB update was skipped because DB is the latest")
+			return false, nil
+		}
+		if c.clock.Now().Before(metadata.DownloadedAt.Add(time.Hour)) {
+			log.Logger.Debug("DB update was skipped because DB was downloaded during the last hour")
+			return false, nil
+		}
```
Comment (knqyf263) [inline pkg/db/db.go:129]: To pass the linter test, we have to define another function like `IsLatestDB` or `IsNewDB`.

**Review by knqyf263 — COMMENTED** [review]
Thanks for your contribution!

File: pkg/vulnerability/vulnerability_test.go (hunk 2 above)
Comment (mozillazg) [reply pkg/vulnerability/vulnerability_test.go:215]: Because the `VendorVectors` field has been removed in https://github.com/aquasecurity/trivy-db/pull/71 and I have open an PR for this: https://github.com/aquasecurity/trivy/pull/718

Comment (knqyf263) [reply pkg/vulnerability/vulnerability_test.go:215]: I see. I merged the PR. Thanks!

**Comment by mozillazg** [comment]
@knqyf263 Thanks for your review. The linter test is pass now, please check again.

**Review by knqyf263 — APPROVED** [review]
I refactored a bit. Thanks for the great contribution!
