### PR TITLE
fix(sbom): update logic for work with files in spdx format

### LINKED ISSUE #4511: spdx format has incorrect location for `files` array
### Discussed in https://github.com/aquasecurity/trivy/discussions/4507

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
`spdx/tools-golang`changed logic for working with files.
We need to move files array from `Package.Files` to `Files`.
Also they changed logic to work with `hasFiles` - https://github.com/spdx/tools-golang/pull/201

I add logic to work with files using `relationships`.
This logic work with files with `hasFiles`.

## Related issues
- Close #4511

## Related PRs
- [x] #4058

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/sbom/spdx/unmarshal.go [hunk 1]
```diff
@@ -192,9 +205,9 @@ func parsePkg(spdxPkg spdx.Package) (*ftypes.Package, error) {
 			return nil, xerrors.Errorf("failed to parse source info: %w", err)
 		}
 	}
-	for _, f := range spdxPkg.Files {
-		pkg.FilePath = f.FileName
-		break // Take the first file name
```
Comment (knqyf263) [inline pkg/sbom/spdx/unmarshal.go:197]: We probably should keep this logic for a while so that Trivy can parse old SPDX files.

File: pkg/sbom/spdx/unmarshal.go [hunk 2]
```diff
@@ -246,3 +259,30 @@ func parseSourceInfo(pkgType, sourceInfo string) (epoch int, name, ver, rel stri
 	}
 	return epoch, name, ver, rel, nil
 }
+
+// getPackageFilePaths parses Relationships and finds filepaths for packages
+func getPackageFilePaths(spdxDocument *spdx.Document) map[string]string {
+	packageFilePaths := map[string]string{}
+	fileSPDXIdentifierMap := createFileSPDXIdentifierMap(spdxDocument.Files)
+	for _, rel := range spdxDocument.Relationships {
+		if rel.Relationship == common.TypeRelationshipDescribe || rel.Relationship == "DESCRIBE" {
```
Comment (knqyf263) [inline pkg/sbom/spdx/unmarshal.go:268]: We can care about `CONTAINS` only, right?


```suggestion
		if rel.Relationship != common.TypeRelationshipContains && rel.Relationship != "CONTAIN" {
```

File: pkg/sbom/spdx/unmarshal.go (hunk 1 above)
Comment (DmitriyLewen) [reply pkg/sbom/spdx/unmarshal.go:197]: We don't need that. 
`tools-golang` converts `hasfiles` to `relationship` - https://github.com/spdx/tools-golang/blob/e939624e362e42cbd362b1d4ecaf1167a42d4901/spdx/v2/v2_2/document.go#L84 

I tested this case. 
Take a look on this testcase - https://github.com/aquasecurity/trivy/pull/4513/files#diff-6a7a7855bcf6bb4b61c399fb4a61a11959c089f7669a0785117f98b8efc25e89R60

File: pkg/sbom/spdx/unmarshal.go (hunk 2 above)
Comment (DmitriyLewen) [reply pkg/sbom/spdx/unmarshal.go]: Right! Made in https://github.com/aquasecurity/trivy/pull/4513/commits/01bb6e38d3d8f6d560300e02404b218ee2bd7111

File: pkg/sbom/spdx/unmarshal.go (hunk 1 above)
Comment (knqyf263) [reply pkg/sbom/spdx/unmarshal.go:197]: Oh, nice. It's ok, then.

**Review by knqyf263 — APPROVED** [review]
