### PR TITLE
fix(ubuntu): skip copyright files from subfolders

### LINKED ISSUE #3610: Inconsistent value for CycloneDX license
## Description

I am getting inconsistent results running trivy image <image> --format cyclonedx

For example, if I run `trivy image docker.io/istio/examples-bookinfo-reviews-v2:1.17.0 --format cyclonedx` sometimes the `ca-certificates` library shows

```JSON
                    "licenses": [
                      {
                        "expression": "..."
                      }
```

but other times

```JSON
  {
    "expression": "GPL-2.0"
  },
  {
    "expression": "MPL-2.0"
  }
```

This happens both with and without `--security-checks vuln`.

## What did you expect to happen?

If I run `trivy image docker.io/istio/examples-bookinfo-reviews-v2:1.17.0 --format cyclonedx | jq ".components[] | select(.name == \"ca-certificates\") | .licenses"` ten times I should see the same thing every time.

## What happened instead?

Sometimes I get the first JSON snippet above, sometimes the other.

## Output of run with `-debug`:

```
2023-02-13T15:32:30.426-0500	DEBUG	["cyclonedx" "spdx" "spdx-json" "github"] automatically enables '--list-all-pkgs'.
2023-02-13T15:32:30.426-0500	DEBUG	Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-02-13T15:32:30.426-0500	INFO	"--format cyclonedx" disables security checks. Specify "--security-checks vuln" explicitly if you want to include vulnerabilities in the CycloneDX report.
2023-02-13T15:32:30.470-0500	DEBUG	cache dir:  /Users/snible/Library/Caches/trivy
2023-02-13T15:32:31.315-0500	DEBUG	Image ID: sha256:284709b16dc196af239c270659f76544c9d815b5e828c65cf883100f508dd4cd
2023-02-13T15:32:31.315-0500	DEBUG	Diff IDs: [sha256:c3f11d77a5de76ec836c52333d45ac3742c7b27d3d83feba6ec978e223715c67 sha256:d9db04f7e324990348d55839435d8107a2261e0ba9a9ad6e01ff81170de6871e sha256:7b2ecb3010219e6ca266b8d913ded71cd53a484da17d8c7e66a88d431b55dc90 sha256:54564d12ff4491a58ddc6d696ad8df78974b7d104a129f86bcef2445659c69b1 sha256:06bf1f9f1452a05d87e3a9f67d25310e8bae1c2b95acc4518688c0e7507d6424 sha256:05781691fc4722b189e07fe1cd198547cd3f84464d5e6e0d39ec187ac2510e17 sha256:df117bc88874f17f258890a6e591e4bf31f7adc805204cf1c60d5f5b91128ff9 sha256:e05d3f145fd941ecf7217eff2a74ce54b942d08e799dccebee7a9964b922bbd8 sha256:2b99d6746ebd93eedb65658d4a52869a6122b405633fb9920439302c011dc844 sha256:9450aee4e26dc87c38fbca1d7e94de9c769a155d79a27820bea53ec1d294d8c0 sha256:5cdce5190f97770aac026f1c3b24e4389a6f4797dc413b0ed2fee4962bbd5ba5 sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef sha256:88162222133eda44828bc4f7b49a759b2cd83ba4a07803dbc559d98b7a533bf7]
2023-02-13T15:32:31.315-0500	DEBUG	Base Layers: [sha256:c3f11d77a5de76ec836c52333d45ac3742c7b27d3d83feba6ec978e223715c67 sha256:d9db04f7e324990348d55839435d8107a2261e0ba9a9ad6e01ff81170de6871e sha256:7b2ecb3010219e6ca266b8d913ded71cd53a484da17d8c7e66a88d431b55dc90 sha256:54564d12ff4491a58ddc6d696ad8df78974b7d104a129f86bcef2445659c69b1 sha256:06bf1f9f1452a05d87e3a9f67d25310e8bae1c2b95acc4518688c0e7507d6424 sha256:05781691fc4722b189e07fe1cd198547cd3f84464d5e6e0d39ec187ac2510e17 sha256:df117bc88874f17f258890a6e591e4bf31f7adc805204cf1c60d5f5b91128ff9 sha256:e05d3f145fd941ecf7217eff2a74ce54b942d08e799dccebee7a9964b922bbd8 sha256:2b99d6746ebd93eedb65658d4a52869a6122b405633fb9920439302c011dc844 sha256:9450aee4e26dc87c38fbca1d7e94de9c769a155d79a27820bea53ec1d294d8c0]
```

## Output of `trivy -v`:

```
Version: 0.36.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2023-02-13 18:08:46.345371425 +0000 UTC
  NextUpdate: 2023-02-14 00:08:46.345371225 +0000 UTC
  DownloadedAt: 2023-02-13 18:58:59.260511 +0000 UTC
```

## Additional details (base image name, container registry info...):

Thanks!

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
There are cases when `/usr/share/doc/*` folders contains subfolders with other `copyright` files.
e.g. `usr/share/doc/ca-certificates/examples/ca-certificates-local/debian/copyright`.
We need to skip these files.

## Related issues
- Close #3610

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/analyzer/pkg/dpkg/copyright.go [hunk 1]
```diff
@@ -128,6 +128,11 @@ func (a *dpkgLicenseAnalyzer) Init(opt analyzer.AnalyzerOptions) error {
 }
 
 func (a *dpkgLicenseAnalyzer) Required(filePath string, _ os.FileInfo) bool {
+	// To exclude files from subfolders
```
Comment (knqyf263) [inline pkg/fanal/analyzer/pkg/dpkg/copyright.go:131]: What if using `path.Match(usr/share/doc/*/copyright)`?

Comment (DmitriyLewen) [reply pkg/fanal/analyzer/pkg/dpkg/copyright.go:131]: It works. Thanks. Changed in e519052e68d8bdf4570bfbdf3654102be409d766

**Review by knqyf263 — APPROVED** [review]
