### PR TITLE
fix(php): skip `composer.lock` inside `vendor` folder

### LINKED ISSUE #2705: composer.lock files in vendor folder are scanned
## Description

I scanned an image with a php application and trivy scanned the composer.lock files in the vendor folder. But these do not reflect what is really installed, trivy should only scan the composer.lock of the application. 

This was also the case in the older versions.

## What did you expect to happen?

composer.lock files in the vendor folder should be ignored.

## What happened instead?

composer.lock Dateien im vendor Ordner werdne nicht ignoriert.

## Output of `trivy -v`:

```
Version: 0.30.4
Vulnerability DB:
  Version: 2
  UpdatedAt: 2022-08-15 06:07:55.064552776 +0000 UTC
  NextUpdate: 2022-08-15 12:07:55.064552376 +0000 UTC
  DownloadedAt: 2022-08-15 08:48:03.542538 +0000 UTC
```

### PR DESCRIPTION
**Pull request by afdesk**
## Description
`trivy` scans `composer.lock` files in the vendor folder, but these don't reflect what is really installed.
`composer.lock` files in the vendor folder should be ignored.

```sh
$ trivy -d image --vuln-type library phpmyadmin:5.0.2
```
before:
```sh
2022-08-23T15:28:49.140+0600	INFO	Number of language-specific files: 4
2022-08-23T15:28:49.140+0600	INFO	Detecting composer vulnerabilities...
2022-08-23T15:28:49.140+0600	DEBUG	Detecting library vulnerabilities, type: composer, path: var/www/html/vendor/pragmarx/google2fa/composer.lock
2022-08-23T15:28:49.141+0600	DEBUG	Detecting library vulnerabilities, type: composer, path: var/www/html/vendor/pragmarx/google2fa-qrcode/composer.lock
2022-08-23T15:28:49.141+0600	DEBUG	Detecting library vulnerabilities, type: composer, path: var/www/html/composer.lock
2022-08-23T15:28:49.142+0600	INFO	Detecting node-pkg vulnerabilities...
```
after:
```sh
2022-08-23T15:29:59.233+0600	INFO	Number of language-specific files: 2
2022-08-23T15:29:59.233+0600	INFO	Detecting composer vulnerabilities...
2022-08-23T15:29:59.233+0600	DEBUG	Detecting library vulnerabilities, type: composer, path: var/www/html/composer.lock
2022-08-23T15:29:59.234+0600	INFO	Detecting node-pkg vulnerabilities...

```

## Related issues
- Close #2705 

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/analyzer/language/php/composer/composer.go [hunk 1]
```diff
@@ -25,6 +26,21 @@ var requiredFiles = []string{types.ComposerLock}
...
 func (a composerLibraryAnalyzer) Analyze(_ context.Context, input analyzer.AnalysisInput) (*analyzer.AnalysisResult, error) {
+	// we should skip `composer.lock` inside `vendor` folder
+	if sep := string(os.PathSeparator); strings.Contains(input.FilePath, "vendor"+sep) {
+		file := filepath.Base(input.FilePath)
+		subDirs := strings.Split(input.FilePath, sep)
+		for i, s := range subDirs {
+			if s == "vendor" {
+				path := filepath.Join(subDirs[:i]...)
+				f := filepath.Join(path, file)
+				if _, err := os.Stat(f); err == os.ErrNotExist {
```
Comment (knqyf263) [inline pkg/fanal/analyzer/language/php/composer/composer.go:37]: `os.Stat` doesn't work if it is from a tar file.

File: pkg/fanal/analyzer/language/php/composer/composer.go [hunk 2]
```diff
@@ -25,6 +26,21 @@ var requiredFiles = []string{types.ComposerLock}
 type composerLibraryAnalyzer struct{}
 
 func (a composerLibraryAnalyzer) Analyze(_ context.Context, input analyzer.AnalysisInput) (*analyzer.AnalysisResult, error) {
+	// we should skip `composer.lock` inside `vendor` folder
```
[the remark this answers is not in the document]
Comment (afdesk) [reply pkg/fanal/analyzer/language/php/composer/composer.go]: sure, done

File: pkg/fanal/analyzer/language/php/composer/composer.go [hunk 3]
```diff
@@ -35,7 +36,15 @@ func (a composerLibraryAnalyzer) Analyze(_ context.Context, input analyzer.Analy
 
 func (a composerLibraryAnalyzer) Required(filePath string, _ os.FileInfo) bool {
 	fileName := filepath.Base(filePath)
-	return utils.StringInSlice(fileName, requiredFiles)
+	if !utils.StringInSlice(fileName, requiredFiles) {
+		return false
+	}
+
+	// we should skip `composer.lock` inside `vendor` folder
+	if sep := string(os.PathSeparator); strings.Contains(filePath, sep+"vendor"+sep) || strings.HasPrefix(filePath, "vendor"+sep) {
```
Comment (knqyf263) [inline pkg/fanal/analyzer/language/php/composer/composer.go:44]: I suppose the path separator could be `/` when parsing tar files even though it runs on Windows. I didn't test it though. `ToSlash` might be safer.

```suggestion
	for _, p := range strings.Split(filepath.ToSlash(filePath), "/") {
		if p == "vendor" {
			return false
		}
	}
```

**Review by knqyf263 — APPROVED** [review]
