### PR TITLE
fix: use `--file-patterns` flag for all post analyzers

### LINKED ISSUE #6962: bug(scan): `--file-patterns` doesn't work for some `post-analyzers`
## Description
In most `post-analyzers` we use `required` function in `PostAnalyze`.
https://github.com/aquasecurity/trivy/blob/3eecfc6b6e1d6cef1497f7ff0044e676da159243/pkg/fanal/analyzer/language/nodejs/npm/npm.go#L49-L51
But we don't have info about `file-patterns` in `PostAnalyze` function.
That is why `--file-patterns` flag may not work.

We need to update our logic to take into account  `file-patterns` for `PostAnalyze`

## Related Issue
- #6946

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Use `--file-patterns` flag for all post analyzers.

## Related issues
- Close #6962

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

File: pkg/fanal/analyzer/language/python/packaging/packaging.go [hunk 1]
```diff
@@ -65,7 +66,7 @@ func (a packagingAnalyzer) PostAnalyze(_ context.Context, input analyzer.PostAna
 	var apps []types.Application
 
 	required := func(path string, _ fs.DirEntry) bool {
-		return filepath.Base(path) == "METADATA" || isEggFile(path)
+		return filepath.Base(path) == "METADATA" || isEggFile(path) || slices.Contains(input.FilePatterns, path)
```
Comment (knqyf263) [inline pkg/fanal/analyzer/language/python/packaging/packaging.go:69]: A file may not end with `.egg` if `--file-patterns` is specified. But I don't have a simple idea of how to handle that. We may want to ignore the edge case.
https://github.com/aquasecurity/trivy/blob/28ac1caafa18119d78f4ce0161e5121ce0531dd5/pkg/fanal/analyzer/language/python/packaging/packaging.go#L79

File: pkg/fanal/analyzer/analyzer.go [hunk 2]
```diff
@@ -142,8 +142,9 @@ type AnalysisInput struct {
 }
 
 type PostAnalysisInput struct {
-	FS      fs.FS
-	Options AnalysisOptions
+	FS           fs.FS
+	Options      AnalysisOptions
+	FilePatterns []string
```
Comment (knqyf263) [inline pkg/fanal/analyzer/analyzer.go:147]: Is this filed for file patterns? It looks like matched file paths.

File: pkg/fanal/analyzer/language/python/packaging/packaging.go (hunk 1 above)
Comment (knqyf263) [reply pkg/fanal/analyzer/language/python/packaging/packaging.go:69]: We may need to split this analyzer into two analyzers for `.egg` and `.egg-info`.

File: pkg/fanal/analyzer/analyzer.go (hunk 2 above)
Comment (DmitriyLewen) [reply pkg/fanal/analyzer/analyzer.go]: Updated filed name in https://github.com/aquasecurity/trivy/pull/7365/commits/5f493acb3671d7a2f53980b6e8a84c0236832613

File: pkg/fanal/analyzer/language/python/packaging/packaging.go (hunk 1 above)
Comment (DmitriyLewen) [reply pkg/fanal/analyzer/language/python/packaging/packaging.go]: > We may need to split this analyzer into two analyzers for .egg and .egg-info.

I agree with this decision.
Split analyzers in https://github.com/aquasecurity/trivy/pull/7365/commits/afb738737c72774849c3d701da92244d3b0b28ae

Comment (knqyf263) [reply pkg/fanal/analyzer/language/python/packaging/packaging.go]: Can we make it a separate PR?

Comment (DmitriyLewen) [reply pkg/fanal/analyzer/language/python/packaging/packaging.go]: I've developed a nasty habit of adding all the changes to one PR...

I created #7514 and reverted the changes in this PR - https://github.com/aquasecurity/trivy/pull/7365/commits/2b4f23b93a65d00dbc7c5bd919da3f800c04124f
After merging one of these PRs - I will update the second PR.
Tell me which PR you prefer to merge first

Comment (knqyf263) [reply pkg/fanal/analyzer/language/python/packaging/packaging.go]: #7514 looks easier to merge.

Comment (DmitriyLewen) [reply pkg/fanal/analyzer/language/python/packaging/packaging.go]: #7514 has been merged.
I merged main branch and updated `packaging` PostAnalyzer in https://github.com/aquasecurity/trivy/pull/7365/commits/a2cfee5cb233ef603d43db28c3ab32c4430db3c2

**Comment by knqyf263** [comment]
I've finally had some free time and am getting back to reviewing this PR.

While your implementation is more efficient, considering that the `fs.FS` [passed to PostAnalyze](https://github.com/aquasecurity/trivy/blob/126d6cd0338d5e8754cd5d5d1e1cb3d0b4bea481/pkg/fanal/analyzer/analyzer.go#L513) contains very few files, would it be acceptable to perform the file pattern matching again as shown below?

```diff
diff --git a/pkg/fanal/analyzer/analyzer.go b/pkg/fanal/analyzer/analyzer.go
index 3bf82c65a..0a103dad6 100644
--- a/pkg/fanal/analyzer/analyzer.go
+++ b/pkg/fanal/analyzer/analyzer.go
@@ -131,7 +131,7 @@ type AnalyzerGroup struct {
 	logger            *log.Logger
 	analyzers         []analyzer
 	postAnalyzers     []PostAnalyzer
-	filePatterns      map[Type][]*regexp.Regexp
+	filePatterns      map[Type]FilePatterns
 	detectionPriority types.DetectionPriority
 }
 
@@ -139,6 +139,17 @@ type AnalyzerGroup struct {
 // Analyzer input/output //
 ///////////////////////////
 
+type FilePatterns []*regexp.Regexp
+
+func (f FilePatterns) Match(filePath string) bool {
+	for _, pattern := range f {
+		if pattern.MatchString(filePath) {
+			return true
+		}
+	}
+	return false
+}
+
 type AnalysisInput struct {
 	Dir      string
 	FilePath string
@@ -149,8 +160,9 @@ type AnalysisInput struct {
 }
 
 type PostAnalysisInput struct {
-	FS      fs.FS
-	Options AnalysisOptions
+	FS           fs.FS
+	FilePatterns FilePatterns
+	Options      AnalysisOptions
 }
 
 type AnalysisOptions struct {
@@ -333,7 +345,7 @@ func NewAnalyzerGroup(opts AnalyzerOptions) (AnalyzerGroup, error) {
 
 	group := AnalyzerGroup{
 		logger:            log.WithPrefix("analyzer"),
-		filePatterns:      make(map[Type][]*regexp.Regexp),
+		filePatterns:      make(map[Type]FilePatterns),
 		detectionPriority: opts.DetectionPriority,
 	}
 	for _, p := range opts.FilePatterns {
@@ -350,7 +362,7 @@ func NewAnalyzerGroup(opts AnalyzerOptions) (AnalyzerGroup, error) {
 		}
 
 		if _, ok := group.filePatterns[Type(fileType)]; !ok {
-			group.filePatterns[Type(fileType)] = []*regexp.Regexp{}
+			group.filePatterns[Type(fileType)] = FilePatterns{}
 		}
 
 		group.filePatterns[Type(fileType)] = append(group.filePatterns[Type(fileType)], r)
@@ -422,7 +434,7 @@ func (ag AnalyzerGroup) AnalyzeFile(ctx context.Context, wg *sync.WaitGroup, lim
 			continue
 		}
 
-		if !ag.filePatternMatch(a.Type(), cleanPath) && !a.Required(cleanPath, info) {
+		if !ag.filePatterns[a.Type()].Match(cleanPath) && !a.Required(cleanPath, info) {
 			continue
 		}
 		rc, err := opener()
@@ -468,7 +480,7 @@ func (ag AnalyzerGroup) RequiredPostAnalyzers(filePath string, info os.FileInfo)
 	}
 	var postAnalyzerTypes []Type
 	for _, a := range ag.postAnalyzers {
-		if ag.filePatternMatch(a.Type(), filePath) || a.Required(filePath, info) {
+		if ag.filePatterns[a.Type()].Match(filePath) || a.Required(filePath, info) {
 			postAnalyzerTypes = append(postAnalyzerTypes, a.Type())
 		}
 	}
@@ -510,8 +522,9 @@ func (ag AnalyzerGroup) PostAnalyze(ctx context.Context, compositeFS *CompositeF
 		}
 
 		res, err := a.PostAnalyze(ctx, PostAnalysisInput{
-			FS:      filteredFS,
-			Options: opts,
+			FS:           filteredFS,
+			FilePatterns: ag.filePatterns[a.Type()],
+			Options:      opts,
 		})
 		if err != nil {
 			return xerrors.Errorf("post analysis error: %w", err)
@@ -526,15 +539,6 @@ func (ag AnalyzerGroup) PostAnalyzerFS() (*CompositeFS, error) {
 	return NewCompositeFS()
 }
 
-func (ag AnalyzerGroup) filePatternMatch(analyzerType Type, filePath string) bool {
-	for _, pattern := range ag.filePatterns[analyzerType] {
-		if pattern.MatchString(filePath) {
-			return true
-		}
-	}
-	return false
-}
-
 // StaticPaths collects static paths from all enabled analyzers
 // It returns the collected paths and a boolean indicating if all enabled analyzers implement StaticPathAnalyzer
 func (ag AnalyzerGroup) StaticPaths(disabled []Type) ([]string, bool) {
diff --git a/pkg/fanal/analyzer/language/golang/mod/mod.go b/pkg/fanal/analyzer/language/golang/mod/mod.go
index bb6117f3a..1c0a9b111 100644
--- a/pkg/fanal/analyzer/language/golang/mod/mod.go
+++ b/pkg/fanal/analyzer/language/golang/mod/mod.go
@@ -68,7 +68,7 @@ func (a *gomodAnalyzer) PostAnalyze(_ context.Context, input analyzer.PostAnalys
 	var apps []types.Application
 
 	required := func(path string, d fs.DirEntry) bool {
-		return filepath.Base(path) == types.GoMod
+		return input.FilePatterns.Match(path) || filepath.Base(path) == types.GoMod
 	}
 
 	err := fsutils.WalkDir(input.FS, ".", required, func(path string, d fs.DirEntry, _ io.Reader) error {
```

The advantage is that it avoids assigning a new variable, making the code simpler and easier for us to read. The downside could be performance, but I don't think the difference would be significant. Are there any other aspects I might have overlooked?

**Comment by DmitriyLewen** [comment]
I think your proposal is acceptable.

In fact, your implementation increases the number of calls for the filePatternMatch function (Match in your code) by a maximum of 2 times.

Some post analyzers will not run it again (5 out of 14 for language analyzers, I will clarify about configs).

So I don't see anything wrong if we execute the regular expression twice.

Also, I'm not sure that users use this flag too often (since we cover all standard formats/file names)

____

So i will resolve conflicts and implement your suggest.

**Comment by DmitriyLewen** [comment]
@knqyf263 I have updated PR.
Take a look, when you have time.

**Comment by DmitriyLewen** [comment]
@knqyf263 I have updated PR.
Take a look ,when you have time.

@nikpivkin It looks like we don't need to update the configuration analyzers.
But can you re-check, please?

**Review by knqyf263 — APPROVED** [review]

**Review by nikpivkin — APPROVED** [review]
LGTM!

Right, the misconfiguration scanner skips the additional check of configuration type if file patterns are passed, which I think is acceptable because in this case the user is sure of the type of file being scanned. The only thing is that Terraform scanner will not take patterns into account, because it selects the parser depending on the file extension: `tf.json` or `tf`.

**Comment by DmitriyLewen** [comment]
thanks for confirming this 👍

**Comment by nikpivkin** [comment]
If this becomes a problem, we can change the way we check and look at the first character to determine the JSON file.
